uipath-commons/main/default/objects/Account/fields/Account_ID_Long__c.field-meta.xml
<CustomField>
    <fullName>Account_ID_Long__c</fullName>
    <formula>CASESAFEID(Id)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Account ID Long</label>
    <type>Text</type>
</CustomField>

uipath-commons/main/default/objects/Account/fields/Area__c.field-meta.xml
<CustomField>
    <fullName>Area__c</fullName>
    <label>Area</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>MEA</fullName>
            </value>
            <value>
                <fullName>Central Europe</fullName>
            </value>
            <value>
                <fullName>EECIS</fullName>
            </value>
            <value>
                <fullName>Southern Europe</fullName>
            </value>
            <value>
                <fullName>Northern Europe</fullName>
            </value>
            <value>
                <fullName>Western Europe</fullName>
            </value>
            <value>
                <fullName>East</fullName>
            </value>
            <value>
                <fullName>Gov / Fed</fullName>
            </value>
            <value>
                <fullName>Central</fullName>
            </value>
            <value>
                <fullName>West</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

uipath-commons/main/default/objects/Account/fields/Geo__c.field-meta.xml
<CustomField>
        <fullName>Geo__c</fullName>
        <label>Geo</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>AMER</fullName>
                </value>
                <value>
                    <fullName>APAC</fullName>
                </value>
                <value>
                    <fullName>EMEA</fullName>
                </value>
                <value>
                    <fullName>Japan</fullName>
                </value>
                <value>
                    <fullName>India</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </CustomField>

uipath-commons/main/default/objects/Account/fields/Region__c.field-meta.xml
<CustomField>
    <fullName>Region__c</fullName>
    <label>Region</label>
    
        <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>ANZ</fullName>
            </value>
            <value>
                <fullName>BFS</fullName>
            </value>
            <value>
                <fullName>Canada</fullName>
            </value>
            <value>
                <fullName>Greater China</fullName>
            </value>
            <value>
                <fullName>GOV</fullName>
            </value>
            <value>
                <fullName>India</fullName>
            </value>
            <value>
                <fullName>Korea</fullName>
            </value>
            <value>
                <fullName>LATAM</fullName>
            </value>
            <value>
                <fullName>MEA</fullName>
            </value>
            <value>
                <fullName>Nordics</fullName>
            </value>
            <value>
                <fullName>NorthCentral</fullName>
            </value>
            <value>
                <fullName>NorthEast</fullName>
            </value>
            <value>
                <fullName>NorthWest</fullName>
            </value>
            <value>
                <fullName>Others</fullName>
            </value>
            <value>
                <fullName>SEA</fullName>
            </value>
            <value>
                <fullName>SouthWest</fullName>
            </value>
            <value>
                <fullName>SouthCentral</fullName>
            </value>
            <value>
                <fullName>SouthEast</fullName>
            </value>
            <value>
                <fullName>UKI</fullName>
            </value>
            <value>
                <fullName>CE</fullName>
            </value>
            <value>
                <fullName>EECIS</fullName>
            </value>
            <value>
                <fullName>France</fullName>
            </value>
            <value>
                <fullName>Italy/Greece</fullName>
            </value>
            <value>
                <fullName>Iberia</fullName>
            </value>
            <value>
                <fullName>Benelux</fullName>
            </value>
            <value>
                <fullName>Japan</fullName>
            </value>
            <value>
                <fullName>Hokkaido</fullName>
            </value>
            <value>
                <fullName>Tohoku</fullName>
            </value>
            <value>
                <fullName>Kanto</fullName>
            </value>
            <value>
                <fullName>Chubu</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

uipath-commons/main/default/objects/Account/fields/Vertical__c.field-meta.xml
<CustomField>
    <fullName>Vertical__c</fullName>
    <formula>CASE( Industry , &quot;Engineering&quot;, &quot;Manufacturing&quot;, 
&quot;Construction&quot;, &quot;Manufacturing&quot;,
&quot;Manufacturing&quot;, &quot;Manufacturing&quot;,
&quot;Automotive&quot;, &quot;Manufacturing&quot;,
&quot;Technology&quot;, &quot;High Tech&quot;,
&quot;Machinery&quot;, &quot;Manufacturing&quot;,
&quot;Civil Engineering&quot;, &quot;Manufacturing&quot;,
&quot;Financial Services&quot;, &quot;Banking and Financial Services&quot;,
&quot;Banking and Financial Services&quot;, &quot;Banking and Financial Services&quot;,
&quot;Chemicals&quot;, &quot;Manufacturing&quot;,
&quot;Automotive&quot;, &quot;Manufacturing&quot;,
&quot;Retail&quot;, &quot;Retail&quot;,
&quot;Biotechnology&quot;, &quot;Healthcare&quot;,
&quot;Building Materials&quot;, &quot;Manufacturing&quot;,
&quot;Pharmaceuticals&quot;, &quot;Healthcare&quot;,
&quot;Entertainment&quot;, &quot;Media &amp; Entertainment&quot;,
&quot;Others&quot;, &quot;Others&quot;,
&quot;Hospitality&quot;, &quot;Hospitality&quot;,
&quot;Media&quot;, &quot;Media &amp; Entertainment&quot;,
&quot;Not For Profit&quot;, &quot;Others&quot;,
&quot;Legal&quot;, &quot;Others&quot;,
&quot;Recreation&quot;, &quot;Others&quot;,
&quot;Staffing &amp; Recruiting services&quot;, &quot;Others&quot;,
&quot;Consulting&quot;, &quot;Partnership&quot;,
&quot;Computer Software&quot;, &quot;High Tech&quot;,
&quot;Management Consulting&quot;, &quot;Partnership&quot;,
&quot;Information Technology and Services&quot;, &quot;High Tech&quot;,
&quot;Education&quot;, &quot;Public Sector&quot;,
&quot;Government&quot;, &quot;Public Sector&quot;,
&quot;Public Sector&quot;, &quot;Public Sector&quot;,
&quot;Higher Education&quot;, &quot;Public Sector&quot;,
&quot;Insurance&quot;, &quot;Insurance&quot;,
&quot;Energy&quot;, &quot;Energy and Utilities&quot;,
&quot;Oil &amp; Energy&quot;, &quot;Energy and Utilities&quot;,
&quot;Utilities&quot;, &quot;Energy and Utilities&quot;,
&quot;Transportation&quot;, &quot;Transportation&quot;,
&quot;Telecommunications&quot;, &quot;Telecommunications&quot;,
&quot;Communications&quot;, &quot;Telecommunications&quot;,
&quot;Banking&quot;, &quot;Banking and Financial Services&quot;,
&quot;Healthcare&quot;, &quot;Healthcare&quot;,
&quot;Healthcare Payers&quot;, &quot;Healthcare&quot;,
&quot;Healthcare Providers&quot;, &quot;Healthcare&quot;,
&quot;Healthcare LS&quot;, &quot;Healthcare&quot;,
&quot;Healthcare Gov&quot;, &quot;Healthcare&quot;,
&quot;Household chemicals&quot;, &quot;CPG&quot;,
&quot;Consumer Goods&quot;, &quot;CPG&quot;,
&quot;Food &amp; Beverage&quot;, &quot;CPG&quot;,
&quot;Electronics,&quot;, &quot;CPG&quot;,
&quot;Apparel,&quot;, &quot;CPG&quot;,
&quot;Others&quot;)</formula>
    <label>Vertical</label>
    <type>Text</type>
</CustomField>

uipath-commons/main/default/objects/Licensing_Environment__mdt/Licensing_Environment__mdt.object-meta.xml
<CustomObject>
    <label>Licensing Environment</label>
    <pluralLabel>Licensing Environments</pluralLabel>
</CustomObject>

uipath-commons/main/default/objects/Licensing_Environment__mdt/fields/Licensing_Server_Callout__c.field-meta.xml
<CustomField>
    <fullName>Licensing_Server_Callout__c</fullName>
    <label>Licensing Server Callout</label>
    <length>40</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

uipath-commons/main/default/classes/LicensingApiDispatch.cls
/**
 * TODO refactor code in next iteration
 */
public with sharing class LicensingApiDispatch {
  public static void onAccountUpdate(string accountId) {
    for (Licensing_Environment__mdt env : getEnvironments()) {
      LicensingApi.onAccountUpdate(env.Licensing_Server_Callout__c, accountId);
    }
  }

  public static void onAccountsMerged(string masterAccountId, List<string> mergedAccountIds) {
    for (Licensing_Environment__mdt env : getEnvironments()) {
      LicensingApi.onAccountsMerged(env.Licensing_Server_Callout__c, masterAccountId, mergedAccountIds);
    }
  }

  private static Organization orgInfo {
    get {
      if (orgInfo == null) {
        orgInfo = [SELECT IsSandbox FROM Organization LIMIT 1];
      }
      return orgInfo;
    }
    set;
  }

  private static Licensing_Environment__mdt[] getEnvironments() {
    //test setting
    if (Test.isRunningTest()) {
      return new List<Licensing_Environment__mdt>{
        new Licensing_Environment__mdt(Licensing_Server_Callout__c = 'test', Enabled__c = true)
      };
    }

    //production setting
    if (orgInfo.IsSandbox == false) {
      return [
        SELECT Licensing_Server_Callout__c, Enabled__c
        FROM Licensing_Environment__mdt
        WHERE Enabled__c = true AND DeveloperName = 'Production'
      ];
    }

    //sandbox setting
    return [
      SELECT Licensing_Server_Callout__c, Enabled__c
      FROM Licensing_Environment__mdt
      WHERE Enabled__c = true AND DeveloperName = 'Sandbox'
    ];
  }

  /**
   * TODO refactor code into Queueable
   * Sync data using licensing Api
   */
  public static void licensingApiSyncAccountOnDelete(List<Account> records) {
    Map<String, List<String>> masterRecordIdAccMap = new Map<String, List<String>>();
    for (Account acc : (List<Account>) records) {
      if (acc.MasterRecordId != null) {
        if (!masterRecordIdAccMap.containsKey(acc.MasterRecordId)) {
          masterRecordIdAccMap.put(acc.MasterRecordId, new List<String>());
        }
        masterRecordIdAccMap.get(acc.MasterRecordId).add(acc.Account_ID_Long__c);
      }
    }
    for (String masterRecordId : masterRecordIdAccMap.keySet()) {
      if ((Limits.getLimitFutureCalls() - Limits.getFutureCalls()) > 0) {
        LicensingApiDispatch.onAccountsMerged(masterRecordId, masterRecordIdAccMap.get(masterRecordId));
      }
    }
  }

  /**
   * TODO refactor code into Queueable
   * Sync data using licensing Api
   */
  public static void licensingApiSyncAccountOnUpdate(List<Account> records, Map<Id, SObject> oldMap) {
    for (Account acc : records) {
      Account oldAcc = (Account) oldMap.get(acc.Id);
      if (
        acc.Account_ID_Long__c != oldAcc.Account_ID_Long__c ||
        acc.Name != oldAcc.Name ||
        acc.ParentId != oldAcc.ParentId ||
        acc.Type != oldAcc.Type ||
        acc.Industry != oldAcc.Industry ||
        acc.BillingCountryCode != oldAcc.BillingCountryCode ||
        acc.Geo__c != oldAcc.Geo__c ||
        acc.Area__c != oldAcc.Area__c ||
        acc.Region__c != oldAcc.Region__c ||
        acc.Vertical__c != oldAcc.Vertical__c ||
        acc.recordTypeId != oldAcc.recordTypeId
      ) {
        if ((Limits.getLimitFutureCalls() - Limits.getFutureCalls()) > 0) {
          LicensingApiDispatch.onAccountUpdate(acc.Account_ID_Long__c);
        }
      }
    }
  }
}