uipath-commons/main/default/objects/Account/fields/AI_Early_Access_Program__c.field-meta.xml
<CustomField>
        <fullName>AI_Early_Access_Program__c</fullName>
        <label>AI Early Access Program</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>AI Fabric</fullName>
                </value>
                <value>
                    <fullName>AI Document Understanding</fullName>
                </value>
                <value>
                    <fullName>AI Process Understanding</fullName>
                </value>
                <value>
                    <fullName>AI Visual Understanding</fullName>
                </value>
                <value>
                    <fullName>AI Conversational Understanding</fullName>
                </value>
                <value>
                    <fullName>AI Analytics</fullName>
                </value>
                <value>
                    <fullName>Human-in-the-Loop</fullName>
                </value>
                <value>
                    <fullName>Cloud Orchestrator</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </CustomField>

uipath-sales/main/default/objects/AI_Early_Access_Program__c/AI_Early_Access_Program__c.object-meta.xml
<CustomObject>    
    <label>Early Access &amp; Adoption Program</label>
    <nameField>
        <displayFormat>EAAP-{0000}</displayFormat>
        <label>Program Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Early Access &amp; Adoption Programs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

uipath-sales/main/default/objects/Case/fields/AI_Early_Access_Program__c.field-meta.xml
<CustomField>
    <fullName>AI_Early_Access_Program__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>AI Early Access Program</label>
    <referenceTo>AI_Early_Access_Program__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>AI_Early_Access_Program</relationshipName>
    <type>Lookup</type>
</CustomField>

uipath-sales/main/default/objects/Case/fields/Conga_Template_2__c.field-meta.xml
<CustomField>
    <fullName>Conga_Template_2__c</fullName>
    <description>This field determines the template for the generating a document based on Document Type.</description>
    <inlineHelpText>This field determines the template for the generating a document based on Document Type.</inlineHelpText>
    <label>Conga Template</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

uipath-sales/main/default/objects/Case/fields/Document_Language__c.field-meta.xml
<CustomField>
    <fullName>Document_Language__c</fullName>
    <label>Document Language</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Document_Type__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>English</fullName>
            </value>
            <value>
                <fullName>日本語</fullName>
            </value>
            <value>
                <fullName>French</fullName>
            </value>
            <value>
                <fullName>Russian</fullName>
            </value>
            <value>
                <fullName>Polish</fullName>
            </value>
            <value>
                <fullName>Spanish</fullName>
            </value>
            <value>
                <fullName>Portuguese</fullName>
            </value>
            <value>
                <fullName>Chinese</fullName>
            </value>
            <value>
                <fullName>German</fullName>
                <isActive>false</isActive>
                <label>German</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

uipath-sales/main/default/objects/Case/fields/Document_Type__c.field-meta.xml
<CustomField>
    <fullName>Document_Type__c</fullName>
    <label>Document Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Academic Alliance Agreement</fullName>
            </value>
            <value>
                <fullName>Affiliate Adoption Agreement</fullName>
            </value>
            <value>
                <fullName>BAA</fullName>
            </value>
            <value>
                <fullName>DPA</fullName>
            </value>
            <value>
                <fullName>End Customer General Terms</fullName>
            </value>
            <value>
                <fullName>EULA Addendum</fullName>
            </value>
            <value>
                <fullName>Invoice</fullName>
            </value>
            <value>
                <fullName>Legal Inquiry</fullName>
            </value>
            <value>
                <fullName>MPA Addendum</fullName>
            </value>
            <value>
                <fullName>MPA Indirect Resale + BPO Agreement (CN)</fullName>
            </value>
            <value>
                <fullName>MPA Indirect Resale Only Agreement (CN)</fullName>
            </value>
            <value>
                <fullName>MSSA</fullName>
            </value>
            <value>
                <fullName>NDA</fullName>
            </value>
            <value>
                <fullName>NDA EAP</fullName>
            </value>
            <value>
                <fullName>Partner BPO Only Agreement</fullName>
            </value>
            <value>
                <fullName>Partner Resale + BPO Agreement</fullName>
            </value>
            <value>
                <fullName>Partner Resale Only Agreement</fullName>
            </value>
            <value>
                <fullName>Software License Broker</fullName>
            </value>
            <value>
                <fullName>Teaming Agreement</fullName>
            </value>
            <value>
                <fullName>Technology Alliance Agreement</fullName>
            </value>
            <value>
                <fullName>Trial Terms</fullName>
            </value>
            <value>
                <fullName>Undertaking by Original Software Developer (for Software) pre Signed</fullName>
            </value>
            <value>
                <fullName>USN Addendum</fullName>
            </value>
            <value>
                <fullName>Contract assignment to UiPath affiliate</fullName>
            </value>
            <value>
                <fullName>Termination</fullName>
            </value>
            <value>
                <fullName>Reverse Reseller</fullName>
            </value>
            <value>
                <fullName>Technology Alliance Agreement Addendum</fullName>
            </value>
            <value>
                <fullName>Technology Alliance Deal Referral Addendum</fullName>
            </value>
            <value>
                <fullName>License Compliance Notice</fullName>
            </value>
            <value>
                <fullName>Partner Confirmation Letter</fullName>
            </value>
            <value>
                <fullName>EAAP Agreement</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

uipath-sales/main/default/objects/Case/fields/Standard_Template__c.field-meta.xml
<CustomField>
    <fullName>Standard_Template__c</fullName>
    <inlineHelpText>Yes - Non-editable document will be generated (Contractual clauses cannot be amended; Products can be modified)
No - Editable document will be generated (Products and contractual clauses can be modified).</inlineHelpText>
    <label>Agreement Template</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
                <label>UiPath Template Non-Editable (Standard)</label>
            </value>
            <value>
                <fullName>No</fullName>
                <label>UiPath Template Editable</label>
            </value>
            <value>
                <fullName>Customer Template</fullName>
            </value>
            <value>
                <fullName>Partner Template</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

uipath-sales/main/default/classes/SalesCaseDocumentTypeFunction.cls
public with sharing class SalesCaseDocumentTypeFunction implements SObjectToSObjectFunction {
  private Map<Id, String> accountToCountryMap;
  public static final String NON_EDITABLE_STANDARD = 'UiPath Template Non-Editable (Standard)';
  private List<String> EXCLUDED_COUNTRIES = new List<String>{
    'Russian Federation',
    'Armenia',
    'Belarus',
    'Kasakhstan',
    'Kyrgyzstan',
    'Turkmenistan',
    'Uzbekistan',
    'Ukraine',
    'Georgia',
    'Azerbaijan'
  };

  public SalesCaseDocumentTypeFunction(List<Case> cases) {
    Set<Id> accountIds = new Set<Id>(Collection.of(cases).pluckIds());
    accountToCountryMap = new Map<Id, String>();
    for (Account account : [SELECT Id, BillingCountry FROM Account WHERE Id IN :accountIds]) {
      accountToCountryMap.put(account.Id, account.BillingCountry);
    }
  }

  public SObject apply(Case record) {
    Boolean assignTemplate = false;
    if (record.Document_Type__c.startsWith('EAAP Agreement')) {
      if (record.AI_Early_Access_Program__c != null) {
        assignTemplate = true;
      }
    } else if (record.Document_Type__c == 'USN Addendum') {
      if (
        record.Standard_Template__c == SalesCaseMetadata.NON_EDITABLE_STANDARD &&
        !EXCLUDED_COUNTRIES.contains(accountToCountryMap.get(record.AccountId))
      ) {
        assignTemplate = true;
      }
    } else if (record.Document_Type__c == 'Undertaking by Original Software Developer (for Software) pre Signed') {
      if (record.Standard_Template__c == SalesCaseMetadata.NON_EDITABLE_STANDARD) {
        assignTemplate = true;
      }
    } else {
      assignTemplate = true;
    }
    if (assignTemplate) {
      record.Conga_Template_2__c = SalesCaseMetadata.DocumentTypeMapping.get(record.Document_Type__c);
    }

    return record;
  }

  public SObject apply(SObject record) {
    return apply((Case) record);
  }

  public static void deriveTemplateId(List<Case> records) {
    Collection.of(records)
      .filter(
        Match.field(Case.Document_Type__c)
          .isIn(SalesCaseMetadata.DocumentTypeMapping.keySet())
          .also(Case.Document_Type__c)
          .hasValue()
      )
      .mapAll(new SalesCaseDocumentTypeFunction(records));
  }

  public static void deriveTemplateId(List<SObject> records, Map<Id, SObject> existingRecords) {
    HasRecordChanged hasChanged = new HasRecordChanged(
      new Set<SObjectField>{ Case.Document_Type__c, Case.Document_Language__c },
      records,
      existingRecords
    );

    Collection.of(records)
      .filter(hasChanged)
      .filter(
        Match.field(Case.Document_Type__c)
          .isIn(SalesCaseMetadata.DocumentTypeMapping.keySet())
          .also(Case.Document_Type__c)
          .hasValue()
      )
      .mapAll(new SalesCaseDocumentTypeFunction(records));
  }
}