uipath-commons/main/default/objects/Account/fields/Allbound_Status__c.field-meta.xml
<CustomField>
    <fullName>Allbound_Status__c</fullName>
    <label>Allbound Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

uipath-commons/main/default/objects/Account/fields/Sync_Status__c.field-meta.xml
<CustomField>
    <fullName>Sync_Status__c</fullName>
    <description>Indicated the status of the product against integration</description>
    <inlineHelpText>Not Valid - default sync status for new records
Valid - Ready to be synced to NetSuite
Pending - Updates on record ready to be synced to NetSuite
Synced - Synced to NetSuite
Error - Error while syncing
Do Not Sync - Archive from syncing</inlineHelpText>
    <label>Sync Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Sync_Status</valueSetName>
    </valueSet>
</CustomField>

uipath-commons/main/default/objects/Account/fields/Technology_Partner_Level__c.field-meta.xml
<CustomField>
        <fullName>Technology_Partner_Level__c</fullName>
        <label>Technology Partner Level</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Prospect</fullName>
                </value>
                <value>
                    <fullName>Registered</fullName>
                </value>
                <value>
                    <fullName>Advanced</fullName>
                </value>
                <value>
                    <fullName>Premier</fullName>
                </value>
                <value>
                    <fullName>OEM</fullName>
                </value>
                <value>
                    <fullName>Resell</fullName>
                </value>
                <value>
                    <fullName>Strategic</fullName>
                </value>
                <value>
                    <fullName>Start-up</fullName>
                </value>
                <value>
                    <fullName>No Action</fullName>
                </value>
                <value>
                    <fullName>Expired</fullName>
                </value>
                <value>
                    <fullName>Strategic - Outside of TAP</fullName>
                </value>
                <value>
                    <fullName>Non-Strategic - Outside of TAP</fullName>
                </value>
                <value>
                    <fullName>Outside of TAP</fullName>
                </value>
                <value>
                    <fullName>Terminated</fullName>
                </value>
                <value>
                    <fullName>Referral</fullName>
                </value>
                <value>
                    <fullName>OEM/Resell</fullName>
                </value>
                <value>
                    <fullName>Certified</fullName>
                    <isActive>false</isActive>
                    <label>Certified</label>
                </value>
                <value>
                    <fullName>Premium</fullName>
                    <isActive>false</isActive>
                    <label>Premium</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </CustomField>

uipath-commons/main/default/objects/Account/fields/Technology_Partnership_Deny_Date__c.field-meta.xml
<CustomField>
        <fullName>Technology_Partnership_Deny_Date__c</fullName>
        <label>Technology Partnership Deny Date</label>
        <type>Date</type>
    </CustomField>

uipath-commons/main/default/objects/Account/fields/Technology_Partnership_signed_Date__c.field-meta.xml
<CustomField>
        <fullName>Technology_Partnership_signed_Date__c</fullName>
        <label>Technology Partnership signed Date</label>
        <type>Date</type>
    </CustomField>

uipath-commons/main/default/objects/Account/fields/Validation_Status__c.field-meta.xml
<CustomField>
    <fullName>Validation_Status__c</fullName>
    <description>Used by the Data Stewards to flag the Account validation status</description>
    <inlineHelpText>When Data Stewards set the status to &quot;Validated&quot; call to boomi integration will be made</inlineHelpText>
    <label>Validation Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Data_Steward_Validation_Status</valueSetName>
    </valueSet>
</CustomField>

uipath-commons/main/default/objects/Account/recordTypes/Partner.recordType-meta.xml
<RecordType>
    <fullName>Partner</fullName>
    <active>true</active>
    <description>UiPath prospective or existing Partner Account</description>
    <label>Partner</label>
</RecordType>

uipath-sales/main/default/objects/Case/fields/Document_Type__c.field-meta.xml
<CustomField>
    <fullName>Document_Type__c</fullName>
    <label>Document Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Academic Alliance Agreement</fullName>
            </value>
            <value>
                <fullName>Affiliate Adoption Agreement</fullName>
            </value>
            <value>
                <fullName>BAA</fullName>
            </value>
            <value>
                <fullName>DPA</fullName>
            </value>
            <value>
                <fullName>End Customer General Terms</fullName>
            </value>
            <value>
                <fullName>EULA Addendum</fullName>
            </value>
            <value>
                <fullName>Invoice</fullName>
            </value>
            <value>
                <fullName>Legal Inquiry</fullName>
            </value>
            <value>
                <fullName>MPA Addendum</fullName>
            </value>
            <value>
                <fullName>MPA Indirect Resale + BPO Agreement (CN)</fullName>
            </value>
            <value>
                <fullName>MPA Indirect Resale Only Agreement (CN)</fullName>
            </value>
            <value>
                <fullName>MSSA</fullName>
            </value>
            <value>
                <fullName>NDA</fullName>
            </value>
            <value>
                <fullName>NDA EAP</fullName>
            </value>
            <value>
                <fullName>Partner BPO Only Agreement</fullName>
            </value>
            <value>
                <fullName>Partner Resale + BPO Agreement</fullName>
            </value>
            <value>
                <fullName>Partner Resale Only Agreement</fullName>
            </value>
            <value>
                <fullName>Software License Broker</fullName>
            </value>
            <value>
                <fullName>Teaming Agreement</fullName>
            </value>
            <value>
                <fullName>Technology Alliance Agreement</fullName>
            </value>
            <value>
                <fullName>Trial Terms</fullName>
            </value>
            <value>
                <fullName>Undertaking by Original Software Developer (for Software) pre Signed</fullName>
            </value>
            <value>
                <fullName>USN Addendum</fullName>
            </value>
            <value>
                <fullName>Contract assignment to UiPath affiliate</fullName>
            </value>
            <value>
                <fullName>Termination</fullName>
            </value>
            <value>
                <fullName>Reverse Reseller</fullName>
            </value>
            <value>
                <fullName>Technology Alliance Agreement Addendum</fullName>
            </value>
            <value>
                <fullName>Technology Alliance Deal Referral Addendum</fullName>
            </value>
            <value>
                <fullName>License Compliance Notice</fullName>
            </value>
            <value>
                <fullName>Partner Confirmation Letter</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

uipath-commons/main/default/globalValueSets/Data_Steward_Validation_Status.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>In Review</fullName>
    </customValue>
    <customValue>
        <fullName>Pending</fullName>
        <default>true</default>
        <label>Pending</label>
    </customValue>
    <customValue>
        <fullName>Ready For Review</fullName>
    </customValue>
    <customValue>
        <fullName>Review Complete</fullName>
    </customValue>
    <customValue>
        <fullName>Validated</fullName>
    </customValue>
    <description>Validation Status values to be used by the Data Stewards on Accounts, Addresses etc</description>
    <masterLabel>Data Steward Validation Status</masterLabel>
</GlobalValueSet>

uipath-commons/main/default/globalValueSets/Sync_Status.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Do Not Sync</fullName>
    </customValue>
    <customValue>
        <fullName>Error</fullName>
    </customValue>
    <customValue>
        <fullName>Not Valid</fullName>
        <default>true</default>
        <label>Not Valid</label>
    </customValue>
    <customValue>
        <fullName>Pending</fullName>
    </customValue>
    <customValue>
        <fullName>Synced</fullName>
    </customValue>
    <customValue>
        <fullName>Valid</fullName>
    </customValue>
    <description>Sync Status used to maintain various integration status</description>
    <masterLabel>Sync Status</masterLabel>
</GlobalValueSet>

uipath-sales/main/default/classes/CaseTechPartnerAgreementQueueableTest.cls
@isTest
public class CaseTechPartnerAgreementQueueableTest {
  @isTest
  private static void whenSigned_updateTechnologyPartnershipSignedDate() {
    Id caseId = fflib_IDGenerator.generate(Case.SObjectType);
    Id legalProductRequestRecordTypeId = SalesCaseMetadata.LegalProductRequestRecordType;

    Account accountRecord = new Account(
      Name = 'New Account',
      BillingCountry = 'United Kingdom',
      Industry = 'Others',
      Validation_Status__c = 'Validated',
      Sync_Status__c = 'Synced'
    );
    insert accountRecord;

    Case oldCase = new Case(
      Subject = 'Test',
      AccountId = accountRecord.Id,
      RecordTypeId = legalProductRequestRecordTypeId,
      Status = 'New'
    );

    Case updatedCase = new Case(
      Id = caseId,
      Subject = 'Test',
      AccountId = accountRecord.Id,
      RecordTypeId = legalProductRequestRecordTypeId,
      Status = SalesCaseMetadata.SIGNED,
      Document_Type__c = SalesCaseMetadata.TECHNOLOGY_ALLIANCE_AGREEMENT
    );
    new CaseTechPartnerAgreementQueueable(new List<Case>{ updatedCase }).work();
    accountRecord = [
      SELECT
        Id,
        Allbound_Status__c,
        Technology_Partner_Level__c,
        Technology_Partnership_signed_Date__c,
        Technology_Partnership_Deny_Date__c
      FROM Account
      WHERE Id = :accountRecord.Id
    ];
    System.assertEquals('Active', accountRecord.Allbound_Status__c, 'All Bound Status is not Active');
    System.assertEquals(
      'Registered',
      accountRecord.Technology_Partner_Level__c,
      'Technology Partner level is not Registered'
    );
    System.assertNotEquals(
      null,
      accountRecord.Technology_Partnership_signed_Date__c,
      'Technology Partnership signed date is null'
    );
    System.assertEquals(
      null,
      accountRecord.Technology_Partnership_Deny_Date__c,
      'Technology Partnership Deny date is not null'
    );
  }

  @isTest
  private static void whenNotSigned_updateTechnologyPartnershipDenyDate() {
    Id caseId = fflib_IDGenerator.generate(Case.SObjectType);
    Id legalProductRequestRecordTypeId = SalesCaseMetadata.LegalProductRequestRecordType;

    Account accountRecord = new Account(
      Name = 'New Account',
      BillingCountry = 'United Kingdom',
      Industry = 'Others',
      Validation_Status__c = 'Validated',
      Sync_Status__c = 'Synced'
    );
    insert accountRecord;

    Case oldCase = new Case(
      Subject = 'Test',
      AccountId = accountRecord.Id,
      RecordTypeId = legalProductRequestRecordTypeId,
      Status = 'New'
    );

    Case updatedCase = new Case(
      Id = caseId,
      Subject = 'Test',
      AccountId = accountRecord.Id,
      RecordTypeId = legalProductRequestRecordTypeId,
      Status = SalesCaseMetadata.NOT_SIGNED,
      Document_Type__c = SalesCaseMetadata.TECHNOLOGY_ALLIANCE_AGREEMENT
    );
    new CaseTechPartnerAgreementQueueable(new List<Case>{ updatedCase }).work();
    accountRecord = [
      SELECT
        Id,
        Allbound_Status__c,
        Technology_Partner_Level__c,
        Technology_Partnership_signed_Date__c,
        Technology_Partnership_Deny_Date__c
      FROM Account
      WHERE Id = :accountRecord.Id
    ];
    System.assertEquals(null, accountRecord.Allbound_Status__c, 'All Bound Status is not null');
    System.assertEquals(null, accountRecord.Technology_Partner_Level__c, 'Technology Partner level is not null');
    System.assertEquals(
      null,
      accountRecord.Technology_Partnership_signed_Date__c,
      'Technology Partnership signed date is null'
    );
    System.assertNotEquals(
      null,
      accountRecord.Technology_Partnership_Deny_Date__c,
      'Technology Partnership Deny date is null'
    );
  }
}