uipath-commons/main/default/objects/Account/fields/Allbound_Status__c.field-meta.xml
<CustomField>
    <fullName>Allbound_Status__c</fullName>
    <label>Allbound Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

uipath-commons/main/default/objects/Account/fields/Technology_Partner_Level__c.field-meta.xml
<CustomField>
        <fullName>Technology_Partner_Level__c</fullName>
        <label>Technology Partner Level</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Prospect</fullName>
                </value>
                <value>
                    <fullName>Registered</fullName>
                </value>
                <value>
                    <fullName>Advanced</fullName>
                </value>
                <value>
                    <fullName>Premier</fullName>
                </value>
                <value>
                    <fullName>OEM</fullName>
                </value>
                <value>
                    <fullName>Resell</fullName>
                </value>
                <value>
                    <fullName>Strategic</fullName>
                </value>
                <value>
                    <fullName>Start-up</fullName>
                </value>
                <value>
                    <fullName>No Action</fullName>
                </value>
                <value>
                    <fullName>Expired</fullName>
                </value>
                <value>
                    <fullName>Strategic - Outside of TAP</fullName>
                </value>
                <value>
                    <fullName>Non-Strategic - Outside of TAP</fullName>
                </value>
                <value>
                    <fullName>Outside of TAP</fullName>
                </value>
                <value>
                    <fullName>Terminated</fullName>
                </value>
                <value>
                    <fullName>Referral</fullName>
                </value>
                <value>
                    <fullName>OEM/Resell</fullName>
                </value>
                <value>
                    <fullName>Certified</fullName>
                    <isActive>false</isActive>
                    <label>Certified</label>
                </value>
                <value>
                    <fullName>Premium</fullName>
                    <isActive>false</isActive>
                    <label>Premium</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </CustomField>

uipath-commons/main/default/objects/Account/fields/Technology_Partnership_Deny_Date__c.field-meta.xml
<CustomField>
        <fullName>Technology_Partnership_Deny_Date__c</fullName>
        <label>Technology Partnership Deny Date</label>
        <type>Date</type>
    </CustomField>

uipath-commons/main/default/objects/Account/fields/Technology_Partnership_signed_Date__c.field-meta.xml
<CustomField>
        <fullName>Technology_Partnership_signed_Date__c</fullName>
        <label>Technology Partnership signed Date</label>
        <type>Date</type>
    </CustomField>

uipath-sales/main/default/objects/Case/fields/Document_Type__c.field-meta.xml
<CustomField>
    <fullName>Document_Type__c</fullName>
    <label>Document Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Academic Alliance Agreement</fullName>
            </value>
            <value>
                <fullName>Affiliate Adoption Agreement</fullName>
            </value>
            <value>
                <fullName>BAA</fullName>
            </value>
            <value>
                <fullName>DPA</fullName>
            </value>
            <value>
                <fullName>End Customer General Terms</fullName>
            </value>
            <value>
                <fullName>EULA Addendum</fullName>
            </value>
            <value>
                <fullName>Invoice</fullName>
            </value>
            <value>
                <fullName>Legal Inquiry</fullName>
            </value>
            <value>
                <fullName>MPA Addendum</fullName>
            </value>
            <value>
                <fullName>MPA Indirect Resale + BPO Agreement (CN)</fullName>
            </value>
            <value>
                <fullName>MPA Indirect Resale Only Agreement (CN)</fullName>
            </value>
            <value>
                <fullName>MSSA</fullName>
            </value>
            <value>
                <fullName>NDA</fullName>
            </value>
            <value>
                <fullName>NDA EAP</fullName>
            </value>
            <value>
                <fullName>Partner BPO Only Agreement</fullName>
            </value>
            <value>
                <fullName>Partner Resale + BPO Agreement</fullName>
            </value>
            <value>
                <fullName>Partner Resale Only Agreement</fullName>
            </value>
            <value>
                <fullName>Software License Broker</fullName>
            </value>
            <value>
                <fullName>Teaming Agreement</fullName>
            </value>
            <value>
                <fullName>Technology Alliance Agreement</fullName>
            </value>
            <value>
                <fullName>Trial Terms</fullName>
            </value>
            <value>
                <fullName>Undertaking by Original Software Developer (for Software) pre Signed</fullName>
            </value>
            <value>
                <fullName>USN Addendum</fullName>
            </value>
            <value>
                <fullName>Contract assignment to UiPath affiliate</fullName>
            </value>
            <value>
                <fullName>Termination</fullName>
            </value>
            <value>
                <fullName>Reverse Reseller</fullName>
            </value>
            <value>
                <fullName>Technology Alliance Agreement Addendum</fullName>
            </value>
            <value>
                <fullName>Technology Alliance Deal Referral Addendum</fullName>
            </value>
            <value>
                <fullName>License Compliance Notice</fullName>
            </value>
            <value>
                <fullName>Partner Confirmation Letter</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

uipath-sales/main/default/classes/SalesCaseTechPartnerAgreementQueueable.cls
/**
 * TODO REWRITE
 * Move to Service Layer
 * this code was just moved here from the sync Trigger context into a Queueable Context.
 * Needs to be rewritten entirely
 * Updates Account on Signed/Declined Legal Document
 */
public with sharing class SalesCaseTechPartnerAgreementQueueable extends AbstractQueueable {
  private final List<SObject> cases;

  public SalesCaseTechPartnerAgreementQueueable(List<SObject> cases) {
    super('SalesCaseTechPartnerAgreementQueueable');
    this.cases = cases;
  }

  public override void work() {
    this.updateAccounts(this.cases);
  }

  private void updateAccounts(List<Case> cases) {
    List<Account> accountsToUpdate = new List<Account>();
    for (Case caseRecord : cases) {
      Account accountRecord = new Account(Id = caseRecord.AccountId);
      if (caseRecord.Status == SalesCaseMetadata.SIGNED) {
        accountRecord.Allbound_Status__c = 'Active';
        accountRecord.Technology_Partner_Level__c = 'Registered';
        accountRecord.Technology_Partnership_signed_Date__c = System.today();
      } else {
        accountRecord.Technology_Partnership_Deny_Date__c = System.today();
      }
      accountsToUpdate.add(accountRecord);
    }

    if (!accountsToUpdate.isEmpty()) {
      update accountsToUpdate;
    }
  }

  public static void deriveTechPartnershipDateOnAccount(List<Case> cases, Map<Id, SObject> existingCases) {
    SObjectPredicate hasChanged = new HasRecordChanged(
      new Set<SObjectField>{ Case.Document_Type__c, Case.Status, Case.RecordTypeId },
      cases,
      existingCases
    );

    List<Case> eligibleCases = (List<Case>) Collection.of(cases)
      .filter(hasChanged)
      .filter(
        Match.field(Case.RecordTypeId)
          .isIn(new Set<String>{ SalesCaseMetadata.LegalProductRequestRecordType })
          .also(Case.Document_Type__c)
          .equals(SalesCaseMetadata.TECHNOLOGY_ALLIANCE_AGREEMENT)
      )
      .filter(
        Match.field(Case.Status)
          .isIn(new Set<String>{ SalesCaseMetadata.SIGNED, SalesCaseMetadata.NOT_SIGNED })
          .also(Case.AccountId)
          .hasValue()
      )
      .asList();

    if (!eligibleCases.isEmpty()) {
      AbstractQueueable.enqueue(new SalesCaseTechPartnerAgreementQueueable(eligibleCases));
    }
  }
}