uipath-commons/main/default/objects/Account/fields/Area__c.field-meta.xml
<CustomField>
    <fullName>Area__c</fullName>
    <label>Area</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>MEA</fullName>
            </value>
            <value>
                <fullName>Central Europe</fullName>
            </value>
            <value>
                <fullName>EECIS</fullName>
            </value>
            <value>
                <fullName>Southern Europe</fullName>
            </value>
            <value>
                <fullName>Northern Europe</fullName>
            </value>
            <value>
                <fullName>Western Europe</fullName>
            </value>
            <value>
                <fullName>East</fullName>
            </value>
            <value>
                <fullName>Gov / Fed</fullName>
            </value>
            <value>
                <fullName>Central</fullName>
            </value>
            <value>
                <fullName>West</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

uipath-commons/main/default/objects/Account/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <description>This required field will be used to capture the country on the creation of a new account. It will populate the country on the new address records for accounts. The standard billing and shipping address fields on account will be made read only.</description>
    <label>Country</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Country_Global_List</valueSetName>
    </valueSet>
</CustomField>

uipath-commons/main/default/objects/Account/fields/Geo__c.field-meta.xml
<CustomField>
        <fullName>Geo__c</fullName>
        <label>Geo</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>AMER</fullName>
                </value>
                <value>
                    <fullName>APAC</fullName>
                </value>
                <value>
                    <fullName>EMEA</fullName>
                </value>
                <value>
                    <fullName>Japan</fullName>
                </value>
                <value>
                    <fullName>India</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </CustomField>

uipath-commons/main/default/objects/Account/fields/Ignore_Territory_Assignment__c.field-meta.xml
<CustomField>
        <fullName>Ignore_Territory_Assignment__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Ignore Territory Assignment</label>
        
        <type>Checkbox</type>
    </CustomField>

uipath-commons/main/default/objects/Account/fields/Region__c.field-meta.xml
<CustomField>
    <fullName>Region__c</fullName>
    <label>Region</label>
    
        <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>ANZ</fullName>
            </value>
            <value>
                <fullName>BFS</fullName>
            </value>
            <value>
                <fullName>Canada</fullName>
            </value>
            <value>
                <fullName>Greater China</fullName>
            </value>
            <value>
                <fullName>GOV</fullName>
            </value>
            <value>
                <fullName>India</fullName>
            </value>
            <value>
                <fullName>Korea</fullName>
            </value>
            <value>
                <fullName>LATAM</fullName>
            </value>
            <value>
                <fullName>MEA</fullName>
            </value>
            <value>
                <fullName>Nordics</fullName>
            </value>
            <value>
                <fullName>NorthCentral</fullName>
            </value>
            <value>
                <fullName>NorthEast</fullName>
            </value>
            <value>
                <fullName>NorthWest</fullName>
            </value>
            <value>
                <fullName>Others</fullName>
            </value>
            <value>
                <fullName>SEA</fullName>
            </value>
            <value>
                <fullName>SouthWest</fullName>
            </value>
            <value>
                <fullName>SouthCentral</fullName>
            </value>
            <value>
                <fullName>SouthEast</fullName>
            </value>
            <value>
                <fullName>UKI</fullName>
            </value>
            <value>
                <fullName>CE</fullName>
            </value>
            <value>
                <fullName>EECIS</fullName>
            </value>
            <value>
                <fullName>France</fullName>
            </value>
            <value>
                <fullName>Italy/Greece</fullName>
            </value>
            <value>
                <fullName>Iberia</fullName>
            </value>
            <value>
                <fullName>Benelux</fullName>
            </value>
            <value>
                <fullName>Japan</fullName>
            </value>
            <value>
                <fullName>Hokkaido</fullName>
            </value>
            <value>
                <fullName>Tohoku</fullName>
            </value>
            <value>
                <fullName>Kanto</fullName>
            </value>
            <value>
                <fullName>Chubu</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

uipath-commons/main/default/objects/Account/fields/Territory__c.field-meta.xml
<CustomField>
    <fullName>Territory__c</fullName>
    <label>Territory</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

uipath-commons/main/default/objects/ROW_Country__mdt/ROW_Country__mdt.object-meta.xml
<CustomObject>
    <label>ROW Country</label>
    <pluralLabel>ROW Countries</pluralLabel>
</CustomObject>

uipath-commons/main/default/objects/ROW_Country__mdt/fields/Area__c.field-meta.xml
<CustomField>
        <fullName>Area__c</fullName>
        <label>Area</label>
        <length>80</length>
        <type>Text</type>
    </CustomField>

uipath-commons/main/default/objects/ROW_Country__mdt/fields/Country__c.field-meta.xml
<CustomField>
        <fullName>Country__c</fullName>
        <label>Country</label>
        <length>255</length>
        <type>Text</type>
    </CustomField>

uipath-commons/main/default/objects/ROW_Country__mdt/fields/Country_Code__c.field-meta.xml
<CustomField>
        <fullName>Country_Code__c</fullName>
        <label>Country Code</label>
        <length>5</length>
        <type>Text</type>
    </CustomField>

uipath-commons/main/default/objects/USA_Industry__mdt/USA_Industry__mdt.object-meta.xml
<CustomObject>
    <label>USA Industry</label>
    <pluralLabel>USA Industry</pluralLabel>
</CustomObject>

uipath-commons/main/default/objects/USA_Industry__mdt/fields/Area__c.field-meta.xml
<CustomField>
        <fullName>Area__c</fullName>
        <label>Area</label>
        <length>255</length>
        <type>Text</type>
    </CustomField>

uipath-commons/main/default/objects/USA_Industry__mdt/fields/Industry__c.field-meta.xml
<CustomField>
        <fullName>Industry__c</fullName>
        <label>Industry</label>
        <length>255</length>
        <type>Text</type>
    </CustomField>

uipath-commons/main/default/objects/USA_Industry__mdt/fields/Territory__c.field-meta.xml
<CustomField>
        <fullName>Territory__c</fullName>
        <label>Territory</label>
        <length>80</length>
        <type>Text</type>
    </CustomField>

uipath-commons/main/default/objects/USA_States__mdt/USA_States__mdt.object-meta.xml
<CustomObject>
    <label>USA States</label>
    <pluralLabel>USA States</pluralLabel>
</CustomObject>

uipath-commons/main/default/objects/USA_States__mdt/fields/Billing_State_Code__c.field-meta.xml
<CustomField>
        <fullName>Billing_State_Code__c</fullName>
        <label>Billing State Code</label>
        <length>5</length>
        <type>Text</type>
    </CustomField>

uipath-commons/main/default/objects/USA_States__mdt/fields/Country__c.field-meta.xml
<CustomField>
        <fullName>Country__c</fullName>
        <label>Country</label>
        <length>10</length>
        <type>Text</type>
    </CustomField>

uipath-commons/main/default/objects/USA_States__mdt/fields/Region__c.field-meta.xml
<CustomField>
        <fullName>Region__c</fullName>
        <label>Region</label>
        <length>80</length>
        <type>Text</type>
    </CustomField>

uipath-commons/main/default/objects/UsaZipCodes__mdt/UsaZipCodes__mdt.object-meta.xml
<CustomObject>
    <label>UsaZipCodes</label>
    <pluralLabel>UsaZipCodes</pluralLabel>
</CustomObject>

uipath-commons/main/default/objects/UsaZipCodes__mdt/fields/Postal_Code__c.field-meta.xml
<CustomField>
        <fullName>Postal_Code__c</fullName>
        <label>Postal Code</label>
        <length>10</length>
        <type>Text</type>
    </CustomField>

uipath-commons/main/default/objects/UsaZipCodes__mdt/fields/Region__c.field-meta.xml
<CustomField>
        <fullName>Region__c</fullName>
        <label>Region</label>
        <length>255</length>
        <type>Text</type>
    </CustomField>

uipath-commons/main/default/objects/UsaZipCodes__mdt/fields/Territory__c.field-meta.xml
<CustomField>
        <fullName>Territory__c</fullName>
        <label>Territory</label>
        <length>255</length>
        <type>Text</type>
    </CustomField>

uipath-core/main/default/globalValueSets/Country_Global_List.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Afghanistan</fullName>
    </customValue>
    <customValue>
        <fullName>Aland Islands</fullName>
    </customValue>
    <customValue>
        <fullName>Albania</fullName>
    </customValue>
    <customValue>
        <fullName>Algeria</fullName>
    </customValue>
    <customValue>
        <fullName>Andorra</fullName>
    </customValue>
    <customValue>
        <fullName>Angola</fullName>
    </customValue>
    <customValue>
        <fullName>Anguilla</fullName>
    </customValue>
    <customValue>
        <fullName>Antarctica</fullName>
    </customValue>
    <customValue>
        <fullName>Antigua and Barbuda</fullName>
    </customValue>
    <customValue>
        <fullName>Argentina</fullName>
    </customValue>
    <customValue>
        <fullName>Armenia</fullName>
    </customValue>
    <customValue>
        <fullName>Aruba</fullName>
    </customValue>
    <customValue>
        <fullName>Australia</fullName>
    </customValue>
    <customValue>
        <fullName>Austria</fullName>
    </customValue>
    <customValue>
        <fullName>Azerbaijan</fullName>
    </customValue>
    <customValue>
        <fullName>Bahamas</fullName>
    </customValue>
    <customValue>
        <fullName>Bahrain</fullName>
    </customValue>
    <customValue>
        <fullName>Bangladesh</fullName>
    </customValue>
    <customValue>
        <fullName>Barbados</fullName>
    </customValue>
    <customValue>
        <fullName>Belarus</fullName>
    </customValue>
    <customValue>
        <fullName>Belgium</fullName>
    </customValue>
    <customValue>
        <fullName>Belize</fullName>
    </customValue>
    <customValue>
        <fullName>Benin</fullName>
    </customValue>
    <customValue>
        <fullName>Bermuda</fullName>
    </customValue>
    <customValue>
        <fullName>Bhutan</fullName>
    </customValue>
    <customValue>
        <fullName>Bolivia, Plurinational State of</fullName>
    </customValue>
    <customValue>
        <fullName>Bonaire, Sint Eustatius and Saba</fullName>
    </customValue>
    <customValue>
        <fullName>Bosnia and Herzegovina</fullName>
    </customValue>
    <customValue>
        <fullName>Botswana</fullName>
    </customValue>
    <customValue>
        <fullName>Bouvet Island</fullName>
    </customValue>
    <description>Created for the new Address object and will be used for other objects (involved in integration with NetSuite)</description>
    <masterLabel>Country Global List</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet>

uipath-commons/main/default/classes/AccountTerritoryService.cls
public without sharing class AccountTerritoryService {
    public static void deriveTerritoryFields(List<Account> accounts) {

        SObjectIndex usaIndustriesByName = getUsaIndustriesByName();
        SObjectIndex usaStatesByCodeAndCountry = getUsaStatesByCodeAndCountry();
        SObjectIndex usaZipCodesIndex=getUsaZipCodesIndex(accounts);
        SObjectIndex countriesByCountryCode = getCountriesByCountryCode();

        for (Account acc : accounts) {

            if (!acc.Ignore_Territory_Assignment__c) {
                acc.Geo__c = null;
                acc.Region__c = null;
                acc.Area__c = null;

                USA_Industry__mdt accountIndustry = (USA_Industry__mdt) (usaIndustriesByName.get(
                    acc.Industry
                ));

                if (acc.BillingCountryCode != null) {
                    USA_States__mdt accountState = (USA_States__mdt) usaStatesByCodeAndCountry.get(
                        new USA_States__mdt(
                            Billing_State_Code__c = acc.BillingStateCode,
                            Country__c = acc.BillingCountryCode
                        )
                    );

                    UsaZipCodes__mdt accountZipcode = (UsaZipCodes__mdt) usaZipCodesIndex.get(
                        new UsaZipCodes__mdt(
                            Postal_Code__c = acc.BillingPostalCode
                        )
                    );

                    ROW_Country__mdt accountCountry = (ROW_Country__mdt) countriesByCountryCode.get(
                        new ROW_Country__mdt(
                            Country_Code__c = acc.BillingCountryCode
                        )
                    );

                    if (acc.BillingCountryCode == 'US') {
                        acc.Geo__c = 'AMER';

                        if (accountIndustry != null) {
                            acc.Geo__c = accountIndustry.Region__c;
                            acc.Region__c = accountIndustry.Territory__c;
                            acc.Area__c = accountIndustry.Area__c;
                        } else if (accountState != null) {
                            acc.Geo__c = accountState.Region__c;
                            acc.Region__c = accountState.Territory__c;
                            acc.Area__c = accountState.Area__c;
                        } else if (accountZipcode != null) {
                            acc.Geo__c = accountZipcode.Region__c;
                            acc.Region__c = accountZipcode
                                .Territory__c;
                            acc.Area__c = accountZipcode.Area__c;
                        }
                    } else {
                        if (
                            acc.BillingCountryCode == 'JP' ||
                                acc.BillingCountryCode == 'IN'
                            ) {
                            if (accountState != null) {
                                acc.Geo__c = accountState.Region__c;
                                acc.Region__c = accountState.Territory__c;
                            } else {
                                if (accountCountry!=null) {
                                    acc.Geo__c = accountCountry
                                        .Region__c;
                                    acc.Region__c = accountCountry
                                        .Territory__c;
                                    acc.Area__c = accountCountry
                                        .Area__c;
                                }
                            }
                        } else {
                            if (accountCountry!=null) {
                                acc.Geo__c = accountCountry.Region__c;
                                acc.Region__c = accountCountry
                                    .Territory__c;
                                acc.Area__c = accountCountry.Area__c;
                            }
                        }
                    }
                }
            }
        }
    }

    private static SObjectIndex getCountriesByCountryCode() {
        SObjectIndex countriesByCountryCode = new SObjectIndex(
            new List<String>{
                'Country_Code__c'
            }
        )
            .putAll(AccountMetadata.Countries);
        return countriesByCountryCode;
    }

    private static SObjectIndex getUsaZipCodesIndex(List<Account> accounts) {

        List<String> zipCodes = Collection.of(accounts)
            .pluckStrings(Account.BillingPostalCode);

        List<UsaZipCodes__mdt> usaZipCodes = [
            SELECT Postal_Code__c, Region__c, Area__c, Territory__c
            FROM UsaZipCodes__mdt
            WHERE Postal_Code__c IN :zipCodes
        ];
        SObjectIndex usaZipCodesIndex = new SObjectIndex(
            new List<String>{
                'Postal_Code__c'
            }
        ).putAll(usaZipCodes);
        return usaZipCodesIndex;
    }

    private static SObjectIndex getUsaStatesByCodeAndCountry() {
        SObjectIndex usaStatesByCodeAndCountry = new SObjectIndex(
            new List<String>{
                'Billing_State_Code__c', 'Country__c'
            }
        )
            .putAll(AccountMetadata.States);
        return usaStatesByCodeAndCountry;
    }

    private static SObjectIndex getUsaIndustriesByName() {
        SObjectIndex usaIndustriesByName = new SObjectIndex(
            new List<String>{
                'Industry__c'
            }
        )
            .putAll(AccountMetadata.Industries);
        return usaIndustriesByName;
    }
}