uipath-commons/main/default/objects/Account/fields/Business_Partner_Status__c.field-meta.xml
<CustomField>
    <fullName>Business_Partner_Status__c</fullName>
    <label>Business Partner Status</label>
    
        <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Good Standing</fullName>
            </value>
            <value>
                <fullName>Not in Program</fullName>
            </value>
            <value>
                <fullName>Pending Contract</fullName>
            </value>
            <value>
                <fullName>Pending Termination</fullName>
            </value>
            <value>
                <fullName>Terminated</fullName>
            </value>
            <value>
                <fullName>Not Yet Signed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

uipath-commons/main/default/objects/Account/fields/Classification__c.field-meta.xml
<CustomField>
    <fullName>Classification__c</fullName>
    <label>Classification</label>
    
        <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Others</fullName>
            </value>
            <value>
                <fullName>Diamond</fullName>
            </value>
            <value>
                <fullName>Gold</fullName>
            </value>
            <value>
                <fullName>Silver</fullName>
            </value>
            <value>
                <fullName>Global</fullName>
            </value>
            <value>
                <fullName>Enterprise</fullName>
            </value>
            <value>
                <fullName>Commercial</fullName>
            </value>
            <value>
                <fullName>SMB</fullName>
            </value>
            <value>
                <fullName>Velocity</fullName>
            </value>
            <value>
                <fullName>General Business</fullName>
            </value>
            <value>
                <fullName>Inside Sales</fullName>
            </value>
            <value>
                <fullName>Global - Strategic</fullName>
                <isActive>false</isActive>
                <label>Global - Strategic</label>
            </value>
            <value>
                <fullName>Growth</fullName>
                <isActive>false</isActive>
                <label>Growth</label>
            </value>
            <value>
                <fullName>Key</fullName>
                <isActive>false</isActive>
                <label>Key</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

uipath-commons/main/default/objects/Account/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <description>This required field will be used to capture the country on the creation of a new account. It will populate the country on the new address records for accounts. The standard billing and shipping address fields on account will be made read only.</description>
    <label>Country</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Country_Global_List</valueSetName>
    </valueSet>
</CustomField>

uipath-commons/main/default/objects/Account/fields/Partner_Portal_Contact_Sync__c.field-meta.xml
<CustomField>
    <fullName>Partner_Portal_Contact_Sync__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Partner Portal Contact Sync</label>
    <type>Checkbox</type>
</CustomField>

uipath-commons/main/default/objects/Account/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <description>Used to sync with address object at account creation</description>
    <label>State</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Country__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>States_Global_List</valueSetName>
    </valueSet>
</CustomField>

uipath-commons/main/default/objects/ZinfiConfiguration__c/ZinfiConfiguration__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Store settings for Zinfi Integration</description>
    <label>Zinfi Configuration</label>
</CustomObject>

uipath-commons/main/default/objects/ZinfiConfiguration__c/fields/IsSyncAccount__c.field-meta.xml
<CustomField>
    <fullName>IsSyncAccount__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Enable account sync with Zinfi</description>
    <label>IsSyncAccount</label>
    <type>Checkbox</type>
</CustomField>

uipath-commons/main/default/objects/ZinfiConfiguration__c/fields/WebHook__c.field-meta.xml
<CustomField>
    <fullName>WebHook__c</fullName>
    <description>Zinfi WebHook</description>
    <label>WebHook</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

uipath-commons/main/default/objects/ZinfiConfiguration__c/fields/WebHookContact__c.field-meta.xml
<CustomField>
    <fullName>WebHookContact__c</fullName>
    <description>Zinfi WebHookContact</description>
    <label>WebHookContact</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

uipath-commons/main/default/objects/ZinfiConfiguration__c/fields/WebhookEndPoint__c.field-meta.xml
<CustomField>
    <fullName>WebhookEndPoint__c</fullName>
    <description>Zinfi callout end point</description>
    <label>WebhookEndPoint</label>
    <type>Url</type>
</CustomField>

uipath-commons/main/default/objects/ZinfiConfiguration__c/fields/WebToken__c.field-meta.xml
<CustomField>
    <fullName>WebToken__c</fullName>
    <description>Zinfi WebToken</description>
    <label>WebToken</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

uipath-core/main/default/globalValueSets/Country_Global_List.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Afghanistan</fullName>
    </customValue>
    <customValue>
        <fullName>Aland Islands</fullName>
    </customValue>
    <customValue>
        <fullName>Albania</fullName>
    </customValue>
    <customValue>
        <fullName>Algeria</fullName>
    </customValue>
    <customValue>
        <fullName>Andorra</fullName>
    </customValue>
    <customValue>
        <fullName>Angola</fullName>
    </customValue>
    <customValue>
        <fullName>Anguilla</fullName>
    </customValue>
    <customValue>
        <fullName>Antarctica</fullName>
    </customValue>
    <customValue>
        <fullName>Antigua and Barbuda</fullName>
    </customValue>
    <customValue>
        <fullName>Argentina</fullName>
    </customValue>
    <customValue>
        <fullName>Armenia</fullName>
    </customValue>
    <customValue>
        <fullName>Aruba</fullName>
    </customValue>
    <customValue>
        <fullName>Australia</fullName>
    </customValue>
    <customValue>
        <fullName>Austria</fullName>
    </customValue>
    <customValue>
        <fullName>Azerbaijan</fullName>
    </customValue>
    <customValue>
        <fullName>Bahamas</fullName>
    </customValue>
    <customValue>
        <fullName>Bahrain</fullName>
    </customValue>
    <customValue>
        <fullName>Bangladesh</fullName>
    </customValue>
    <customValue>
        <fullName>Barbados</fullName>
    </customValue>
    <customValue>
        <fullName>Belarus</fullName>
    </customValue>
    <customValue>
        <fullName>Belgium</fullName>
    </customValue>
    <customValue>
        <fullName>Belize</fullName>
    </customValue>
    <customValue>
        <fullName>Benin</fullName>
    </customValue>
    <customValue>
        <fullName>Bermuda</fullName>
    </customValue>
    <customValue>
        <fullName>Bhutan</fullName>
    </customValue>
    <customValue>
        <fullName>Bolivia, Plurinational State of</fullName>
    </customValue>
    <customValue>
        <fullName>Bonaire, Sint Eustatius and Saba</fullName>
    </customValue>
    <customValue>
        <fullName>Bosnia and Herzegovina</fullName>
    </customValue>
    <customValue>
        <fullName>Botswana</fullName>
    </customValue>
    <customValue>
        <fullName>Bouvet Island</fullName>
    </customValue>
    <customValue>
        <fullName>United States</fullName>
    </customValue>
    <description>Created for the new Address object and will be used for other objects (involved in integration with NetSuite)</description>
    <masterLabel>Country Global List</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet>

uipath-commons/main/default/globalValueSets/States_Global_List.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Acre</fullName>
    </customValue>
    <customValue>
        <fullName>Aguascalientes</fullName>
    </customValue>
    <customValue>
        <fullName>Alabama</fullName>
    </customValue>
    <customValue>
        <fullName>Alagoas</fullName>
    </customValue>
    <customValue>
        <fullName>Alaska</fullName>
    </customValue>
    <customValue>
        <fullName>Alberta</fullName>
    </customValue>
    <customValue>
        <fullName>Amapá</fullName>
    </customValue>
    <customValue>
        <fullName>Amazonas</fullName>
    </customValue>
    <customValue>
        <fullName>Andaman and Nicobar Islands</fullName>
    </customValue>
    <customValue>
        <fullName>Andhra Pradesh</fullName>
    </customValue>
    <customValue>
        <fullName>Anhui</fullName>
    </customValue>
    <customValue>
        <fullName>Arizona</fullName>
    </customValue>
    <customValue>
        <fullName>Arkansas</fullName>
    </customValue>
    <customValue>
        <fullName>Arunachal Pradesh</fullName>
    </customValue>
    <customValue>
        <fullName>Assam</fullName>
    </customValue>
    <customValue>
        <fullName>Bahia</fullName>
    </customValue>
    <customValue>
        <fullName>Baja California</fullName>
    </customValue>
    <customValue>
        <fullName>Baja California Sur</fullName>
    </customValue>
    <customValue>
        <fullName>Beijing</fullName>
    </customValue>
    <customValue>
        <fullName>Bihar</fullName>
    </customValue>
    <customValue>
        <fullName>British Columbia</fullName>
    </customValue>
    <customValue>
        <fullName>California</fullName>
    </customValue>
    <customValue>
        <fullName>Campeche</fullName>
    </customValue>
    <customValue>
        <fullName>Ceara</fullName>
    </customValue>
    <customValue>
        <fullName>Chandigarh</fullName>
    </customValue>
    <customValue>
        <fullName>Chhattisgarh</fullName>
    </customValue>
    <customValue>
        <fullName>Chiapas</fullName>
    </customValue>
    <customValue>
        <fullName>Chihuahua</fullName>
    </customValue>
    <customValue>
        <fullName>Chinese Taipei</fullName>
    </customValue>
    <customValue>
        <fullName>Chongqing</fullName>
    </customValue>
    <customValue>
        <fullName>Victoria</fullName>
    </customValue>
    <description>Created for the new Address object and will be used for other objects (involved in integration with NetSuite)</description>
    <masterLabel>States Global List</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet>

uipath-commons/main/default/classes/ZinfiCalloutClassTest.cls
/**
 * TODO refactor code in next iteration
 */
@SuppressWarnings('PMD')
@isTest
private class ZinfiCalloutClassTest {
  @TestSetup
  static void makeData() {
    ZinfiConfiguration__c zinfiSetting = new ZinfiConfiguration__c();
    zinfiSetting.IsSyncAccount__c = true;
    zinfiSetting.WebHook__c = 'WebHook';
    zinfiSetting.WebHookContact__c = 'WebHookContact';
    zinfiSetting.WebhookEndPoint__c = 'WebhookEndPoint';
    zinfiSetting.WebToken__c = 'WebToken';
    insert zinfiSetting;
  }

  @isTest
  static void testZinfiDeleteCallout() {
    Test.startTest();
    //Test.setMock(HttpCalloutMock.class, new ZinfiMockHttp());

    Account acc2 = new Account();
    acc2.Name = 'Zinfi Test Account';
    acc2.Partner_Portal_Contact_Sync__c = true;
    acc2.Business_Partner_Status__c = 'Good Standing';
    acc2.Country__c = 'Australia';
    acc2.State__c = 'Victoria';
    acc2.Classification__c = 'Commercial';
    acc2.Industry = 'Banking and Financial Services';
    insert acc2;

    Contact contact2 = new Contact();
    contact2.FirstName = 'Zinfi';
    contact2.LastName = 'Test';
    contact2.Email = 'zinfi.test@test.com';
    contact2.AccountId = acc2.Id;
    contact2.MailingCountry = 'Australia';
    contact2.MailingState = '';
    contact2.Title = 'Test';
    contact2.LeadSource = 'Webinar';
    insert contact2;
    delete contact2;
    delete acc2;

    Test.stopTest();
  }

  @isTest
  static void testZinfiUpdateCallout() {
    Test.startTest();
    //Test.setMock(HttpCalloutMock.class, new ZinfiMockHttp());

    Account acc = new Account();
    acc.Name = 'Zinfi Test Account';
    acc.Partner_Portal_Contact_Sync__c = true;
    acc.Business_Partner_Status__c = 'Good Standing';
    acc.Country__c = 'United States';
    acc.Classification__c = 'Commercial';
    acc.Industry = 'Banking and Financial Services';
    insert acc;

    Contact contact = new Contact();
    contact.FirstName = 'Zinfi';
    contact.LastName = 'Test';
    contact.Email = 'zinfi.test@test.com';
    contact.AccountId = acc.Id;
    contact.MailingCountry = 'United States';
    contact.MailingState = '';
    contact.Title = 'Test';
    contact.LeadSource = 'Webinar';
    insert contact;

    acc.Name = 'Zinfi 1';
    update acc;

    Test.stopTest();
  }
}