uipath-commons/main/default/objects/Account/fields/Business_Partner_Status__c.field-meta.xml
<CustomField>
    <fullName>Business_Partner_Status__c</fullName>
    <label>Business Partner Status</label>
    
        <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Good Standing</fullName>
            </value>
            <value>
                <fullName>Not in Program</fullName>
            </value>
            <value>
                <fullName>Pending Contract</fullName>
            </value>
            <value>
                <fullName>Pending Termination</fullName>
            </value>
            <value>
                <fullName>Terminated</fullName>
            </value>
            <value>
                <fullName>Not Yet Signed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

uipath-commons/main/default/objects/Account/fields/Partner_Portal_Contact_Sync__c.field-meta.xml
<CustomField>
    <fullName>Partner_Portal_Contact_Sync__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Partner Portal Contact Sync</label>
    <type>Checkbox</type>
</CustomField>

uipath-commons/main/default/objects/ZinfiConfiguration__c/ZinfiConfiguration__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Store settings for Zinfi Integration</description>
    <label>Zinfi Configuration</label>
</CustomObject>

uipath-commons/main/default/objects/ZinfiConfiguration__c/fields/IsSyncAccount__c.field-meta.xml
<CustomField>
    <fullName>IsSyncAccount__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Enable account sync with Zinfi</description>
    <label>IsSyncAccount</label>
    <type>Checkbox</type>
</CustomField>

uipath-commons/main/default/objects/ZinfiConfiguration__c/fields/WebHookContact__c.field-meta.xml
<CustomField>
    <fullName>WebHookContact__c</fullName>
    <description>Zinfi WebHookContact</description>
    <label>WebHookContact</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

uipath-commons/main/default/objects/ZinfiConfiguration__c/fields/WebhookEndPoint__c.field-meta.xml
<CustomField>
    <fullName>WebhookEndPoint__c</fullName>
    <description>Zinfi callout end point</description>
    <label>WebhookEndPoint</label>
    <type>Url</type>
</CustomField>

uipath-commons/main/default/objects/ZinfiConfiguration__c/fields/WebToken__c.field-meta.xml
<CustomField>
    <fullName>WebToken__c</fullName>
    <description>Zinfi WebToken</description>
    <label>WebToken</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

uipath-commons/main/default/classes/ZinfiSyncContactWithAccount.cls
/**
 * TODO refactor code in next iteration
 */
@SuppressWarnings('PMD')
public class ZinfiSyncContactWithAccount {
  @future(callout=true)
  public static void sendContactFutureCall(Set<Id> IdList) {
    ZinfiConfiguration__c zinfiSetting = ZinfiConfiguration__c.getInstance();
    List<ContactWrapper> WList = new List<ContactWrapper>();

    Set<String> contactFieldsToSync = new Set<String>{
      'FirstName',
      'LastName',
      'Email',
      'Id',
      'MailingCountry',
      'MailingState',
      'Direct_Phone__c',
      'Title',
      'AccountId'
    };

    // remove fields which are not present in the org
    Map<String, Schema.SobjectField> fieldMap = Schema.Contact.sObjectType.getDescribe().fields.getMap();
    for (String conField : contactFieldsToSync) {
      if (!fieldMap.containsKey(conField)) {
        contactFieldsToSync.remove(conField);
      }
    }

    List<Contact> CList = Database.query(
      'SELECT ' +
      String.join(new List<String>(contactFieldsToSync), ',') +
      ' FROM Contact' +
      ' WHERE Account.Business_Partner_Status__c=\'Good Standing\' ' +
      ' AND Account.Partner_Portal_Contact_Sync__c=true' +
      ' AND AccountId IN :IdList'
    );

    for (Contact n : CList) {
      ContactWrapper nw = new ContactWrapper();
      nw.ID = getDataFromSObject(n, 'Id');
      nw.FirstName = getDataFromSObject(n, 'FirstName');
      nw.LastName = getDataFromSObject(n, 'LastName');
      nw.EMAIL = getDataFromSObject(n, 'Email');
      nw.MailingCountry = getDataFromSObject(n, 'MailingCountry');
      nw.MailingState = getDataFromSObject(n, 'MailingState');
      nw.DirectPhone = getDataFromSObject(n, 'Direct_Phone__c');
      nw.Title = getDataFromSObject(n, 'Title');
      nw.AccountID = getDataFromSObject(n, 'AccountId');
      WList.add(nw);
    }

    String strbdy = JSON.serialize(WList);
    System.debug(':::strbdy=' + strbdy);
    Http htp = new Http();
    HttpRequest hr = new HttpRequest();
    hr.setMethod('POST');
    hr.setEndPoint(zinfiSetting.WebhookEndPoint__c);

    hr.setBody(strbdy);
    hr.setHeader('Content-Type', 'application/json');
    hr.setHeader('Accept', 'application/json');
    hr.setHeader('WebToken', zinfiSetting.WebToken__c);
    hr.setHeader('WebHook', zinfiSetting.WebHookContact__c);
    System.debug(':::hr=' + hr);
    try {
      HttpResponse hs = htp.send(hr);
      String rsStr = hs.getBody();
      System.debug('***** response=' + rsStr);
      System.debug('***** StatusCode =' + hs.getStatusCode());
    } catch (Exception e) {
      System.debug('***** Exception=' + e.getMessage());
    }
  }

  public class ContactWrapper {
    public string ID;
    public string FirstName;
    public string LastName;
    public string EMAIL;
    public string MailingCountry;
    public string MailingState;
    public string DirectPhone;
    public string Title;
    public string AccountID;
  }

  /**
   * If field is not present in the org then return blank
   */
  private static String getDataFromSObject(SObject sObj, String fieldName) {
    try {
      return sObj.get(fieldName) + '';
    } catch (Exception e) {
      return '';
    }
  }

  /**
   * TODO refactor code into Queueable
   * Sync data with Zinfi system
   */
  public static void zinfiSyncAccountOnUpdate(Map<Id, SObject> existingRecords) {
    ZinfiConfiguration__c zinfiSetting = ZinfiConfiguration__c.getInstance();
    if (zinfiSetting != null && zinfiSetting.IsSyncAccount__c) {
      ZinfiSyncContactWithAccount.sendContactFutureCall(existingRecords.keySet());
    }
  }
}