uipath-commons/main/default/objects/Account/fields/Classification__c.field-meta.xml
<CustomField>
    <fullName>Classification__c</fullName>
    <label>Classification</label>
    
        <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Others</fullName>
            </value>
            <value>
                <fullName>Diamond</fullName>
            </value>
            <value>
                <fullName>Gold</fullName>
            </value>
            <value>
                <fullName>Silver</fullName>
            </value>
            <value>
                <fullName>Global</fullName>
            </value>
            <value>
                <fullName>Enterprise</fullName>
            </value>
            <value>
                <fullName>Commercial</fullName>
            </value>
            <value>
                <fullName>SMB</fullName>
            </value>
            <value>
                <fullName>Velocity</fullName>
            </value>
            <value>
                <fullName>General Business</fullName>
            </value>
            <value>
                <fullName>Inside Sales</fullName>
            </value>
            <value>
                <fullName>Global - Strategic</fullName>
                <isActive>false</isActive>
                <label>Global - Strategic</label>
            </value>
            <value>
                <fullName>Growth</fullName>
                <isActive>false</isActive>
                <label>Growth</label>
            </value>
            <value>
                <fullName>Key</fullName>
                <isActive>false</isActive>
                <label>Key</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

uipath-commons/main/default/objects/Account/fields/Geo__c.field-meta.xml
<CustomField>
        <fullName>Geo__c</fullName>
        <label>Geo</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>AMER</fullName>
                </value>
                <value>
                    <fullName>APAC</fullName>
                </value>
                <value>
                    <fullName>EMEA</fullName>
                </value>
                <value>
                    <fullName>Japan</fullName>
                </value>
                <value>
                    <fullName>India</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </CustomField>

uipath-commons/main/default/objects/Account/fields/Overwrite_Classification__c.field-meta.xml
<CustomField>
        <fullName>Overwrite_Classification__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Used to exclude Classification field from being updated by the Account Segmentation process.</description>
        <label>Overwrite Classification</label>
        <type>Checkbox</type>
    </CustomField>

uipath-commons/main/default/objects/Account/fields/Region__c.field-meta.xml
<CustomField>
    <fullName>Region__c</fullName>
    <label>Region</label>
    
        <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>ANZ</fullName>
            </value>
            <value>
                <fullName>BFS</fullName>
            </value>
            <value>
                <fullName>Canada</fullName>
            </value>
            <value>
                <fullName>Greater China</fullName>
            </value>
            <value>
                <fullName>GOV</fullName>
            </value>
            <value>
                <fullName>India</fullName>
            </value>
            <value>
                <fullName>Korea</fullName>
            </value>
            <value>
                <fullName>LATAM</fullName>
            </value>
            <value>
                <fullName>MEA</fullName>
            </value>
            <value>
                <fullName>Nordics</fullName>
            </value>
            <value>
                <fullName>NorthCentral</fullName>
            </value>
            <value>
                <fullName>NorthEast</fullName>
            </value>
            <value>
                <fullName>NorthWest</fullName>
            </value>
            <value>
                <fullName>Others</fullName>
            </value>
            <value>
                <fullName>SEA</fullName>
            </value>
            <value>
                <fullName>SouthWest</fullName>
            </value>
            <value>
                <fullName>SouthCentral</fullName>
            </value>
            <value>
                <fullName>SouthEast</fullName>
            </value>
            <value>
                <fullName>UKI</fullName>
            </value>
            <value>
                <fullName>CE</fullName>
            </value>
            <value>
                <fullName>EECIS</fullName>
            </value>
            <value>
                <fullName>France</fullName>
            </value>
            <value>
                <fullName>Italy/Greece</fullName>
            </value>
            <value>
                <fullName>Iberia</fullName>
            </value>
            <value>
                <fullName>Benelux</fullName>
            </value>
            <value>
                <fullName>Japan</fullName>
            </value>
            <value>
                <fullName>Hokkaido</fullName>
            </value>
            <value>
                <fullName>Tohoku</fullName>
            </value>
            <value>
                <fullName>Kanto</fullName>
            </value>
            <value>
                <fullName>Chubu</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

uipath-commons/main/default/objects/Account/recordTypes/Prospect.recordType-meta.xml
<RecordType>
        <fullName>Prospect</fullName>
        <active>true</active>
        <description
  >Non-Customer and non-Partner Account with past or existing UiPath Sales Opportunities</description>
        <label>Prospect</label>
 
        
  
       
      
    </RecordType>

uipath-commons/main/default/classes/AccountSetClassificationFunctionTest.cls
@isTest
private class AccountSetClassificationFunctionTest {
  @isTest
  private static void setClassificationFieldTest() {
    Id prospectRT = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('Prospect').getRecordTypeId();

    Account account1 = new Account(
      Id = fflib_IDGenerator.generate(Account.SObjectType),
      Name = 'Test1',
      Geo__c = 'APAC',
      RecordTypeId = prospectRT,
      AnnualRevenue = 150000000.00,
      Overwrite_Classification__c = false
    );
    Account oldAccount1 = new Account(Id = account1.Id, Name = 'Test1');

    Account account2 = new Account(
      Id = fflib_IDGenerator.generate(Account.SObjectType),
      Name = 'Test2',
      Geo__c = 'AMER',
      Region__c = 'LATAM',
      RecordTypeId = prospectRT,
      AnnualRevenue = 150000000.00,
      Overwrite_Classification__c = false
    );
    Account oldAccount2 = new Account(Id = account2.Id, Name = 'Test2');

    Account account3 = new Account(
      Id = fflib_IDGenerator.generate(Account.SObjectType),
      Name = 'Test3',
      Geo__c = 'EMEA',
      RecordTypeId = prospectRT,
      AnnualRevenue = 250000000.00,
      Overwrite_Classification__c = false
    );
    Account oldAccount3 = new Account(Id = account3.Id, Name = 'Test3');

    Account account4 = new Account(
      Id = fflib_IDGenerator.generate(Account.SObjectType),
      Name = 'Test4',
      Geo__c = 'AMER',
      Region__c = 'LATAM',
      RecordTypeId = prospectRT,
      AnnualRevenue = 140000000.00,
      Overwrite_Classification__c = false
    );
    Account oldAccount4 = new Account(Id = account4.Id, Name = 'Test4');

    Account account5 = new Account(
      Id = fflib_IDGenerator.generate(Account.SObjectType),
      Name = 'Test5',
      Geo__c = 'India',
      RecordTypeId = prospectRT,
      AnnualRevenue = 10.00,
      Overwrite_Classification__c = false
    );
    Account oldAccount5 = new Account(Id = account5.Id, Name = 'Test5');

    Account account6 = new Account(
      Id = fflib_IDGenerator.generate(Account.SObjectType),
      Name = 'Test6',
      Geo__c = 'APAC',
      RecordTypeId = prospectRT,
      AnnualRevenue = 250000000.00,
      Overwrite_Classification__c = false
    );
    Account oldAccount6 = new Account(Id = account6.Id, Name = 'Test6');

    Account account7 = new Account(
      Id = fflib_IDGenerator.generate(Account.SObjectType),
      Name = 'Test7',
      Geo__c = 'EMEA',
      RecordTypeId = prospectRT,
      AnnualRevenue = 240000000.00,
      Overwrite_Classification__c = false
    );
    Account oldAccount7 = new Account(Id = account7.Id, Name = 'Test7');

    Account account8 = new Account(
      Id = fflib_IDGenerator.generate(Account.SObjectType),
      Name = 'Test8',
      Geo__c = 'AMER',
      Region__c = 'Canada',
      RecordTypeId = prospectRT,
      AnnualRevenue = 200000000.00,
      Overwrite_Classification__c = false
    );
    Account oldAccount8 = new Account(Id = account8.Id, Name = 'Test8');

    fflib_SObjectDomain.Test.Database.onUpdate(
      new List<Account>{ account1, account2, account3, account4, account5, account6, account7, account8 },
      new Map<Id, SObject>{
        oldAccount1.Id => oldAccount1,
        oldAccount2.Id => oldAccount2,
        oldAccount3.Id => oldAccount3,
        oldAccount4.Id => oldAccount4,
        oldAccount5.Id => oldAccount5,
        oldAccount6.Id => oldAccount6,
        oldAccount7.Id => oldAccount7,
        oldAccount8.Id => oldAccount8
      }
    );
    fflib_SObjectDomain.triggerHandler(Accounts.class);

    System.assertEquals(account1.Classification__c, 'SMB');
    System.assertEquals(account2.Classification__c, 'Enterprise');
    System.assertEquals(account3.Classification__c, 'Commercial');
    System.assertEquals(account4.Classification__c, 'Velocity');
    System.assertEquals(account5.Classification__c, 'Commercial');
    System.assertEquals(account6.Classification__c, 'Commercial');
    System.assertEquals(account7.Classification__c, 'SMB');
    System.assertEquals(account8.Classification__c, 'Enterprise');
  }
}