uipath-commons/main/default/objects/Account/fields/Classification__c.field-meta.xml
<CustomField>
    <fullName>Classification__c</fullName>
    <label>Classification</label>
    
        <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Others</fullName>
            </value>
            <value>
                <fullName>Diamond</fullName>
            </value>
            <value>
                <fullName>Gold</fullName>
            </value>
            <value>
                <fullName>Silver</fullName>
            </value>
            <value>
                <fullName>Global</fullName>
            </value>
            <value>
                <fullName>Enterprise</fullName>
            </value>
            <value>
                <fullName>Commercial</fullName>
            </value>
            <value>
                <fullName>SMB</fullName>
            </value>
            <value>
                <fullName>Velocity</fullName>
            </value>
            <value>
                <fullName>General Business</fullName>
            </value>
            <value>
                <fullName>Inside Sales</fullName>
            </value>
            <value>
                <fullName>Global - Strategic</fullName>
                <isActive>false</isActive>
                <label>Global - Strategic</label>
            </value>
            <value>
                <fullName>Growth</fullName>
                <isActive>false</isActive>
                <label>Growth</label>
            </value>
            <value>
                <fullName>Key</fullName>
                <isActive>false</isActive>
                <label>Key</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

uipath-commons/main/default/objects/Account/fields/Overwrite_Classification__c.field-meta.xml
<CustomField>
        <fullName>Overwrite_Classification__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Used to exclude Classification field from being updated by the Account Segmentation process.</description>
        <label>Overwrite Classification</label>
        <type>Checkbox</type>
    </CustomField>

uipath-commons/main/default/classes/AccountSetClassificationQueueable.cls
public with sharing class AccountSetClassificationQueueable extends AbstractQueueable {
  private final List<SObject> accounts;

  public AccountSetClassificationQueueable(List<SObject> accounts) {
    super('AccountSetClassificationQueueable');
    this.accounts = accounts;
  }

  public override void work() {
    this.setFormulaClassificationOnChildren(this.accounts);
  }
  private void setFormulaClassificationOnChildren(List<SObject> accounts) {
    List<Id> recordTypesOfInterest = new List<Id>{
      AccountMetadata.customerRecordType,
      AccountMetadata.customerProspectRecordType,
      AccountMetadata.ProspectRecordType
    };
    List<Account> children = [
      SELECT
        Id,
        Name,
        Parent.Overwrite_Classification__c,
        Parent.Parent.Overwrite_Classification__c
      FROM Account
      WHERE
        (Parent.Parent.Parent.Id IN :accounts
        OR Parent.Parent.Id IN :accounts
        OR Parent.Id IN :accounts)
        AND RecordTypeId IN :recordTypesOfInterest
        AND Classification__c = 'Global'
        AND Overwrite_Classification__c = false
    ];

    for (Account acc : children) {
      if (
        acc.Parent.Overwrite_Classification__c == false &&
        acc.Parent.Parent.Overwrite_Classification__c == false
      )
        acc.Classification__c = '';
    }
    update children;
  }

  /**
   * For non-global accounts, when an Account Classification changes from 'Global' to the formula based on AnnualRevenue, Geo and Region set all children accounts to follow the
   * @param accounts
   * @param existingAccounts
   */
  public static void setClassificationByGeoAndRevenue(
    List<Account> accounts,
    Map<Id, SObject> existingAccounts
  ) {
    SObjectPredicate hasChanged = new HasRecordChanged(
      new Set<SObjectField>{ Account.Classification__c },
      accounts,
      existingAccounts
    );

    List<Account> changedAccounts = Collection.of(accounts)
      .filter(hasChanged)
      .filter(
        Match.field(Account.RecordTypeId)
          .isIn(
            new Set<String>{
              AccountMetadata.customerRecordType,
              AccountMetadata.customerProspectRecordType,
              AccountMetadata.ProspectRecordType,
              null
            }
          )
          .also(Account.Classification__c)
          .notEquals('Global')
          .also(Account.Overwrite_Classification__c)
          .equals(false)
          .also(Account.AnnualRevenue)
          .notEquals(null)
      )
      .asList();

    if (!changedAccounts.isEmpty()) {
      AbstractQueueable.enqueue(
        new AccountSetClassificationQueueable(changedAccounts)
      );
    }
  }
}