uipath-commons/main/default/objects/Account/fields/Classification__c.field-meta.xml
<CustomField>
    <fullName>Classification__c</fullName>
    <label>Classification</label>
    
        <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Others</fullName>
            </value>
            <value>
                <fullName>Diamond</fullName>
            </value>
            <value>
                <fullName>Gold</fullName>
            </value>
            <value>
                <fullName>Silver</fullName>
            </value>
            <value>
                <fullName>Global</fullName>
            </value>
            <value>
                <fullName>Enterprise</fullName>
            </value>
            <value>
                <fullName>Commercial</fullName>
            </value>
            <value>
                <fullName>SMB</fullName>
            </value>
            <value>
                <fullName>Velocity</fullName>
            </value>
            <value>
                <fullName>General Business</fullName>
            </value>
            <value>
                <fullName>Inside Sales</fullName>
            </value>
            <value>
                <fullName>Global - Strategic</fullName>
                <isActive>false</isActive>
                <label>Global - Strategic</label>
            </value>
            <value>
                <fullName>Growth</fullName>
                <isActive>false</isActive>
                <label>Growth</label>
            </value>
            <value>
                <fullName>Key</fullName>
                <isActive>false</isActive>
                <label>Key</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

uipath-commons/main/default/objects/Account/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <description>This required field will be used to capture the country on the creation of a new account. It will populate the country on the new address records for accounts. The standard billing and shipping address fields on account will be made read only.</description>
    <label>Country</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Country_Global_List</valueSetName>
    </valueSet>
</CustomField>

uipath-core/main/default/globalValueSets/Country_Global_List.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Afghanistan</fullName>
    </customValue>
    <customValue>
        <fullName>Aland Islands</fullName>
    </customValue>
    <customValue>
        <fullName>Albania</fullName>
    </customValue>
    <customValue>
        <fullName>Algeria</fullName>
    </customValue>
    <customValue>
        <fullName>Andorra</fullName>
    </customValue>
    <customValue>
        <fullName>Angola</fullName>
    </customValue>
    <customValue>
        <fullName>Anguilla</fullName>
    </customValue>
    <customValue>
        <fullName>Antarctica</fullName>
    </customValue>
    <customValue>
        <fullName>Antigua and Barbuda</fullName>
    </customValue>
    <customValue>
        <fullName>Argentina</fullName>
    </customValue>
    <customValue>
        <fullName>Armenia</fullName>
    </customValue>
    <customValue>
        <fullName>Aruba</fullName>
    </customValue>
    <customValue>
        <fullName>Australia</fullName>
    </customValue>
    <customValue>
        <fullName>Austria</fullName>
    </customValue>
    <customValue>
        <fullName>Azerbaijan</fullName>
    </customValue>
    <customValue>
        <fullName>Bahamas</fullName>
    </customValue>
    <customValue>
        <fullName>Bahrain</fullName>
    </customValue>
    <customValue>
        <fullName>Bangladesh</fullName>
    </customValue>
    <customValue>
        <fullName>Barbados</fullName>
    </customValue>
    <customValue>
        <fullName>Belarus</fullName>
    </customValue>
    <customValue>
        <fullName>Belgium</fullName>
    </customValue>
    <customValue>
        <fullName>Belize</fullName>
    </customValue>
    <customValue>
        <fullName>Benin</fullName>
    </customValue>
    <customValue>
        <fullName>Bermuda</fullName>
    </customValue>
    <customValue>
        <fullName>Bhutan</fullName>
    </customValue>
    <customValue>
        <fullName>Bolivia, Plurinational State of</fullName>
    </customValue>
    <customValue>
        <fullName>Bonaire, Sint Eustatius and Saba</fullName>
    </customValue>
    <customValue>
        <fullName>Bosnia and Herzegovina</fullName>
    </customValue>
    <customValue>
        <fullName>Botswana</fullName>
    </customValue>
    <customValue>
        <fullName>Bouvet Island</fullName>
    </customValue>
    <customValue>
        <fullName>United Kingdom</fullName>
    </customValue>
    <description>Created for the new Address object and will be used for other objects (involved in integration with NetSuite)</description>
    <masterLabel>Country Global List</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet>

uipath-commons/main/default/classes/AccountSharingRollupQueueableTest.cls
/**
 * TODO REWRITE with Mocking as too much DML involved
 */
@isTest
public class AccountSharingRollupQueueableTest {
  @isTest
  public static void canRunAccountSharingJobOnInsert() {
    User u1 = new User();
    u1.ProfileId = [SELECT Id FROM Profile WHERE Name = 'System Administrator']
    .Id;
    u1.Username = 'canRunAccountSharingJob@uipath.com';
    u1.LastName = 'Test';
    u1.Email = 'canRunAccountSharingJob@uipath.com';
    u1.Alias = 't839734';
    u1.TimeZoneSidKey = 'America/Los_Angeles';
    u1.LocaleSidKey = 'en_US';
    u1.EmailEncodingKey = 'UTF-8';
    u1.LanguageLocaleKey = 'en_US';

    insert u1;

    Account ukAccountParent = new Account(
      Name = 'TestAccountUK',
      Country__c = 'United Kingdom',
      BillingCountry = 'United Kingdom',
      OwnerId = u1.Id,
      Industry = 'Others'
    );

    insert ukAccountParent;

    Account ukAccountChild = ukAccountParent.clone();
    ukAccountChild.Name = 'ChildTestAccountUK';
    ukAccountChild.ParentId = ukAccountParent.Id;
    ukAccountChild.Classification__c = 'Global';
    ukAccountChild.OwnerId = UserInfo.getUserId();

    insert ukAccountChild;

    AccountSharingRollupQueueable accountSharingRollupQueueable = new AccountSharingRollupQueueable(
      new List<Account>{ ukAccountChild },
      null
    );
    accountSharingRollupQueueable.execute(null);

    List<AccountShare> accountShares = [
      SELECT Id
      FROM AccountShare
      WHERE
        AccountId = :ukAccountChild.Id
        AND AccountAccessLevel = 'Edit'
        AND OpportunityAccessLevel = 'Edit'
        AND UserOrGroupId = :u1.Id
    ];
    System.assertEquals(
      1,
      accountShares.size(),
      'Parent Account owner should have edit access to Account and Opty'
    );
  }

  @isTest
  public static void canRunAccountSharingJobOnUpdateOfParentOwner() {
    User u1 = new User();
    u1.ProfileId = [SELECT Id FROM Profile WHERE Name = 'System Administrator']
    .Id;
    u1.Username = 'canRunAccountSharingJob@uipath.com';
    u1.LastName = 'Test';
    u1.Email = 'canRunAccountSharingJob@uipath.com';
    u1.Alias = 't839734';
    u1.TimeZoneSidKey = 'America/Los_Angeles';
    u1.LocaleSidKey = 'en_US';
    u1.EmailEncodingKey = 'UTF-8';
    u1.LanguageLocaleKey = 'en_US';

    User u2 = new User();
    u2.ProfileId = [SELECT Id FROM Profile WHERE Name = 'System Administrator']
    .Id;
    u2.Username = '2canRunAccountSharingJob@uipath.com';
    u2.LastName = '2Test';
    u2.Email = '2canRunAccountSharingJob@uipath.com';
    u2.Alias = '2t839734';
    u2.TimeZoneSidKey = 'America/Los_Angeles';
    u2.LocaleSidKey = 'en_US';
    u2.EmailEncodingKey = 'UTF-8';
    u2.LanguageLocaleKey = 'en_US';

    insert new List<User>{ u1, u2 };

    Account ukAccountParent = new Account(
      Name = 'TestAccountUK',
      Country__c = 'United Kingdom',
      BillingCountry = 'United Kingdom',
      OwnerId = u1.Id,
      Industry = 'Others'
    );

    insert ukAccountParent;

    Account ukAccountChild = ukAccountParent.clone();
    ukAccountChild.Name = 'ChildTestAccountUK';
    ukAccountChild.ParentId = ukAccountParent.Id;
    ukAccountChild.Classification__c = 'Global';
    ukAccountChild.OwnerId = UserInfo.getUserId();

    insert ukAccountChild;

    AccountSharingRollupQueueable accountSharingRollupQueueable = new AccountSharingRollupQueueable(
      new List<Account>{ ukAccountChild },
      null
    );
    accountSharingRollupQueueable.execute(null);

    ukAccountParent.OwnerId = u2.Id;
    update ukAccountParent;

    AccountSharingRollupQueueable accountSharingRollupQueueable2 = new AccountSharingRollupQueueable(
      new List<Account>{ ukAccountChild },
      null
    );
    accountSharingRollupQueueable2.execute(null);

    List<AccountShare> accountShares = [
      SELECT Id
      FROM AccountShare
      WHERE
        AccountId = :ukAccountChild.Id
        AND AccountAccessLevel = 'Edit'
        AND OpportunityAccessLevel = 'Edit'
        AND UserOrGroupId = :u2.Id
    ];
    System.assertEquals(
      1,
      accountShares.size(),
      'Parent Account owner should have edit access to Account and Opty'
    );
  }
}