uipath-commons/main/default/objects/Account/fields/Classification__c.field-meta.xml
<CustomField>
    <fullName>Classification__c</fullName>
    <label>Classification</label>
    
        <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Others</fullName>
            </value>
            <value>
                <fullName>Diamond</fullName>
            </value>
            <value>
                <fullName>Gold</fullName>
            </value>
            <value>
                <fullName>Silver</fullName>
            </value>
            <value>
                <fullName>Global</fullName>
            </value>
            <value>
                <fullName>Enterprise</fullName>
            </value>
            <value>
                <fullName>Commercial</fullName>
            </value>
            <value>
                <fullName>SMB</fullName>
            </value>
            <value>
                <fullName>Velocity</fullName>
            </value>
            <value>
                <fullName>General Business</fullName>
            </value>
            <value>
                <fullName>Inside Sales</fullName>
            </value>
            <value>
                <fullName>Global - Strategic</fullName>
                <isActive>false</isActive>
                <label>Global - Strategic</label>
            </value>
            <value>
                <fullName>Growth</fullName>
                <isActive>false</isActive>
                <label>Growth</label>
            </value>
            <value>
                <fullName>Key</fullName>
                <isActive>false</isActive>
                <label>Key</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

uipath-commons/main/default/objects/Account/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <description>This required field will be used to capture the country on the creation of a new account. It will populate the country on the new address records for accounts. The standard billing and shipping address fields on account will be made read only.</description>
    <label>Country</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Country_Global_List</valueSetName>
    </valueSet>
</CustomField>

uipath-commons/main/default/objects/Account/fields/Geo__c.field-meta.xml
<CustomField>
        <fullName>Geo__c</fullName>
        <label>Geo</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>AMER</fullName>
                </value>
                <value>
                    <fullName>APAC</fullName>
                </value>
                <value>
                    <fullName>EMEA</fullName>
                </value>
                <value>
                    <fullName>Japan</fullName>
                </value>
                <value>
                    <fullName>India</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </CustomField>

uipath-commons/main/default/objects/Account/fields/Overwrite_Classification__c.field-meta.xml
<CustomField>
        <fullName>Overwrite_Classification__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Used to exclude Classification field from being updated by the Account Segmentation process.</description>
        <label>Overwrite Classification</label>
        <type>Checkbox</type>
    </CustomField>

uipath-commons/main/default/objects/Account/recordTypes/Customer.recordType-meta.xml
<RecordType>
    <fullName>Customer</fullName>
    <active>true</active>
    <description>Customer account, i.e., account of a company with purchase transactions</description>
    <label>Customer</label>
</RecordType>

uipath-commons/main/default/classes/AccountClassificationGlobalQueueableTest.cls
@isTest
public with sharing class AccountClassificationGlobalQueueableTest {
  private static final string USA = 'United States';

  @isTest
  public static void setupClassification_InsertTest() {
    Id customerRT = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('Customer').getRecordTypeId();

    Account topParentAcc = new Account(
      Name = 'TopParentAccount',
      Geo__c = 'APAC',
      RecordTypeId = customerRT,
      Classification__c = 'General Business',
      Country__c = USA,
      BillingCountry = USA,
      Industry = 'Communications'
    );
    insert topParentAcc;

    Account parentAccount = new Account(
      Name = 'Parent Account',
      ParentId = topParentAcc.Id,
      RecordTypeId = customerRT,
      Classification__c = 'Global',
      Country__c = 'France',
      BillingCountry = USA,
      Industry = 'Communications',
      Overwrite_Classification__c = true
    );
    insert parentAccount;

    Account parentAccount1 = [
      SELECT Id, Classification__c, Overwrite_Classification__c
      FROM Account
      WHERE Id = :parentAccount.Id
      LIMIT 1
    ];
    parentAccount1.Classification__c = 'Global';
    parentAccount1.Overwrite_Classification__c = true;
    update parentAccount1;

    Account childparentAccount = new Account(
      Name = 'ChildrenAccount11',
      ParentId = parentAccount1.Id,
      RecordTypeId = customerRT,
      Country__c = USA,
      BillingCountry = USA,
      Industry = 'Communications',
      Overwrite_Classification__c = false
    );

    fflib_SObjectDomain.Test.Database.onInsert(new List<Account>{ childparentAccount });
    fflib_SObjectDomain.triggerHandler(Accounts.class);
    System.assertEquals('Global', childparentAccount.Classification__c);

    Id accountId = fflib_IDGenerator.generate(Account.SObjectType);
    Account childAccount = new Account(
      Id = accountId,
      Name = 'ChildrenAccount11',
      RecordTypeId = customerRT,
      Country__c = USA,
      BillingCountry = USA,
      Industry = 'Communications',
      ParentId = childparentAccount.Id
    );

    Account childAccountOld = new Account(
      Id = accountId,
      Name = 'ChildrenAccount11',
      RecordTypeId = customerRT,
      Country__c = USA,
      BillingCountry = USA,
      Industry = 'Communications'
    );

    fflib_SObjectDomain.Test.Database.onUpdate(
      new List<Account>{ childAccount },
      new Map<Id, SObject>{ childAccountOld.Id => childAccountOld }
    );
    fflib_SObjectDomain.triggerHandler(Accounts.class);
  }

  @isTest
  public static void setupClassification_Update2Test() {
    Id customerRT = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('Customer').getRecordTypeId();

    Account topParentAcc = new Account(
      Name = 'TopParentAccount',
      Geo__c = 'APAC',
      RecordTypeId = customerRT,
      Classification__c = 'General Business',
      Country__c = USA,
      BillingCountry = USA,
      Industry = 'Communications'
    );
    insert topParentAcc;

    Account parentAccount1 = new Account(
      Name = 'Parent Account 1',
      ParentId = topParentAcc.Id,
      RecordTypeId = customerRT,
      Classification__c = 'Velocity',
      Country__c = 'France',
      BillingCountry = 'France',
      Industry = 'Communications',
      Overwrite_Classification__c = true
    );
    insert parentAccount1;

    List<Account> childrenAccounts = new List<Account>();
    Account childparentAccount11 = new Account(
      Name = 'ChildrenAccount11',
      ParentId = parentAccount1.Id,
      RecordTypeId = customerRT,
      Classification__c = 'Velocity',
      Country__c = USA,
      BillingCountry = USA,
      Industry = 'Communications',
      Overwrite_Classification__c = true
    );
    childrenAccounts.add(childparentAccount11);

    Account childparentAccount12 = new Account(
      Name = 'Children Account 12',
      ParentId = parentAccount1.Id,
      RecordTypeId = customerRT,
      Classification__c = 'Velocity',
      Country__c = 'Germany',
      BillingCountry = 'Germany',
      Industry = 'Communications',
      Overwrite_Classification__c = true
    );
    childrenAccounts.add(childparentAccount12);

    Account parentAccount2 = new Account(
      Name = 'ParentAccount2',
      ParentId = topParentAcc.Id,
      RecordTypeId = customerRT,
      Classification__c = 'Velocity',
      Country__c = 'Italy',
      BillingCountry = 'Italy',
      Industry = 'Communications',
      Overwrite_Classification__c = true
    );
    insert parentAccount2;

    Account childparentAccount21 = new Account(
      Name = 'ChildrenAccount21',
      ParentId = parentAccount2.Id,
      RecordTypeId = customerRT,
      Classification__c = 'Velocity',
      Country__c = 'Peru',
      BillingCountry = 'Peru',
      Industry = 'Communications',
      Overwrite_Classification__c = true
    );
    childrenAccounts.add(childparentAccount21);

    Account childparentAccount22 = new Account(
      Name = 'Children Account 22',
      ParentId = parentAccount2.Id,
      RecordTypeId = customerRT,
      Classification__c = 'Velocity',
      Country__c = USA,
      BillingCountry = USA,
      Industry = 'Communications',
      Overwrite_Classification__c = true
    );
    childrenAccounts.add(childparentAccount22);

    insert childrenAccounts;

    Account childparentAccount23 = new Account(
      Name = 'Child Account 23',
      ParentId = parentAccount2.Id,
      RecordTypeId = customerRT,
      Classification__c = 'Velocity',
      Country__c = 'Japan',
      BillingCountry = 'Japan',
      Industry = 'Communications',
      Overwrite_Classification__c = true
    );
    insert childparentAccount23;

    List<Account> childrenAccounts2 = new List<Account>();
    Account a = new Account();
    for (Integer i = 1; i < 5; i++) {
      a = new Account(
        Name = string.valueOf(i) + 'A Children Account 23',
        ParentId = childparentAccount23.Id,
        RecordTypeId = customerRT,
        Classification__c = 'Velocity',
        Country__c = 'Canada',
        BillingCountry = 'Canada',
        Industry = 'Communications',
        Overwrite_Classification__c = true
      );
      childrenAccounts2.add(a);
    }
    insert childrenAccounts2;

    List<Account> parentAcc = [
      SELECT Id, Name, Classification__c
      FROM Account
      WHERE Name = 'Parent Account 1' OR Name = 'ParentAccount2'
    ];
    for (Account acc : parentAcc)
      acc.Classification__c = 'Global';

    update parentAcc;

    AccountClassificationGlobalQueueable accSetClassificationGlobal = new AccountClassificationGlobalQueueable(
      new List<Account>{ parentAcc[0], parentAcc[1] }
    );
    accSetClassificationGlobal.execute(null);

    List<Account> childAccountIns = [
      SELECT Id, Name, Classification__c
      FROM Account
      WHERE Classification__c = 'Global'
    ];
    System.assertEquals(11, childAccountIns.size());
  }

  @IsTest
  public static void temp() {
    Id customerRT = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('Customer').getRecordTypeId();
    Account topParentAcc = new Account(
      Name = 'TopParentAccount',
      Geo__c = 'APAC',
      RecordTypeId = customerRT,
      Classification__c = 'General Business',
      Country__c = USA,
      Industry = 'Communications'
    );
    insert topParentAcc;

    Account child1 = new Account(
      Name = 'child1',
      ParentId = topParentAcc.Id,
      RecordTypeId = customerRT,
      Classification__c = 'Velocity',
      Country__c = 'France',
      Industry = 'Communications'
    );
    insert child1;

    Account grandchild1 = new Account(
      Name = 'grandchild1',
      ParentId = child1.Id,
      RecordTypeId = customerRT,
      Classification__c = 'Velocity',
      Country__c = 'France',
      Industry = 'Communications'
    );
    insert grandchild1;

    Account greatgrandchild1 = new Account(
      Name = 'greatgrandchild1',
      ParentId = grandchild1.Id,
      RecordTypeId = customerRT,
      Classification__c = 'Velocity',
      Country__c = 'France',
      Industry = 'Communications'
    );
    insert greatgrandchild1;

    List<Account> accounts = [
      SELECT id, name
      FROM Account
      WHERE
        Parent.Parent.Parent.Id IN :new List<Account>{ topParentAcc }
        OR Parent.Parent.Id IN :new List<Account>{ topParentAcc }
        OR Parent.Id IN :new List<Account>{ topParentAcc }
    ];

    for (Account account : accounts) {
      System.debug('======' + account.name);
    }
  }
}