uipath-commons/main/default/objects/Account/fields/Classification__c.field-meta.xml
<CustomField>
    <fullName>Classification__c</fullName>
    <label>Classification</label>
    
        <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Others</fullName>
            </value>
            <value>
                <fullName>Diamond</fullName>
            </value>
            <value>
                <fullName>Gold</fullName>
            </value>
            <value>
                <fullName>Silver</fullName>
            </value>
            <value>
                <fullName>Global</fullName>
            </value>
            <value>
                <fullName>Enterprise</fullName>
            </value>
            <value>
                <fullName>Commercial</fullName>
            </value>
            <value>
                <fullName>SMB</fullName>
            </value>
            <value>
                <fullName>Velocity</fullName>
            </value>
            <value>
                <fullName>General Business</fullName>
            </value>
            <value>
                <fullName>Inside Sales</fullName>
            </value>
            <value>
                <fullName>Global - Strategic</fullName>
                <isActive>false</isActive>
                <label>Global - Strategic</label>
            </value>
            <value>
                <fullName>Growth</fullName>
                <isActive>false</isActive>
                <label>Growth</label>
            </value>
            <value>
                <fullName>Key</fullName>
                <isActive>false</isActive>
                <label>Key</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

uipath-commons/main/default/objects/Account/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <description>This required field will be used to capture the country on the creation of a new account. It will populate the country on the new address records for accounts. The standard billing and shipping address fields on account will be made read only.</description>
    <label>Country</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Country_Global_List</valueSetName>
    </valueSet>
</CustomField>

uipath-commons/main/default/objects/Account/fields/GAM_Email__c.field-meta.xml
<CustomField>
        <fullName>GAM_Email__c</fullName>
        <label>GAM Email</label>
        <type>Email</type>
    </CustomField>

uipath-commons/main/default/objects/Account/fields/Overwrite_Classification__c.field-meta.xml
<CustomField>
        <fullName>Overwrite_Classification__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Used to exclude Classification field from being updated by the Account Segmentation process.</description>
        <label>Overwrite Classification</label>
        <type>Checkbox</type>
    </CustomField>

uipath-commons/main/default/objects/Account/recordTypes/Customer.recordType-meta.xml
<RecordType>
    <fullName>Customer</fullName>
    <active>true</active>
    <description>Customer account, i.e., account of a company with purchase transactions</description>
    <label>Customer</label>
</RecordType>

uipath-commons/main/default/objects/Account/recordTypes/Other.recordType-meta.xml
<RecordType>
    <fullName>Other</fullName>
    <active>false</active>
    <description>Non-Partner Account without past or existing UiPath Sales Opportunities</description>
    <label>Other</label>
</RecordType>

uipath-core/main/default/globalValueSets/Country_Global_List.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Afghanistan</fullName>
    </customValue>
    <customValue>
        <fullName>Aland Islands</fullName>
    </customValue>
    <customValue>
        <fullName>Albania</fullName>
    </customValue>
    <customValue>
        <fullName>Algeria</fullName>
    </customValue>
    <customValue>
        <fullName>Andorra</fullName>
    </customValue>
    <customValue>
        <fullName>Angola</fullName>
    </customValue>
    <customValue>
        <fullName>Anguilla</fullName>
    </customValue>
    <customValue>
        <fullName>Antarctica</fullName>
    </customValue>
    <customValue>
        <fullName>Antigua and Barbuda</fullName>
    </customValue>
    <customValue>
        <fullName>Argentina</fullName>
    </customValue>
    <customValue>
        <fullName>Armenia</fullName>
    </customValue>
    <customValue>
        <fullName>Aruba</fullName>
    </customValue>
    <customValue>
        <fullName>Australia</fullName>
    </customValue>
    <customValue>
        <fullName>Austria</fullName>
    </customValue>
    <customValue>
        <fullName>Azerbaijan</fullName>
    </customValue>
    <customValue>
        <fullName>Bahamas</fullName>
    </customValue>
    <customValue>
        <fullName>Bahrain</fullName>
    </customValue>
    <customValue>
        <fullName>Bangladesh</fullName>
    </customValue>
    <customValue>
        <fullName>Barbados</fullName>
    </customValue>
    <customValue>
        <fullName>Belarus</fullName>
    </customValue>
    <customValue>
        <fullName>Belgium</fullName>
    </customValue>
    <customValue>
        <fullName>Belize</fullName>
    </customValue>
    <customValue>
        <fullName>Benin</fullName>
    </customValue>
    <customValue>
        <fullName>Bermuda</fullName>
    </customValue>
    <customValue>
        <fullName>Bhutan</fullName>
    </customValue>
    <customValue>
        <fullName>Bolivia, Plurinational State of</fullName>
    </customValue>
    <customValue>
        <fullName>Bonaire, Sint Eustatius and Saba</fullName>
    </customValue>
    <customValue>
        <fullName>Bosnia and Herzegovina</fullName>
    </customValue>
    <customValue>
        <fullName>Botswana</fullName>
    </customValue>
    <customValue>
        <fullName>Bouvet Island</fullName>
    </customValue>
    <customValue>
        <fullName>United States</fullName>
    </customValue>
    <description>Created for the new Address object and will be used for other objects (involved in integration with NetSuite)</description>
    <masterLabel>Country Global List</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet>

uipath-commons/main/default/classes/AccountSetGAMEmailQueueableTest.cls
@isTest
public with sharing class AccountSetGAMEmailQueueableTest {
  @isTest
  public static void setupGAMEmailTest() {
    User u1 = new User(
      ProfileId = [SELECT Id FROM Profile WHERE Name = 'System Administrator']
      .Id,
      Username = 'testgamemailacc@testgam.com',
      LastName = 'TestUser',
      Email = 'testgamemailacc@testgam.com',
      Alias = 'tgame433',
      TimeZoneSidKey = 'America/Los_Angeles',
      LocaleSidKey = 'en_US',
      EmailEncodingKey = 'UTF-8',
      LanguageLocaleKey = 'en_US'
    );

    insert u1;

    Id customerRT = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('Customer').getRecordTypeId();

    Account topParentAcc = new Account();
    System.runAs(u1) {
      topParentAcc = new Account(
        Name = 'TopParentAccount',
        RecordTypeId = customerRT,
        AnnualRevenue = 150000000.00,
        Classification__c = 'General Business',
        Overwrite_Classification__c = false,
        Country__c = 'United States',
        BillingCountry = 'United States',
        Industry = 'Communications'
      );
      insert topParentAcc;
    }

    Account parentAccount = new Account(
      Name = 'ParentAccount',
      ParentId = topParentAcc.Id,
      RecordTypeId = customerRT,
      AnnualRevenue = 150000000.00,
      Classification__c = 'Global',
      Overwrite_Classification__c = false,
      Country__c = 'United States',
      BillingCountry = 'United States',
      Industry = 'Communications'
    );
    insert parentAccount;

    Account childAccount = new Account(
      Name = 'TestAccount',
      ParentId = parentAccount.Id,
      RecordTypeId = customerRT,
      AnnualRevenue = 5000000.00,
      Overwrite_Classification__c = false,
      Classification__c = 'Global',
      Country__c = 'United States',
      BillingCountry = 'United States',
      Industry = 'Telecommunications'
    );
    insert childAccount;

    AccountSetGAMEmailQueueable accSetGAMEmailQueueable = new AccountSetGAMEmailQueueable(
      new List<Account>{ childAccount },
      null
    );
    accSetGAMEmailQueueable.execute(null);

    List<Account> childAccountIns = [
      SELECT Id, Classification__c, GAM_Email__c
      FROM Account
      WHERE Classification__c = 'Global'
    ];
    System.assertEquals(2, childAccountIns.size());
    for (Account childacc : childAccountIns)
      System.assertEquals('testgamemailacc@testgam.com', childacc.GAM_Email__c);
  }

  @isTest
  public static void setupGAMEmail_Classification_Test() {
    User u1 = new User(
      ProfileId = [SELECT Id FROM Profile WHERE Name = 'System Administrator']
      .Id,
      Username = 'testgamemailacc@testgam.com',
      LastName = 'TestUser',
      Email = 'testgamemailacc@testgam.com',
      Alias = 'tgame433',
      TimeZoneSidKey = 'America/Los_Angeles',
      LocaleSidKey = 'en_US',
      EmailEncodingKey = 'UTF-8',
      LanguageLocaleKey = 'en_US'
    );

    insert u1;

    Id customerRT = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('Customer').getRecordTypeId();

    Account topParentAcc = new Account();
    System.runAs(u1) {
      topParentAcc = new Account(
        Name = 'TopParentAccount',
        RecordTypeId = customerRT,
        AnnualRevenue = 150000000.00,
        Classification__c = 'General Business',
        Country__c = 'United States',
        BillingCountry = 'United States',
        Overwrite_Classification__c = false,
        Industry = 'Communications'
      );
      insert topParentAcc;
    }

    Account parentAccount = new Account(
      Name = 'ParentAccount',
      ParentId = topParentAcc.Id,
      RecordTypeId = customerRT,
      AnnualRevenue = 150000000.00,
      Classification__c = 'Global',
      Country__c = 'United States',
      BillingCountry = 'United States',
      Overwrite_Classification__c = false,
      Industry = 'Communications'
    );
    insert parentAccount;

    Account childAccount = new Account(
      Name = 'TestAccount',
      ParentId = parentAccount.Id,
      RecordTypeId = customerRT,
      AnnualRevenue = 5000000.00,
      Classification__c = 'Global',
      Country__c = 'United States',
      BillingCountry = 'United States',
      Industry = 'Telecommunications',
      Overwrite_Classification__c = false
    );
    insert childAccount;

    Account newAcc = parentAccount.clone();
    newAcc.Id = parentAccount.Id;
    newAcc.Classification__c = 'Velocity';
    update newAcc;

    AccountSetGAMEmailQueueable accSetGAMEmailQueueable = new AccountSetGAMEmailQueueable(
      new List<Account>{ newAcc },
      new Map<Id, SObject>{ parentAccount.Id => parentAccount }
    );
    accSetGAMEmailQueueable.execute(null);

    Account nonGlobalClasificationAcc = [
      SELECT Id, Classification__c, GAM_Email__c
      FROM Account
      WHERE Id = :parentAccount.Id
      LIMIT 1
    ];
    //TODO: conflict with other code in org
    //System.assertEquals(null, nonGlobalClasificationAcc.GAM_Email__c);
  }

  @isTest
  public static void setupGAMEmail_owner_Test() {
    Id profileId = [SELECT Id FROM Profile WHERE Name = 'System Administrator'].Id;
    User u1 = new User(
      ProfileId = profileId,
      Username = 'testgamemailacc@testgam.com',
      LastName = 'TestUser',
      Email = 'testgamemailacc@testgam.com',
      Alias = 'tgame433',
      TimeZoneSidKey = 'America/Los_Angeles',
      LocaleSidKey = 'en_US',
      EmailEncodingKey = 'UTF-8',
      LanguageLocaleKey = 'en_US'
    );

    insert u1;

    User u2 = new User(
      ProfileId = profileId,
      Username = 'testgamemailacc2@testgam.com',
      LastName = 'TestUser2',
      Email = 'testgamemailacc2@testgam.com',
      Alias = 'tgame422',
      TimeZoneSidKey = 'America/Los_Angeles',
      LocaleSidKey = 'en_US',
      EmailEncodingKey = 'UTF-8',
      LanguageLocaleKey = 'en_US'
    );

    insert u2;

    Id customerRT = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('Customer').getRecordTypeId();

    Account topParentAcc = new Account();
    System.runAs(u1) {
      topParentAcc = new Account(
        Name = 'TopParentAccount',
        RecordTypeId = customerRT,
        AnnualRevenue = 150000000.00,
        Classification__c = 'General Business',
        Overwrite_Classification__c = false,
        Country__c = 'United States',
        BillingCountry = 'United States',
        Industry = 'Communications'
      );
      insert topParentAcc;
    }

    Account parentAccount = new Account(
      Name = 'ParentAccount',
      ParentId = topParentAcc.Id,
      RecordTypeId = customerRT,
      AnnualRevenue = 150000000.00,
      Classification__c = 'Global',
      Country__c = 'United States',
      BillingCountry = 'United States',
      Overwrite_Classification__c = false,
      Industry = 'Communications'
    );
    insert parentAccount;

    Account childAccount = new Account(
      Name = 'TestAccount',
      ParentId = parentAccount.Id,
      RecordTypeId = customerRT,
      AnnualRevenue = 5000000.00,
      Overwrite_Classification__c = false,
      Classification__c = 'Global',
      Country__c = 'United States',
      BillingCountry = 'United States',
      Industry = 'Telecommunications'
    );
    insert childAccount;

    Account newAcc = topParentAcc.clone();
    newAcc.Id = topParentAcc.Id;
    newAcc.OwnerId = u2.Id;
    update newAcc;

    AccountSetGAMEmailQueueable accSetGAMEmailQueueable = new AccountSetGAMEmailQueueable(
      new List<Account>{ newAcc },
      new Map<Id, SObject>{ topParentAcc.Id => topParentAcc }
    );
    accSetGAMEmailQueueable.execute(null);

    List<Account> childAccountIns = [
      SELECT Id, Classification__c, GAM_Email__c
      FROM Account
      WHERE Classification__c = 'Global'
    ];
    System.assertEquals(2, childAccountIns.size());
    for (Account childacc : childAccountIns)
      System.assertEquals('testgamemailacc2@testgam.com', childacc.GAM_Email__c);
  }
}