uipath-commons/main/default/objects/Account/fields/Classification__c.field-meta.xml
<CustomField>
    <fullName>Classification__c</fullName>
    <label>Classification</label>
    
        <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Others</fullName>
            </value>
            <value>
                <fullName>Diamond</fullName>
            </value>
            <value>
                <fullName>Gold</fullName>
            </value>
            <value>
                <fullName>Silver</fullName>
            </value>
            <value>
                <fullName>Global</fullName>
            </value>
            <value>
                <fullName>Enterprise</fullName>
            </value>
            <value>
                <fullName>Commercial</fullName>
            </value>
            <value>
                <fullName>SMB</fullName>
            </value>
            <value>
                <fullName>Velocity</fullName>
            </value>
            <value>
                <fullName>General Business</fullName>
            </value>
            <value>
                <fullName>Inside Sales</fullName>
            </value>
            <value>
                <fullName>Global - Strategic</fullName>
                <isActive>false</isActive>
                <label>Global - Strategic</label>
            </value>
            <value>
                <fullName>Growth</fullName>
                <isActive>false</isActive>
                <label>Growth</label>
            </value>
            <value>
                <fullName>Key</fullName>
                <isActive>false</isActive>
                <label>Key</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

uipath-commons/main/default/objects/Account/fields/Overwrite_Classification__c.field-meta.xml
<CustomField>
        <fullName>Overwrite_Classification__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Used to exclude Classification field from being updated by the Account Segmentation process.</description>
        <label>Overwrite Classification</label>
        <type>Checkbox</type>
    </CustomField>

uipath-commons/main/default/classes/AccountSetClassificationGlobalFunction.cls
/**
 * Sets Classification to "Global" if Parent Account Classification is "Global" on insert
 */
public with sharing class AccountSetClassificationGlobalFunction implements SObjectToSObjectFunction {
  private Map<Id, Account> parentAccounts;

  public AccountSetClassificationGlobalFunction(List<Account> accounts) {
    Set<Id> parentIds = new Set<Id>();
    for (Account acc : accounts) {
      parentIds.add(acc.ParentId);
    }
    system.debug('parentIds ======> ' + parentIds);
    parentAccounts = new Map<Id, Account>(
      [SELECT Id, Classification__c FROM Account WHERE Id IN :parentIds AND Classification__c = 'Global']
    );
  }

  public SObject apply(Account acc) {
    if (parentAccounts.containsKey(acc.ParentId)) {
      acc.Classification__c = 'Global';
      acc.Overwrite_Classification__c = true;
    } else {
      acc.Classification__c = '';
      acc.Overwrite_Classification__c = false;
    }
    return acc;
  }

  public SObject apply(SObject record) {
    return apply((Account) record);
  }

  public static void deriveRecordTypeOnInsert(List<Account> records) {
    Collection.of(records)
      .mapSome(Match.field(Account.ParentId).hasValue(), new AccountSetClassificationGlobalFunction(records));
  }

  public static void deriveRecordTypeOnUpdate(List<Account> accounts, Map<Id, SObject> existingAccounts) {
    SObjectPredicate hasChanged = new HasRecordChanged(
      new Set<SObjectField>{ Account.ParentId },
      accounts,
      existingAccounts
    );

    List<Account> changedAccounts = Collection.of(accounts)
      .filter(hasChanged)
      .filter(
        Match.field(Account.RecordTypeId)
          .isIn(
            new Set<String>{
              AccountMetadata.customerRecordType,
              AccountMetadata.customerProspectRecordType,
              AccountMetadata.ProspectRecordType,
              null
            }
          )
      )
      .asList();

    if (!changedAccounts.isEmpty()) {
      system.debug('changedAccounts ======> ' + changedAccounts);
      Collection.of(changedAccounts).mapAll(new AccountSetClassificationGlobalFunction(changedAccounts));
    }
  }
}