uipath-commons/main/default/objects/Account/fields/Classification__c.field-meta.xml
<CustomField>
    <fullName>Classification__c</fullName>
    <label>Classification</label>
    
        <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Others</fullName>
            </value>
            <value>
                <fullName>Diamond</fullName>
            </value>
            <value>
                <fullName>Gold</fullName>
            </value>
            <value>
                <fullName>Silver</fullName>
            </value>
            <value>
                <fullName>Global</fullName>
            </value>
            <value>
                <fullName>Enterprise</fullName>
            </value>
            <value>
                <fullName>Commercial</fullName>
            </value>
            <value>
                <fullName>SMB</fullName>
            </value>
            <value>
                <fullName>Velocity</fullName>
            </value>
            <value>
                <fullName>General Business</fullName>
            </value>
            <value>
                <fullName>Inside Sales</fullName>
            </value>
            <value>
                <fullName>Global - Strategic</fullName>
                <isActive>false</isActive>
                <label>Global - Strategic</label>
            </value>
            <value>
                <fullName>Growth</fullName>
                <isActive>false</isActive>
                <label>Growth</label>
            </value>
            <value>
                <fullName>Key</fullName>
                <isActive>false</isActive>
                <label>Key</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

uipath-commons/main/default/objects/Account/fields/Geo__c.field-meta.xml
<CustomField>
        <fullName>Geo__c</fullName>
        <label>Geo</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>AMER</fullName>
                </value>
                <value>
                    <fullName>APAC</fullName>
                </value>
                <value>
                    <fullName>EMEA</fullName>
                </value>
                <value>
                    <fullName>Japan</fullName>
                </value>
                <value>
                    <fullName>India</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </CustomField>

uipath-commons/main/default/objects/Account/fields/Overwrite_Classification__c.field-meta.xml
<CustomField>
        <fullName>Overwrite_Classification__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Used to exclude Classification field from being updated by the Account Segmentation process.</description>
        <label>Overwrite Classification</label>
        <type>Checkbox</type>
    </CustomField>

uipath-commons/main/default/objects/Account/fields/Parent_Account_Classification__c.field-meta.xml
<CustomField>
    <fullName>Parent_Account_Classification__c</fullName>
    <formula>IF(NOT(ISBLANK(text(Parent.Parent.Parent.Parent.Parent.Classification__c))), text(Parent.Classification__c), 
IF(NOT(ISBLANK(text(Parent.Parent.Parent.Parent.Classification__c))), text(Parent.Classification__c), 
IF(NOT(ISBLANK(text(Parent.Parent.Parent.Classification__c))), text(Parent.Classification__c), 
IF(NOT(ISBLANK(text(Parent.Parent.Classification__c))), text(Parent.Classification__c), 
IF(NOT(ISBLANK(text(Parent.Classification__c))),text(Parent.Classification__c), 
null)))))</formula>
    <label>Parent Account Classification</label>
    <type>Text</type>
</CustomField>

uipath-commons/main/default/objects/Account/fields/Region__c.field-meta.xml
<CustomField>
    <fullName>Region__c</fullName>
    <label>Region</label>
    
        <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>ANZ</fullName>
            </value>
            <value>
                <fullName>BFS</fullName>
            </value>
            <value>
                <fullName>Canada</fullName>
            </value>
            <value>
                <fullName>Greater China</fullName>
            </value>
            <value>
                <fullName>GOV</fullName>
            </value>
            <value>
                <fullName>India</fullName>
            </value>
            <value>
                <fullName>Korea</fullName>
            </value>
            <value>
                <fullName>LATAM</fullName>
            </value>
            <value>
                <fullName>MEA</fullName>
            </value>
            <value>
                <fullName>Nordics</fullName>
            </value>
            <value>
                <fullName>NorthCentral</fullName>
            </value>
            <value>
                <fullName>NorthEast</fullName>
            </value>
            <value>
                <fullName>NorthWest</fullName>
            </value>
            <value>
                <fullName>Others</fullName>
            </value>
            <value>
                <fullName>SEA</fullName>
            </value>
            <value>
                <fullName>SouthWest</fullName>
            </value>
            <value>
                <fullName>SouthCentral</fullName>
            </value>
            <value>
                <fullName>SouthEast</fullName>
            </value>
            <value>
                <fullName>UKI</fullName>
            </value>
            <value>
                <fullName>CE</fullName>
            </value>
            <value>
                <fullName>EECIS</fullName>
            </value>
            <value>
                <fullName>France</fullName>
            </value>
            <value>
                <fullName>Italy/Greece</fullName>
            </value>
            <value>
                <fullName>Iberia</fullName>
            </value>
            <value>
                <fullName>Benelux</fullName>
            </value>
            <value>
                <fullName>Japan</fullName>
            </value>
            <value>
                <fullName>Hokkaido</fullName>
            </value>
            <value>
                <fullName>Tohoku</fullName>
            </value>
            <value>
                <fullName>Kanto</fullName>
            </value>
            <value>
                <fullName>Chubu</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

uipath-commons/main/default/objects/Account/recordTypes/Customer.recordType-meta.xml
<RecordType>
    <fullName>Customer</fullName>
    <active>true</active>
    <description>Customer account, i.e., account of a company with purchase transactions</description>
    <label>Customer</label>
</RecordType>

uipath-commons/main/default/objects/Account/recordTypes/Customer_Prospect.recordType-meta.xml
<RecordType>
        <fullName>Customer_Prospect</fullName>
        <active>true</active>
        <label>Customer Prospect</label>
      
       
      
       
      
    </RecordType>

uipath-commons/main/default/objects/Account/recordTypes/Partner.recordType-meta.xml
<RecordType>
    <fullName>Partner</fullName>
    <active>true</active>
    <description>UiPath prospective or existing Partner Account</description>
    <label>Partner</label>
</RecordType>

uipath-commons/main/default/objects/Account/recordTypes/Partner_Prospect.recordType-meta.xml
<RecordType>
    <fullName>Partner_Prospect</fullName>
    <active>true</active>
    <label>Partner Prospect</label>
</RecordType>

uipath-commons/main/default/objects/Account/recordTypes/Prospect.recordType-meta.xml
<RecordType>
        <fullName>Prospect</fullName>
        <active>true</active>
        <description
  >Non-Customer and non-Partner Account with past or existing UiPath Sales Opportunities</description>
        <label>Prospect</label>
 
        
  
       
      
    </RecordType>

uipath-commons/main/default/classes/AccountSetClassificationFunction.cls
public with sharing class AccountSetClassificationFunction implements SObjectToSObjectFunction {
  private static Id customerRT = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName()
    .get('Customer')
    .getRecordTypeId();
  private static Id customerProspectRT = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName()
    .get('Customer_Prospect')
    .getRecordTypeId();
  private static Id partnerRT = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName()
    .get('Partner')
    .getRecordTypeId();
  private static Id partnerProspectRT = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName()
    .get('Partner_Prospect')
    .getRecordTypeId();
  private static Id prospectRT = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName()
    .get('Prospect')
    .getRecordTypeId();

  /**
   * Set classification field on account
   * *ProcessBuilder clean-up:  Account Segmentation - Update Classification
   */
  public SObject apply(Account acc) {
    if (
      acc.RecordTypeId == customerRT ||
      acc.RecordTypeId == customerProspectRT ||
      acc.RecordTypeId == partnerRT ||
      acc.RecordTypeId == partnerProspectRT ||
      acc.RecordTypeId == prospectRT
    ) {
      // AMER
      if (acc.Geo__c == 'AMER') {
        processAMERAccount(acc);
      } else if (acc.Geo__c == 'EMEA') {
        // EMEA
        processEMEAAccount(acc);
      } else if (acc.Geo__c == 'India') {
        // India
        processIndiaAccount(acc);
      } else if (acc.Geo__c == 'APAC') {
        // APAC
        processAPACAccount(acc);
      }
    }

    return acc;
  }

  public SObject apply(SObject record) {
    return apply((Account) record);
  }

  private static void processAMERAccount(Account acc) {
    // AMER (wo Canada & LATAM) - ENTERPRISE
    if (
      acc.Region__c != 'Canada' &&
      acc.Region__c != 'LATAM' &&
      acc.AnnualRevenue >= 1000000000.00 &&
      acc.Overwrite_Classification__c == false &&
      acc.Parent_Account_Classification__c != 'Global'
    ) {
      acc.Classification__c = 'Enterprise';
    } else if (
      acc.Region__c != 'Canada' &&
      acc.Region__c != 'LATAM' &&
      acc.AnnualRevenue < 1000000000.00 &&
      acc.Overwrite_Classification__c == false &&
      acc.Parent_Account_Classification__c != 'Global'
    ) {
      // AMER (wo Canada & LATAM) - Velocity
      acc.Classification__c = 'Velocity';
    } else if (
      acc.Region__c == 'Canada' &&
      acc.AnnualRevenue >= 200000000.00 &&
      acc.Overwrite_Classification__c == false &&
      acc.Parent_Account_Classification__c != 'Global'
    ) {
      // AMER (Canada) - Enterprise
      acc.Classification__c = 'Enterprise';
    } else if (
      acc.Region__c == 'Canada' &&
      acc.AnnualRevenue < 200000000.00 &&
      acc.Overwrite_Classification__c == false &&
      acc.Parent_Account_Classification__c != 'Global'
    ) {
      // AMER (Canada) - Velocity
      acc.Classification__c = 'Velocity';
    } else if (
      acc.Region__c == 'LATAM' &&
      acc.AnnualRevenue >= 150000000.00 &&
      acc.Overwrite_Classification__c == false &&
      acc.Parent_Account_Classification__c != 'Global'
    ) {
      // AMER (LATAM) - Enterprise
      acc.Classification__c = 'Enterprise';
    } else if (
      acc.Region__c == 'LATAM' &&
      acc.AnnualRevenue < 150000000.00 &&
      acc.Overwrite_Classification__c == false &&
      acc.Parent_Account_Classification__c != 'Global'
    ) {
      // AMER (LATAM) - Velocity
      acc.Classification__c = 'Velocity';
    }
  }

  private static void processEMEAAccount(Account acc) {
    // EMEA - Enterprise
    if (
      acc.AnnualRevenue >= 1000000000.00 &&
      acc.Overwrite_Classification__c == false &&
      acc.Parent_Account_Classification__c != 'Global'
    ) {
      acc.Classification__c = 'Enterprise';
    } else if (
      acc.AnnualRevenue >= 250000000.00 &&
      acc.AnnualRevenue < 1000000000.00 &&
      acc.Overwrite_Classification__c == false &&
      acc.Parent_Account_Classification__c != 'Global'
    ) {
      // EMEA - Commercial
      acc.Classification__c = 'Commercial';
    } else if (
      acc.AnnualRevenue < 250000000.00 &&
      acc.Overwrite_Classification__c == false &&
      acc.Parent_Account_Classification__c != 'Global'
    ) {
      // EMEA - SMB
      acc.Classification__c = 'SMB';
    }
  }

  private static void processIndiaAccount(Account acc) {
    // INDIA - Commercial
    if (
      acc.Overwrite_Classification__c == false &&
      acc.Classification__c != 'Global' &&
      acc.Parent_Account_Classification__c != 'Global'
    ) {
      acc.Classification__c = 'Commercial';
    }
  }

  private static void processAPACAccount(Account acc) {
    // APAC - Enterprise
    if (
      acc.AnnualRevenue >= 1000000000.00 &&
      acc.Overwrite_Classification__c == false &&
      acc.Parent_Account_Classification__c != 'Global'
    ) {
      acc.Classification__c = 'Enterprise';
    } else if (
      acc.AnnualRevenue >= 250000000.00 &&
      acc.AnnualRevenue < 1000000000.00 &&
      acc.Overwrite_Classification__c == false &&
      acc.Parent_Account_Classification__c != 'Global'
    ) {
      // APAC - Commercial
      acc.Classification__c = 'Commercial';
    } else if (
      acc.AnnualRevenue < 250000000.00 &&
      acc.Overwrite_Classification__c == false &&
      acc.Parent_Account_Classification__c != 'Global'
    ) {
      // APAC - SMB
      acc.Classification__c = 'SMB';
    }
  }
}