uipath-commons/main/default/objects/Account/fields/Classification__c.field-meta.xml
<CustomField>
    <fullName>Classification__c</fullName>
    <label>Classification</label>
    
        <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Others</fullName>
            </value>
            <value>
                <fullName>Diamond</fullName>
            </value>
            <value>
                <fullName>Gold</fullName>
            </value>
            <value>
                <fullName>Silver</fullName>
            </value>
            <value>
                <fullName>Global</fullName>
            </value>
            <value>
                <fullName>Enterprise</fullName>
            </value>
            <value>
                <fullName>Commercial</fullName>
            </value>
            <value>
                <fullName>SMB</fullName>
            </value>
            <value>
                <fullName>Velocity</fullName>
            </value>
            <value>
                <fullName>General Business</fullName>
            </value>
            <value>
                <fullName>Inside Sales</fullName>
            </value>
            <value>
                <fullName>Global - Strategic</fullName>
                <isActive>false</isActive>
                <label>Global - Strategic</label>
            </value>
            <value>
                <fullName>Growth</fullName>
                <isActive>false</isActive>
                <label>Growth</label>
            </value>
            <value>
                <fullName>Key</fullName>
                <isActive>false</isActive>
                <label>Key</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

uipath-commons/main/default/objects/Account/fields/Company_Tier__c.field-meta.xml
<CustomField>
    <fullName>Company_Tier__c</fullName>
    <label>Company Tier</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>A</fullName>
            </value>
            <value>
                <fullName>B</fullName>
            </value>
            <value>
                <fullName>C</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

uipath-commons/main/default/objects/Account/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <description>This required field will be used to capture the country on the creation of a new account. It will populate the country on the new address records for accounts. The standard billing and shipping address fields on account will be made read only.</description>
    <label>Country</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Country_Global_List</valueSetName>
    </valueSet>
</CustomField>

uipath-commons/main/default/objects/Account/fields/Email_Domain__c.field-meta.xml
<CustomField>
        <fullName>Email_Domain__c</fullName>
        <label>Email Domain</label>
        <length>255</length>
        <type>Text</type>
    </CustomField>

uipath-commons/main/default/objects/Account/fields/Geo__c.field-meta.xml
<CustomField>
        <fullName>Geo__c</fullName>
        <label>Geo</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>AMER</fullName>
                </value>
                <value>
                    <fullName>APAC</fullName>
                </value>
                <value>
                    <fullName>EMEA</fullName>
                </value>
                <value>
                    <fullName>Japan</fullName>
                </value>
                <value>
                    <fullName>India</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </CustomField>

uipath-commons/main/default/objects/Account/fields/Overwrite_Classification__c.field-meta.xml
<CustomField>
        <fullName>Overwrite_Classification__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Used to exclude Classification field from being updated by the Account Segmentation process.</description>
        <label>Overwrite Classification</label>
        <type>Checkbox</type>
    </CustomField>

uipath-commons/main/default/objects/Account/fields/Region_Specific__c.field-meta.xml
<CustomField>
        <fullName>Region_Specific__c</fullName>
        <label>Region Specific</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Enterprise Tier 1</fullName>
                </value>
                <value>
                    <fullName>Enterprise Tier 2</fullName>
                </value>
                <value>
                    <fullName>Enterprise Tier 3</fullName>
                </value>
                <value>
                    <fullName>Velocity Tier 1</fullName>
                </value>
                <value>
                    <fullName>Velocity Tier 2</fullName>
                </value>
                <value>
                    <fullName>Velocity Tier 3</fullName>
                </value>
                <value>
                    <fullName>BPO Accounts</fullName>
                </value>
                <value>
                    <fullName>India Business</fullName>
                </value>
                <value>
                    <fullName>Government</fullName>
                </value>
                <value>
                    <fullName>SOE</fullName>
                </value>
                <value>
                    <fullName>MNC</fullName>
                </value>
                <value>
                    <fullName>Commercial</fullName>
                </value>
                <value>
                    <fullName>Private</fullName>
                </value>
                <value>
                    <fullName>Joint Venture</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </CustomField>

uipath-commons/main/default/objects/Account/fields/UiPath_Program__c.field-meta.xml
<CustomField>
        <fullName>UiPath_Program__c</fullName>
        <description>GLAS Program - Account Identification Field</description>
        <label>UiPath Program</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>GOV</fullName>
                </value>
                <value>
                    <fullName>EAP</fullName>
                </value>
                <value>
                    <fullName>Strategic AMER</fullName>
                </value>
                <value>
                    <fullName>Strategic APAC</fullName>
                </value>
                <value>
                    <fullName>FED</fullName>
                    <isActive>false</isActive>
                    <label>FED</label>
                </value>
                <value>
                    <fullName>None</fullName>
                    <isActive>false</isActive>
                    <label>None</label>
                </value>
                <value>
                    <fullName>Strategic</fullName>
                    <isActive>false</isActive>
                    <label>Strategic</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </CustomField>

uipath-commons/main/default/objects/Account/fields/Ultimate_Parent_Classification__c.field-meta.xml
<CustomField>
        <fullName>Ultimate_Parent_Classification__c</fullName>
        <formula>IF(NOT(ISBLANK(Parent.Parent.Parent.Parent.Parent.Id)), Parent.Parent.Parent.Parent.Parent.Classification2__c ,
IF(NOT(ISBLANK(Parent.Parent.Parent.Parent.Id)), Parent.Parent.Parent.Parent.Classification2__c ,
IF(NOT(ISBLANK(Parent.Parent.Parent.Id)), Parent.Parent.Parent.Classification2__c  ,
IF(NOT(ISBLANK(Parent.Parent.Id)), Parent.Parent.Classification2__c ,
IF(NOT(ISBLANK(Parent.Id)),Parent.Classification2__c ,
Classification2__c  )))))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Ultimate Parent Classification</label>
        <type>Text</type>
    </CustomField>

uipath-commons/main/default/objects/Account/recordTypes/Prospect.recordType-meta.xml
<RecordType>
        <fullName>Prospect</fullName>
        <active>true</active>
        <description
  >Non-Customer and non-Partner Account with past or existing UiPath Sales Opportunities</description>
        <label>Prospect</label>
 
        
  
       
      
    </RecordType>

uipath-commons/main/default/classes/AccountSetCompanyTierQueueableTest.cls
@isTest
private class AccountSetCompanyTierQueueableTest {
  private static final string AccountEMEA = 'Test Account EMEA';
  private static final string AccountAMER = 'Test Account AMER';
  private static final string AccountAPAC = 'Test Account APAC';
  private static final string AccountIndia = 'Test Account India';
  private static final string AccountJapan = 'Test Account Japan';
  private static final string NewZealand = 'New Zealand';

  @isTest
  private static void setUpCompanyTierInsert1Test() {
    Id prospectRT = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('Prospect').getRecordTypeId();

    Account accEMEA = new Account(
      Name = AccountEMEA,
      RecordTypeId = prospectRT,
      Country__c = 'Romania',
      Geo__c = 'EMEA',
      BillingCountry = 'Romania',
      Classification__c = 'SMB',
      AnnualRevenue = 100000,
      Industry = 'Energy',
      Overwrite_Classification__c = true
    );
    insert accEMEA;

    AccountSetCompanyTierQueueable accountSetCompanyTierQueueable = new AccountSetCompanyTierQueueable(
      new List<Account>{ accEMEA },
      null,
      null
    );
    accountSetCompanyTierQueueable.execute(null);
    Account insertedAcc = [SELECT Id, Company_Tier__c FROM Account WHERE Id = :accEMEA.Id];

    System.assertEquals('A', insertedAcc.Company_Tier__c);
  }

  @isTest
  private static void setUpCompanyTierInsert2Test() {
    Id prospectRT = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('Prospect').getRecordTypeId();

    Account enterpriseParentAcc = new Account(
      Name = 'Parent Account 1',
      RecordTypeId = prospectRT,
      Country__c = 'France',
      Industry = 'Energy',
      Classification__c = 'SMB',
      Overwrite_Classification__c = true
    );
    insert enterpriseParentAcc;

    Account velocityParentAcc = new Account(
      Name = 'Parent Account 2',
      RecordTypeId = prospectRT,
      Country__c = 'Italy',
      Industry = 'Construction',
      Classification__c = 'Velocity',
      Overwrite_Classification__c = true
    );
    insert velocityParentAcc;

    Account sMBParentAcc = new Account(
      Name = 'Parent Account 3',
      RecordTypeId = prospectRT,
      Country__c = 'Germany',
      Industry = 'Communications',
      Classification__c = 'SMB',
      Overwrite_Classification__c = true
    );
    insert sMBParentAcc;

    List<Account> accToInsert = new List<Account>();

    Account accEMEAt1 = new Account(
      Name = AccountEMEA,
      RecordTypeId = prospectRT,
      ParentId = sMBParentAcc.Id,
      Country__c = 'Romania',
      Geo__c = 'EMEA',
      Classification__c = 'SMB',
      Industry = 'Energy',
      Overwrite_Classification__c = true
    );
    accToInsert.add(accEMEAt1);

    Account accAMERt1 = new Account(
      Name = AccountAMER,
      RecordTypeId = prospectRT,
      ParentId = velocityParentAcc.Id,
      Country__c = 'Canada',
      Geo__c = 'AMER',
      BillingCountry = 'Canada',
      Classification__c = 'Enterprise',
      AnnualRevenue = 300000000.00,
      Industry = 'Energy',
      Overwrite_Classification__c = true,
      Region_Specific__c = 'Velocity Tier 1'
    );
    accToInsert.add(accAMERt1);

    Account accIndiat1 = new Account(
      Name = AccountIndia,
      RecordTypeId = prospectRT,
      ParentId = velocityParentAcc.Id,
      Country__c = 'India',
      Geo__c = 'India',
      BillingCountry = 'India',
      Classification__c = 'Commercial',
      AnnualRevenue = 300000000.00,
      Industry = 'Energy',
      Overwrite_Classification__c = true,
      Region_Specific__c = 'BPO Accounts'
    );
    accToInsert.add(accIndiat1);

    Account accJapant1 = new Account(
      Name = AccountJapan,
      RecordTypeId = prospectRT,
      Country__c = 'Japan',
      Geo__c = 'Japan',
      BillingCountry = 'Japan',
      Classification__c = 'Commercial',
      AnnualRevenue = 100000.00,
      Industry = 'Energy',
      Overwrite_Classification__c = true
    );
    accToInsert.add(accJapant1);

    Account accAPACt1 = new Account(
      Name = AccountAPAC,
      RecordTypeId = prospectRT,
      ParentId = sMBParentAcc.Id,
      Country__c = NewZealand,
      Geo__c = 'APAC',
      BillingCountry = NewZealand,
      Classification__c = 'Commercial',
      AnnualRevenue = 30000.00,
      Industry = 'Energy',
      Overwrite_Classification__c = true
    );
    accToInsert.add(accAPACt1);

    insert accToInsert;

    AccountSetCompanyTierQueueable accountSetCompanyTierQueueable = new AccountSetCompanyTierQueueable(
      accToInsert,
      null,
      null
    );
    accountSetCompanyTierQueueable.execute(null);

    List<Account> allAccs = [SELECT Id, Name, Company_Tier__c FROM Account];
    for (Account acc : allAccs) {
      if (acc.Name == AccountAMER) {
        System.assertEquals('B', acc.Company_Tier__c);
      }
      if (acc.Name == AccountIndia) {
        System.assertEquals('B', acc.Company_Tier__c);
      }
      if (acc.Name == AccountAPAC) {
        System.assertEquals('C', acc.Company_Tier__c);
      }
      if (acc.Name == AccountEMEA) {
        System.assertEquals('C', acc.Company_Tier__c);
      }
      if (acc.Name == AccountJapan) {
        System.assertEquals('A', acc.Company_Tier__c);
      }
    }
  }

  @isTest
  private static void setUpCompanyTierUpdateTest() {
    Id prospectRT = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('Prospect').getRecordTypeId();

    Account parentAccEnterprise = new Account(
      Name = 'Parent Account Enterprise',
      RecordTypeId = prospectRT,
      Country__c = 'France',
      Industry = 'Energy',
      Classification__c = 'Enterprise',
      Overwrite_Classification__c = true
    );
    insert parentAccEnterprise;

    Account parentAccVelocity = new Account(
      Name = 'Parent Account Velocity',
      RecordTypeId = prospectRT,
      Country__c = 'France',
      Industry = 'Energy',
      Classification__c = 'Velocity',
      Overwrite_Classification__c = true
    );
    insert parentAccVelocity;

    Account parentAccSMB = new Account(
      Name = 'Parent Account SMB',
      RecordTypeId = prospectRT,
      Country__c = 'France',
      Industry = 'Energy',
      Classification__c = 'SMB',
      Overwrite_Classification__c = true
    );
    insert parentAccSMB;

    Account parentAccGold = new Account(
      Name = 'Parent Account Gold',
      RecordTypeId = prospectRT,
      Country__c = 'France',
      Industry = 'Energy',
      Classification__c = 'Gold',
      Overwrite_Classification__c = true
    );
    insert parentAccGold;

    List<Account> oldaccToUpdate = new List<Account>();
    List<Account> accToUpdate = new List<Account>();

    Account oldaccEMEA = new Account(
      Name = AccountEMEA,
      RecordTypeId = prospectRT,
      ParentId = parentAccGold.Id,
      Country__c = 'Romania',
      Geo__c = 'EMEA',
      BillingCountry = 'Romania',
      Classification__c = 'SMB',
      AnnualRevenue = 100000,
      Industry = 'Energy',
      Overwrite_Classification__c = true
    );
    oldaccToUpdate.add(oldaccEMEA);

    Account oldaccAMER = new Account(
      Name = AccountAMER,
      RecordTypeId = prospectRT,
      ParentId = parentAccVelocity.Id,
      Country__c = 'Canada',
      Geo__c = 'AMER',
      BillingCountry = 'Canada',
      Classification__c = 'Enterprise',
      AnnualRevenue = 300000000.00,
      Industry = 'Energy',
      Overwrite_Classification__c = true,
      Region_Specific__c = 'Velocity Tier 1'
    );
    oldaccToUpdate.add(oldaccAMER);

    Account oldaccIndia = new Account(
      Name = AccountIndia,
      RecordTypeId = prospectRT,
      ParentId = parentAccVelocity.Id,
      Country__c = 'India',
      Geo__c = 'India',
      BillingCountry = 'India',
      Classification__c = 'Commercial',
      AnnualRevenue = 300000000.00,
      Industry = 'Energy',
      Overwrite_Classification__c = true,
      Region_Specific__c = 'BPO Accounts'
    );
    oldaccToUpdate.add(oldaccIndia);

    Account oldaccJapan = new Account(
      Name = AccountJapan,
      RecordTypeId = prospectRT,
      ParentId = parentAccSMB.Id,
      Country__c = 'Japan',
      Geo__c = 'Japan',
      BillingCountry = 'Japan',
      Classification__c = 'Commercial',
      Overwrite_Classification__c = true,
      Industry = 'Communications'
    );
    oldaccToUpdate.add(oldaccJapan);

    Account oldaccAPAC = new Account(
      Name = AccountAPAC,
      RecordTypeId = prospectRT,
      ParentId = parentAccSMB.Id,
      Country__c = NewZealand,
      Geo__c = 'APAC',
      BillingCountry = NewZealand,
      Classification__c = 'Commercial',
      AnnualRevenue = 30000.00,
      Industry = 'Energy',
      Overwrite_Classification__c = true
    );
    oldaccToUpdate.add(oldaccAPAC);

    insert oldaccToUpdate;

    Map<Id, Account> oldAccounts = new Map<Id, Account>(
      [
        SELECT
          Id,
          Name,
          ParentId,
          Geo__c,
          Classification__c,
          UiPath_Program__c,
          Region_Specific__c,
          Industry,
          Company_Tier__c,
          Email_Domain__c,
          Ultimate_Parent_Classification__c
        FROM Account
        WHERE Id IN :oldaccToUpdate
      ]
    );

    Account newAccEMEA = oldaccEMEA.clone();
    newAccEMEA.Id = oldaccEMEA.Id;
    newAccEMEA.Classification__c = 'Commercial';
    accToUpdate.add(newAccEMEA);

    Account newAccAMER = oldaccAMER.clone();
    newAccAMER.Id = oldaccAMER.Id;
    newAccAMER.ParentId = null;
    accToUpdate.add(newAccAMER);

    Account newAccIndia = oldaccIndia.clone();
    newAccIndia.Id = oldaccIndia.Id;
    newAccIndia.Classification__c = 'Enterprise';
    accToUpdate.add(newAccIndia);

    Account newAccAPAC = oldaccAPAC.clone();
    newAccAPAC.Id = oldaccAPAC.Id;
    newAccAPAC.Classification__c = 'SMB';
    accToUpdate.add(newAccAPAC);

    Account newAccJapan = oldaccJapan.clone();
    newAccJapan.Id = oldaccJapan.Id;
    newAccJapan.Classification__c = 'SMB';
    accToUpdate.add(newAccJapan);

    update accToUpdate;

    AccountSetCompanyTierQueueable accountSetCompanyTierQueueable = new AccountSetCompanyTierQueueable(
      accToUpdate,
      null,
      oldAccounts
    );
    accountSetCompanyTierQueueable.execute(null);

    List<Account> allAcc = [
      SELECT Id, Name, ParentId, Classification__c, Ultimate_Parent_Classification__c, Company_Tier__c
      FROM Account
    ];

    for (Account acc : allAcc) {
      if (acc.Name == AccountEMEA) {
        System.assertEquals('B', acc.Company_Tier__c);
      }
      if (acc.Name == AccountAMER) {
        System.assertEquals('A', acc.Company_Tier__c);
      }
      if (acc.Name == AccountIndia) {
        System.assertEquals('A', acc.Company_Tier__c);
      }
      if (acc.Name == AccountAPAC) {
        System.assertEquals('C', acc.Company_Tier__c);
      }
      if (acc.Name == AccountJapan) {
        System.assertEquals('C', acc.Company_Tier__c);
      }
    }
  }
}