uipath-commons/main/default/objects/Account/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <description>This required field will be used to capture the country on the creation of a new account. It will populate the country on the new address records for accounts. The standard billing and shipping address fields on account will be made read only.</description>
    <label>Country</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Country_Global_List</valueSetName>
    </valueSet>
</CustomField>

uipath-commons/main/default/objects/Account/fields/Created_by_lead_convert__c.field-meta.xml
<CustomField>
        <fullName>Created_by_lead_convert__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Shows accounts created by lead convert
SLTECH-465</description>
        <inlineHelpText>Shows accounts created by lead convert</inlineHelpText>
        <label>Created by lead convert</label>
        <type>Checkbox</type>
    </CustomField>

uipath-commons/main/default/objects/Account/recordTypes/Partner.recordType-meta.xml
<RecordType>
    <fullName>Partner</fullName>
    <active>true</active>
    <description>UiPath prospective or existing Partner Account</description>
    <label>Partner</label>
</RecordType>

uipath-core/main/default/globalValueSets/Country_Global_List.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Afghanistan</fullName>
    </customValue>
    <customValue>
        <fullName>Aland Islands</fullName>
    </customValue>
    <customValue>
        <fullName>Albania</fullName>
    </customValue>
    <customValue>
        <fullName>Algeria</fullName>
    </customValue>
    <customValue>
        <fullName>Andorra</fullName>
    </customValue>
    <customValue>
        <fullName>Angola</fullName>
    </customValue>
    <customValue>
        <fullName>Anguilla</fullName>
    </customValue>
    <customValue>
        <fullName>Antarctica</fullName>
    </customValue>
    <customValue>
        <fullName>Antigua and Barbuda</fullName>
    </customValue>
    <customValue>
        <fullName>Argentina</fullName>
    </customValue>
    <customValue>
        <fullName>Armenia</fullName>
    </customValue>
    <customValue>
        <fullName>Aruba</fullName>
    </customValue>
    <customValue>
        <fullName>Australia</fullName>
    </customValue>
    <customValue>
        <fullName>Austria</fullName>
    </customValue>
    <customValue>
        <fullName>Azerbaijan</fullName>
    </customValue>
    <customValue>
        <fullName>Bahamas</fullName>
    </customValue>
    <customValue>
        <fullName>Bahrain</fullName>
    </customValue>
    <customValue>
        <fullName>Bangladesh</fullName>
    </customValue>
    <customValue>
        <fullName>Barbados</fullName>
    </customValue>
    <customValue>
        <fullName>Belarus</fullName>
    </customValue>
    <customValue>
        <fullName>Belgium</fullName>
    </customValue>
    <customValue>
        <fullName>Belize</fullName>
    </customValue>
    <customValue>
        <fullName>Benin</fullName>
    </customValue>
    <customValue>
        <fullName>Bermuda</fullName>
    </customValue>
    <customValue>
        <fullName>Bhutan</fullName>
    </customValue>
    <customValue>
        <fullName>Bolivia, Plurinational State of</fullName>
    </customValue>
    <customValue>
        <fullName>Bonaire, Sint Eustatius and Saba</fullName>
    </customValue>
    <customValue>
        <fullName>Bosnia and Herzegovina</fullName>
    </customValue>
    <customValue>
        <fullName>Botswana</fullName>
    </customValue>
    <customValue>
        <fullName>Bouvet Island</fullName>
    </customValue>
    <customValue>
        <fullName>Japan</fullName>
    </customValue>
    <description>Created for the new Address object and will be used for other objects (involved in integration with NetSuite)</description>
    <masterLabel>Country Global List</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet>

uipath-commons/main/default/classes/AccountUpdateJapanContactQueueable.cls
/**
 * TODO REWRITE : Can be moved to contact before trigger
 * Update contact LeadSource for all Japan converted Leads
 * *Org-cleanup : Process Builder - Conversion aid, Geo and Region
 */
public with sharing class AccountUpdateJapanContactQueueable extends AbstractQueueable {
  private final List<SObject> accountList;

  public AccountUpdateJapanContactQueueable(List<SObject> accountList) {
    super('AccountUpdateJapanContactQueueable');
    this.accountList = accountList;
  }

  public override void work() {
    this.setLeadSourceOnContact(this.accountList);
  }

  private void setLeadSourceOnContact(List<Account> accountList) {
    Set<Id> accIds = new Set<Id>();

    for (Account acc : accountList) {
      if (acc.Country__c == 'Japan' && acc.Created_by_lead_convert__c) {
        accIds.add(acc.Id);
      }
    }

    if (!accIds.isEmpty()) {
      List<Contact> conList = [
        SELECT Id, LeadSource
        FROM Contact
        WHERE AccountId IN :accIds
      ];
      for (Contact con : conList) {
        con.LeadSource = 'Partner';
      }

      if (!conList.isEmpty()) {
        update conList;
      }
    }
  }
}