uipath-commons/main/default/objects/Account/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <description>This required field will be used to capture the country on the creation of a new account. It will populate the country on the new address records for accounts. The standard billing and shipping address fields on account will be made read only.</description>
    <label>Country</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Country_Global_List</valueSetName>
    </valueSet>
</CustomField>

uipath-commons/main/default/objects/Account/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <description>Used to sync with address object at account creation</description>
    <label>State</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Country__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>States_Global_List</valueSetName>
    </valueSet>
</CustomField>

uipath-core/main/default/globalValueSets/Country_Global_List.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Afghanistan</fullName>
    </customValue>
    <customValue>
        <fullName>Aland Islands</fullName>
    </customValue>
    <customValue>
        <fullName>Albania</fullName>
    </customValue>
    <customValue>
        <fullName>Algeria</fullName>
    </customValue>
    <customValue>
        <fullName>Andorra</fullName>
    </customValue>
    <customValue>
        <fullName>Angola</fullName>
    </customValue>
    <customValue>
        <fullName>Anguilla</fullName>
    </customValue>
    <customValue>
        <fullName>Antarctica</fullName>
    </customValue>
    <customValue>
        <fullName>Antigua and Barbuda</fullName>
    </customValue>
    <customValue>
        <fullName>Argentina</fullName>
    </customValue>
    <customValue>
        <fullName>Armenia</fullName>
    </customValue>
    <customValue>
        <fullName>Aruba</fullName>
    </customValue>
    <customValue>
        <fullName>Australia</fullName>
    </customValue>
    <customValue>
        <fullName>Austria</fullName>
    </customValue>
    <customValue>
        <fullName>Azerbaijan</fullName>
    </customValue>
    <customValue>
        <fullName>Bahamas</fullName>
    </customValue>
    <customValue>
        <fullName>Bahrain</fullName>
    </customValue>
    <customValue>
        <fullName>Bangladesh</fullName>
    </customValue>
    <customValue>
        <fullName>Barbados</fullName>
    </customValue>
    <customValue>
        <fullName>Belarus</fullName>
    </customValue>
    <customValue>
        <fullName>Belgium</fullName>
    </customValue>
    <customValue>
        <fullName>Belize</fullName>
    </customValue>
    <customValue>
        <fullName>Benin</fullName>
    </customValue>
    <customValue>
        <fullName>Bermuda</fullName>
    </customValue>
    <customValue>
        <fullName>Bhutan</fullName>
    </customValue>
    <customValue>
        <fullName>Bolivia, Plurinational State of</fullName>
    </customValue>
    <customValue>
        <fullName>Bonaire, Sint Eustatius and Saba</fullName>
    </customValue>
    <customValue>
        <fullName>Bosnia and Herzegovina</fullName>
    </customValue>
    <customValue>
        <fullName>Botswana</fullName>
    </customValue>
    <customValue>
        <fullName>Bouvet Island</fullName>
    </customValue>
    <customValue>
        <fullName>China</fullName>
    </customValue>
    <customValue>
        <fullName>India</fullName>
    </customValue>
    <customValue>
        <fullName>United Kingdom</fullName>
    </customValue>
    <description>Created for the new Address object and will be used for other objects (involved in integration with NetSuite)</description>
    <masterLabel>Country Global List</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet>

uipath-commons/main/default/globalValueSets/States_Global_List.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Acre</fullName>
    </customValue>
    <customValue>
        <fullName>Aguascalientes</fullName>
    </customValue>
    <customValue>
        <fullName>Alabama</fullName>
    </customValue>
    <customValue>
        <fullName>Alagoas</fullName>
    </customValue>
    <customValue>
        <fullName>Alaska</fullName>
    </customValue>
    <customValue>
        <fullName>Alberta</fullName>
    </customValue>
    <customValue>
        <fullName>Amapá</fullName>
    </customValue>
    <customValue>
        <fullName>Amazonas</fullName>
    </customValue>
    <customValue>
        <fullName>Andaman and Nicobar Islands</fullName>
    </customValue>
    <customValue>
        <fullName>Andhra Pradesh</fullName>
    </customValue>
    <customValue>
        <fullName>Anhui</fullName>
    </customValue>
    <customValue>
        <fullName>Arizona</fullName>
    </customValue>
    <customValue>
        <fullName>Arkansas</fullName>
    </customValue>
    <customValue>
        <fullName>Arunachal Pradesh</fullName>
    </customValue>
    <customValue>
        <fullName>Assam</fullName>
    </customValue>
    <customValue>
        <fullName>Bahia</fullName>
    </customValue>
    <customValue>
        <fullName>Baja California</fullName>
    </customValue>
    <customValue>
        <fullName>Baja California Sur</fullName>
    </customValue>
    <customValue>
        <fullName>Beijing</fullName>
    </customValue>
    <customValue>
        <fullName>Bihar</fullName>
    </customValue>
    <customValue>
        <fullName>British Columbia</fullName>
    </customValue>
    <customValue>
        <fullName>California</fullName>
    </customValue>
    <customValue>
        <fullName>Campeche</fullName>
    </customValue>
    <customValue>
        <fullName>Ceara</fullName>
    </customValue>
    <customValue>
        <fullName>Chandigarh</fullName>
    </customValue>
    <customValue>
        <fullName>Chhattisgarh</fullName>
    </customValue>
    <customValue>
        <fullName>Chiapas</fullName>
    </customValue>
    <customValue>
        <fullName>Chihuahua</fullName>
    </customValue>
    <customValue>
        <fullName>Chinese Taipei</fullName>
    </customValue>
    <customValue>
        <fullName>Chongqing</fullName>
    </customValue>
    <customValue>
        <fullName>Gujarat</fullName>
    </customValue>
    <description>Created for the new Address object and will be used for other objects (involved in integration with NetSuite)</description>
    <masterLabel>States Global List</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet>

uipath-commons/main/default/classes/AccountsTest.cls
@IsTest
public with sharing class AccountsTest {

    @IsTest
    private static void validatesStateRequiredForChinaAustralia() {
        Accounts accounts = new Accounts(new Account[]{
                new Account (Name = 'Test', Country__c = 'China', State__c = null)
        });
        accounts.onValidate();
        System.assertEquals(1, fflib_SObjectDomain.Errors.getAll().size());
        System.assertEquals('State is required if Country is China', fflib_SObjectDomain.Errors.getAll()[0].message);
        System.assertEquals(Account.State__c, ((fflib_SObjectDomain.FieldError) fflib_SObjectDomain.Errors.getAll()[0]).field);
    }

    @IsTest
    private static void copiesStateToBillingStateIfCountryNotChinaAustralia() {
        Account account = new Account (Name = 'Test', Country__c = 'India', State__c = 'Gujarat');
        fflib_SObjectDomain.Test.Database.onInsert(new Account[]{
                account
        });
        fflib_SObjectDomain.triggerHandler(Accounts.class);
        System.assertEquals(account.BillingState, 'Gujarat');

    }


    /**
     * Can insert 200 Accounts in Bulk without Limits issues
     */
    @IsTest
    private static void canInsertAccountsInBulk() {

        List<Account> accounts = new List<Account>();
        for (Integer i = 0; i < 200; i++) {
            accounts.add(new Account (Name = 'Test ' + i, BillingCountry = 'United Kingdom', Industry = 'Others'));

        }
        //will throw on any limits issues
        System.assertEquals(Database.insert(accounts,true).size()>0, true);

    }


    /**
     * Can update 200 Accounts in Bulk without Limits issues
     */
    @IsTest
    private static void canUpdateAccountsInBulk() {

        List<Account> accounts = new List<Account>();
        for (Integer i = 0; i < 200; i++) {
            accounts.add(new Account (Name = 'Test ' + i, BillingCountry = 'United Kingdom', Industry = 'Others'));

        }
        insert accounts;

        Test.startTest();
        for (Integer i = 0; i < 200; i++) {
            accounts.get(i).Name='Updated Account ' + i;
        }
        //will throw on any limits issues
        List<Database.SaveResult> results=Database.update(accounts,true);
        Test.stopTest();
        System.assertEquals(results.size()>0, true);


    }

}