uipath-commons/main/default/objects/Account/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <description>This required field will be used to capture the country on the creation of a new account. It will populate the country on the new address records for accounts. The standard billing and shipping address fields on account will be made read only.</description>
    <label>Country</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Country_Global_List</valueSetName>
    </valueSet>
</CustomField>

uipath-commons/main/default/objects/Account/fields/DnB_City__c.field-meta.xml
<CustomField>
        <fullName>DnB_City__c</fullName>
        <description>D&amp;B address will be synced to custom D&amp;B address fields on account. From there, they can be synced to the address object. These fields are hidden and used in the background for syncing logic.</description>
        <label>DnB City</label>
        <length>40</length>
        <type>Text</type>
    </CustomField>

uipath-commons/main/default/objects/Account/fields/DnB_Country__c.field-meta.xml
<CustomField>
        <fullName>DnB_Country__c</fullName>
        <label>DnB Country</label>
        <length>50</length>
        <type>Text</type>
    </CustomField>

uipath-commons/main/default/objects/Account/fields/DnB_State_Province__c.field-meta.xml
<CustomField>
    <fullName>DnB_State_Province__c</fullName>
    <label>DnB State/Province</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

uipath-commons/main/default/objects/Account/fields/DnB_Street__c.field-meta.xml
<CustomField>
        <fullName>DnB_Street__c</fullName>
        <description>D&amp;B address will be synced to custom D&amp;B address fields on account. From there, they can be synced to the address object. These fields are hidden and used in the background for syncing logic.</description>
        <label>DnB Street</label>
        <type>TextArea</type>
    </CustomField>

uipath-commons/main/default/objects/Account/fields/DnB_Zip_Postal_Code__c.field-meta.xml
<CustomField>
        <fullName>DnB_Zip_Postal_Code__c</fullName>
        <description>D&amp;B address will be synced to custom D&amp;B address fields on account. From there, they can be synced to the address object. These fields are hidden and used in the background for syncing logic.</description>
        <label>DnB Zip/Postal Code</label>
        <length>20</length>
        <type>Text</type>
    </CustomField>

uipath-commons/main/default/objects/Account/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <description>Used to sync with address object at account creation</description>
    <label>State</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Country__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>States_Global_List</valueSetName>
    </valueSet>
</CustomField>

uipath-commons/main/default/objects/Address__c/Address__c.object-meta.xml
<CustomObject>
    <description>Object to hold the Customer Address details</description>
    <label>Address</label>
    <nameField>
        <displayFormat>ADD-{000000}</displayFormat>
        <label>Address ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Addresses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

uipath-commons/main/default/objects/Address__c/fields/Account__c.field-meta.xml
<CustomField>
        <fullName>Account__c</fullName>
        <description>Parent Account</description>
        <inlineHelpText>Parent Account</inlineHelpText>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Addresses</relationshipLabel>
        <relationshipName>Addresses</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </CustomField>

uipath-commons/main/default/objects/Address__c/fields/City__c.field-meta.xml
<CustomField>
        <fullName>City__c</fullName>
        <description>City</description>
        <inlineHelpText>City</inlineHelpText>
        <label>City</label>
        <length>40</length>
        <type>Text</type>
    </CustomField>

uipath-commons/main/default/objects/Address__c/fields/Country__c.field-meta.xml
<CustomField>
        <fullName>Country__c</fullName>
        <description>Country with ISO Codes</description>
        <inlineHelpText>Country with ISO Codes</inlineHelpText>
        <label>Country</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Country_Global_List</valueSetName>
        </valueSet>
    </CustomField>

uipath-commons/main/default/objects/Address__c/fields/D_B_Address__c.field-meta.xml
<CustomField>
        <fullName>D_B_Address__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Flag is true if address is sourced from D&amp;B</description>
        <label>D&amp;B Address</label>
        <type>Checkbox</type>
    </CustomField>

uipath-commons/main/default/objects/Address__c/fields/Primary_Billing__c.field-meta.xml
<CustomField>
        <fullName>Primary_Billing__c</fullName>
        <defaultValue>false</defaultValue>
        <description>To note the primary billing address on the Account</description>
        <inlineHelpText>Check the box if this is the primary billing address on the Account. Account can have only one primary billing Address at a time</inlineHelpText>
        <label>Primary Billing</label>
        <type>Checkbox</type>
    </CustomField>

uipath-commons/main/default/objects/Address__c/fields/Primary_Shipping__c.field-meta.xml
<CustomField>
        <fullName>Primary_Shipping__c</fullName>
        <defaultValue>false</defaultValue>
        <description>To note the primary shipping address on the Account</description>
        <inlineHelpText>Check the box if this is the primary shipping address on the Account. Account can have only one primary shipping Address at a time</inlineHelpText>
        <label>Primary Shipping</label>
        <type>Checkbox</type>
    </CustomField>

uipath-commons/main/default/objects/Address__c/fields/State__c.field-meta.xml
<CustomField>
        <fullName>State__c</fullName>
        <description>State</description>
        <inlineHelpText>State</inlineHelpText>
        <label>State</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Country__c</controllingField>
            <restricted>true</restricted>
            <valueSetName>States_Global_List</valueSetName>
        </valueSet>
    </CustomField>

uipath-commons/main/default/objects/Address__c/fields/Street_Line_1__c.field-meta.xml
<CustomField>
        <fullName>Street_Line_1__c</fullName>
        <description>Address Street</description>
        <inlineHelpText>Address Street</inlineHelpText>
        <label>Street Line 1</label>
        <length>150</length>
        <type>Text</type>
    </CustomField>

uipath-commons/main/default/objects/Address__c/fields/Street_Line_2__c.field-meta.xml
<CustomField>
        <fullName>Street_Line_2__c</fullName>
        <description>Street Address</description>
        <inlineHelpText>Street Address Line 2</inlineHelpText>
        <label>Street Line 2</label>
        <length>105</length>
        <type>Text</type>
    </CustomField>

uipath-commons/main/default/objects/Address__c/fields/Zip_Postal_Code__c.field-meta.xml
<CustomField>
        <fullName>Zip_Postal_Code__c</fullName>
        <description>Zip/Postal Code</description>
        <inlineHelpText>Zip/Postal Code</inlineHelpText>
        <label>Zip/Postal Code</label>
        <length>20</length>
        <type>Text</type>
    </CustomField>

uipath-core/main/default/globalValueSets/Country_Global_List.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Afghanistan</fullName>
    </customValue>
    <customValue>
        <fullName>Aland Islands</fullName>
    </customValue>
    <customValue>
        <fullName>Albania</fullName>
    </customValue>
    <customValue>
        <fullName>Algeria</fullName>
    </customValue>
    <customValue>
        <fullName>Andorra</fullName>
    </customValue>
    <customValue>
        <fullName>Angola</fullName>
    </customValue>
    <customValue>
        <fullName>Anguilla</fullName>
    </customValue>
    <customValue>
        <fullName>Antarctica</fullName>
    </customValue>
    <customValue>
        <fullName>Antigua and Barbuda</fullName>
    </customValue>
    <customValue>
        <fullName>Argentina</fullName>
    </customValue>
    <customValue>
        <fullName>Armenia</fullName>
    </customValue>
    <customValue>
        <fullName>Aruba</fullName>
    </customValue>
    <customValue>
        <fullName>Australia</fullName>
    </customValue>
    <customValue>
        <fullName>Austria</fullName>
    </customValue>
    <customValue>
        <fullName>Azerbaijan</fullName>
    </customValue>
    <customValue>
        <fullName>Bahamas</fullName>
    </customValue>
    <customValue>
        <fullName>Bahrain</fullName>
    </customValue>
    <customValue>
        <fullName>Bangladesh</fullName>
    </customValue>
    <customValue>
        <fullName>Barbados</fullName>
    </customValue>
    <customValue>
        <fullName>Belarus</fullName>
    </customValue>
    <customValue>
        <fullName>Belgium</fullName>
    </customValue>
    <customValue>
        <fullName>Belize</fullName>
    </customValue>
    <customValue>
        <fullName>Benin</fullName>
    </customValue>
    <customValue>
        <fullName>Bermuda</fullName>
    </customValue>
    <customValue>
        <fullName>Bhutan</fullName>
    </customValue>
    <customValue>
        <fullName>Bolivia, Plurinational State of</fullName>
    </customValue>
    <customValue>
        <fullName>Bonaire, Sint Eustatius and Saba</fullName>
    </customValue>
    <customValue>
        <fullName>Bosnia and Herzegovina</fullName>
    </customValue>
    <customValue>
        <fullName>Botswana</fullName>
    </customValue>
    <customValue>
        <fullName>Bouvet Island</fullName>
    </customValue>
    <description>Created for the new Address object and will be used for other objects (involved in integration with NetSuite)</description>
    <masterLabel>Country Global List</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet>

uipath-commons/main/default/globalValueSets/States_Global_List.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Acre</fullName>
    </customValue>
    <customValue>
        <fullName>Aguascalientes</fullName>
    </customValue>
    <customValue>
        <fullName>Alabama</fullName>
    </customValue>
    <customValue>
        <fullName>Alagoas</fullName>
    </customValue>
    <customValue>
        <fullName>Alaska</fullName>
    </customValue>
    <customValue>
        <fullName>Alberta</fullName>
    </customValue>
    <customValue>
        <fullName>Amapá</fullName>
    </customValue>
    <customValue>
        <fullName>Amazonas</fullName>
    </customValue>
    <customValue>
        <fullName>Andaman and Nicobar Islands</fullName>
    </customValue>
    <customValue>
        <fullName>Andhra Pradesh</fullName>
    </customValue>
    <customValue>
        <fullName>Anhui</fullName>
    </customValue>
    <customValue>
        <fullName>Arizona</fullName>
    </customValue>
    <customValue>
        <fullName>Arkansas</fullName>
    </customValue>
    <customValue>
        <fullName>Arunachal Pradesh</fullName>
    </customValue>
    <customValue>
        <fullName>Assam</fullName>
    </customValue>
    <customValue>
        <fullName>Bahia</fullName>
    </customValue>
    <customValue>
        <fullName>Baja California</fullName>
    </customValue>
    <customValue>
        <fullName>Baja California Sur</fullName>
    </customValue>
    <customValue>
        <fullName>Beijing</fullName>
    </customValue>
    <customValue>
        <fullName>Bihar</fullName>
    </customValue>
    <customValue>
        <fullName>British Columbia</fullName>
    </customValue>
    <customValue>
        <fullName>California</fullName>
    </customValue>
    <customValue>
        <fullName>Campeche</fullName>
    </customValue>
    <customValue>
        <fullName>Ceara</fullName>
    </customValue>
    <customValue>
        <fullName>Chandigarh</fullName>
    </customValue>
    <customValue>
        <fullName>Chhattisgarh</fullName>
    </customValue>
    <customValue>
        <fullName>Chiapas</fullName>
    </customValue>
    <customValue>
        <fullName>Chihuahua</fullName>
    </customValue>
    <customValue>
        <fullName>Chinese Taipei</fullName>
    </customValue>
    <customValue>
        <fullName>Chongqing</fullName>
    </customValue>
    <description>Created for the new Address object and will be used for other objects (involved in integration with NetSuite)</description>
    <masterLabel>States Global List</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet>

uipath-commons/main/default/classes/AccountDNBCompanyQueueable.cls
/**
 * TODO REWRITE
 * this code was just moved here from the sync Trigger context into a Queueable Context.
 * Needs to be rewritten entirely
 */
public with sharing class AccountDNBCompanyQueueable extends AbstractQueueable {
    private final List<SObject> accountsLst;
    private final Map<Id, SObject> oldAccountsMap;

    public AccountDNBCompanyQueueable(
            List<SObject> accountsLst,
            Map<Id, SObject> oldAccountsMap
    ) {
        super('AccountDNBCompanyQueueable');
        this.accountsLst = accountsLst;
        this.oldAccountsMap = oldAccountsMap;
    }

    public override void work() {
        this.processDNBCompany(this.accountsLst, oldAccountsMap);
    }


  /**
   * TODO REWRITE
   * @DESCRIPTION: Process mapped D&B Company, create an address record for D&B address
   * @AUTHOR: SV - Slalom Consulting
   */
  private void processDNBCompany(List<SObject> accountList, Map<Id, SObject> oldAccountsMap) {

    List<Address__c> addressList = new List<Address__c>();
    Set<Id> addressHasBeenAddedFor = new Set<Id>();

    List<String> AvailableCountryStates = new List<String>();

    Schema.DescribeFieldResult stateResult = Address__c.State__c.getDescribe();
    List<Schema.PicklistEntry> statePLE = stateResult.getPicklistValues();
    for (Schema.PicklistEntry entry : statePLE) {
        AvailableCountryStates.add(entry.getValue());
    }


    for (Account acc : (List<Account>) accountList) {
      Account oldAccount = (Account) oldAccountsMap.get(acc.Id);

      //Only run the first time the D&B account/address is set
      if (
        String.IsNotBlank(acc.DnB_Country__c) &&
        String.IsBlank(oldAccount.DnB_Country__c)
      ) {
        if (addressHasBeenAddedFor.contains(acc.Id)) {
          //SFSL-827
          continue;
        }

        //Mapped D&B Company has changed. Create an address record based on D&B details and mark it as primary billing
        Address__c address = new Address__c();
        address.Account__c = acc.Id;
        address.Primary_Billing__c = true;
        address.Primary_Shipping__c = true;

        address.D_B_Address__c = true;

        //if D&B country is different from Country__c, data steward needs to fix data manually
        address.Country__c = acc.DnB_Country__c;

        //D&B street is 255 characters. On address object we have street 1 (150 characters) and street 2 (105 characters)
        if (String.IsNotBlank(acc.DnB_Street__c)) {
          address.Street_Line_1__c = acc.DnB_Street__c.left(150);
          if (acc.DnB_Street__c.length() > 150) {
            address.Street_Line_2__c = acc.DnB_Street__c.substring(
              150,
              acc.DnB_Street__c.length()
            );
          }
        }
        address.City__c = acc.DnB_City__c;
        address.Zip_Postal_Code__c = acc.DnB_Zip_Postal_Code__c;

        if (AvailableCountryStates.Contains(acc.DnB_State_Province__c)) {
          address.State__c = acc.DnB_State_Province__c;
        }

        address.RecordTypeId = Utilities.getRecordTypeId(
          Constants.ADDRESS_RECORD_TYPE_LOCKDOWN,
          'Address__c'
        );

        addressList.add(address);
        addressHasBeenAddedFor.add(acc.Id);
      }
    }
    insert addressList;
  }
}