uipath-commons/main/default/objects/Account/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <description>This required field will be used to capture the country on the creation of a new account. It will populate the country on the new address records for accounts. The standard billing and shipping address fields on account will be made read only.</description>
    <label>Country</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Country_Global_List</valueSetName>
    </valueSet>
</CustomField>

uipath-commons/main/default/objects/Account/fields/Sync_Status__c.field-meta.xml
<CustomField>
    <fullName>Sync_Status__c</fullName>
    <description>Indicated the status of the product against integration</description>
    <inlineHelpText>Not Valid - default sync status for new records
Valid - Ready to be synced to NetSuite
Pending - Updates on record ready to be synced to NetSuite
Synced - Synced to NetSuite
Error - Error while syncing
Do Not Sync - Archive from syncing</inlineHelpText>
    <label>Sync Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Sync_Status</valueSetName>
    </valueSet>
</CustomField>

uipath-commons/main/default/objects/Account/fields/Validation_Status__c.field-meta.xml
<CustomField>
    <fullName>Validation_Status__c</fullName>
    <description>Used by the Data Stewards to flag the Account validation status</description>
    <inlineHelpText>When Data Stewards set the status to &quot;Validated&quot; call to boomi integration will be made</inlineHelpText>
    <label>Validation Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Data_Steward_Validation_Status</valueSetName>
    </valueSet>
</CustomField>

uipath-commons/main/default/objects/Address__c/Address__c.object-meta.xml
<CustomObject>
    <description>Object to hold the Customer Address details</description>
    <label>Address</label>
    <nameField>
        <displayFormat>ADD-{000000}</displayFormat>
        <label>Address ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Addresses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

uipath-commons/main/default/objects/Address__c/fields/Account__c.field-meta.xml
<CustomField>
        <fullName>Account__c</fullName>
        <description>Parent Account</description>
        <inlineHelpText>Parent Account</inlineHelpText>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Addresses</relationshipLabel>
        <relationshipName>Addresses</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </CustomField>

uipath-commons/main/default/objects/Address__c/fields/City__c.field-meta.xml
<CustomField>
        <fullName>City__c</fullName>
        <description>City</description>
        <inlineHelpText>City</inlineHelpText>
        <label>City</label>
        <length>40</length>
        <type>Text</type>
    </CustomField>

uipath-commons/main/default/objects/Address__c/fields/Country__c.field-meta.xml
<CustomField>
        <fullName>Country__c</fullName>
        <description>Country with ISO Codes</description>
        <inlineHelpText>Country with ISO Codes</inlineHelpText>
        <label>Country</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Country_Global_List</valueSetName>
        </valueSet>
    </CustomField>

uipath-commons/main/default/objects/Address__c/fields/Created_From_Account__c.field-meta.xml
<CustomField>
        <fullName>Created_From_Account__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Checkbox to indicate address was created from account. If so, don&#39;t update account on address creation.</description>
        <label>Created From Account</label>
        <type>Checkbox</type>
    </CustomField>

uipath-commons/main/default/objects/Address__c/fields/Primary_Billing__c.field-meta.xml
<CustomField>
        <fullName>Primary_Billing__c</fullName>
        <defaultValue>false</defaultValue>
        <description>To note the primary billing address on the Account</description>
        <inlineHelpText>Check the box if this is the primary billing address on the Account. Account can have only one primary billing Address at a time</inlineHelpText>
        <label>Primary Billing</label>
        <type>Checkbox</type>
    </CustomField>

uipath-commons/main/default/objects/Address__c/fields/Primary_Shipping__c.field-meta.xml
<CustomField>
        <fullName>Primary_Shipping__c</fullName>
        <defaultValue>false</defaultValue>
        <description>To note the primary shipping address on the Account</description>
        <inlineHelpText>Check the box if this is the primary shipping address on the Account. Account can have only one primary shipping Address at a time</inlineHelpText>
        <label>Primary Shipping</label>
        <type>Checkbox</type>
    </CustomField>

uipath-commons/main/default/objects/Address__c/fields/Sync_Status__c.field-meta.xml
<CustomField>
        <fullName>Sync_Status__c</fullName>
        <description>Sync Status to indicate the integration status</description>
        <inlineHelpText>Sync Status to indicate the integration status</inlineHelpText>
        <label>Sync Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Sync_Status</valueSetName>
        </valueSet>
    </CustomField>

uipath-commons/main/default/objects/Address__c/fields/Validation_Status__c.field-meta.xml
<CustomField>
        <fullName>Validation_Status__c</fullName>
        <description>Used by the Data Stewards to flag the Account validation status</description>
        <inlineHelpText>Used by the Data Stewards to flag the Account validation status. When Data Stewards set the status to &quot;Validated&quot; call to boomi integration will be made</inlineHelpText>
        <label>Validation Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Data_Steward_Validation_Status</valueSetName>
        </valueSet>
    </CustomField>

uipath-core/main/default/globalValueSets/Country_Global_List.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Afghanistan</fullName>
    </customValue>
    <customValue>
        <fullName>Aland Islands</fullName>
    </customValue>
    <customValue>
        <fullName>Albania</fullName>
    </customValue>
    <customValue>
        <fullName>Algeria</fullName>
    </customValue>
    <customValue>
        <fullName>Andorra</fullName>
    </customValue>
    <customValue>
        <fullName>Angola</fullName>
    </customValue>
    <customValue>
        <fullName>Anguilla</fullName>
    </customValue>
    <customValue>
        <fullName>Antarctica</fullName>
    </customValue>
    <customValue>
        <fullName>Antigua and Barbuda</fullName>
    </customValue>
    <customValue>
        <fullName>Argentina</fullName>
    </customValue>
    <customValue>
        <fullName>Armenia</fullName>
    </customValue>
    <customValue>
        <fullName>Aruba</fullName>
    </customValue>
    <customValue>
        <fullName>Australia</fullName>
    </customValue>
    <customValue>
        <fullName>Austria</fullName>
    </customValue>
    <customValue>
        <fullName>Azerbaijan</fullName>
    </customValue>
    <customValue>
        <fullName>Bahamas</fullName>
    </customValue>
    <customValue>
        <fullName>Bahrain</fullName>
    </customValue>
    <customValue>
        <fullName>Bangladesh</fullName>
    </customValue>
    <customValue>
        <fullName>Barbados</fullName>
    </customValue>
    <customValue>
        <fullName>Belarus</fullName>
    </customValue>
    <customValue>
        <fullName>Belgium</fullName>
    </customValue>
    <customValue>
        <fullName>Belize</fullName>
    </customValue>
    <customValue>
        <fullName>Benin</fullName>
    </customValue>
    <customValue>
        <fullName>Bermuda</fullName>
    </customValue>
    <customValue>
        <fullName>Bhutan</fullName>
    </customValue>
    <customValue>
        <fullName>Bolivia, Plurinational State of</fullName>
    </customValue>
    <customValue>
        <fullName>Bonaire, Sint Eustatius and Saba</fullName>
    </customValue>
    <customValue>
        <fullName>Bosnia and Herzegovina</fullName>
    </customValue>
    <customValue>
        <fullName>Botswana</fullName>
    </customValue>
    <customValue>
        <fullName>Bouvet Island</fullName>
    </customValue>
    <customValue>
        <fullName>United Kingdom</fullName>
    </customValue>
    <description>Created for the new Address object and will be used for other objects (involved in integration with NetSuite)</description>
    <masterLabel>Country Global List</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet>

uipath-commons/main/default/globalValueSets/Data_Steward_Validation_Status.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>In Review</fullName>
    </customValue>
    <customValue>
        <fullName>Pending</fullName>
        <default>true</default>
        <label>Pending</label>
    </customValue>
    <customValue>
        <fullName>Ready For Review</fullName>
    </customValue>
    <customValue>
        <fullName>Review Complete</fullName>
    </customValue>
    <customValue>
        <fullName>Validated</fullName>
    </customValue>
    <description>Validation Status values to be used by the Data Stewards on Accounts, Addresses etc</description>
    <masterLabel>Data Steward Validation Status</masterLabel>
</GlobalValueSet>

uipath-commons/main/default/globalValueSets/Sync_Status.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Do Not Sync</fullName>
    </customValue>
    <customValue>
        <fullName>Error</fullName>
    </customValue>
    <customValue>
        <fullName>Not Valid</fullName>
        <default>true</default>
        <label>Not Valid</label>
    </customValue>
    <customValue>
        <fullName>Pending</fullName>
    </customValue>
    <customValue>
        <fullName>Synced</fullName>
    </customValue>
    <customValue>
        <fullName>Valid</fullName>
    </customValue>
    <description>Sync Status used to maintain various integration status</description>
    <masterLabel>Sync Status</masterLabel>
</GlobalValueSet>

uipath-commons/main/default/classes/IntegrationHandlerTest.cls
/**
    * @DESCRIPTION: This is Test Class for IntegrationHandler class
    * @AUTHOR: Slalom Consulting
*/
@IsTest
private class IntegrationHandlerTest {

    private static User getAdminUser(){
        User adminUser = new User();
        adminUser.ProfileId = [SELECT Id FROM Profile WHERE Name = 'System Administrator'].Id;
        adminUser.Username = 'test839734@uiath.com';
        adminUser.LastName = 'Test';
        adminUser.Email = 'test839734@uiath.com';
        adminUser.Alias = 't839734';
        adminUser.TimeZoneSidKey = 'America/Los_Angeles';
        adminUser.LocaleSidKey = 'en_US';
        adminUser.EmailEncodingKey = 'UTF-8';
        adminUser.LanguageLocaleKey = 'en_US';
        insert adminUser;

        return adminUser;
    }

    @isTest
    private static void syncStatusAutomationProcessTest(){
        
        Account acc = new Account(
            Id = fflib_IDGenerator.generate(Account.SObjectType),
            Name = 'syncStatusAutomationProcessTest',
            Country__c = 'United Kingdom'
        );

        Address__c address = new Address__c(
            Id = fflib_IDGenerator.generate(Address__c.SObjectType),
            Account__c = acc.Id,
            Primary_Billing__c = true,
            Primary_Shipping__c = true,
            Created_From_Account__c = true,
            Country__c = 'United Kingdom',
            Sync_Status__c = 'Synced'
        );
        
        Address__c updatedAddress = new Address__c(
            Id = address.Id,
            Account__c = acc.Id,
            Primary_Billing__c = true,
            Primary_Shipping__c = true,
            Created_From_Account__c = true,
            Country__c = 'United Kingdom',
            City__c = 'London',
            Sync_Status__c = 'Synced'
        );

        Test.startTest();
            System.runAs(getAdminUser()){

                IntegrationHandler.syncStatusAutomationProcess(
                    new Map<Id, Address__c>{address.Id => address},
                    new List<Address__c>{updatedAddress}
                );
            }

            System.assertEquals(CommonsConstants.ACC_SYNC_STATUS_PENDING, updatedAddress.Sync_Status__c); //Should be Pending

        Test.stopTest();
    }

    @isTest
    private static void updateAccountValidationStatusToReadyForReviewTest(){
        
        Account acc = new Account(
            Name = 'Test Acc',
            BillingCountry = 'United Kingdom',
            Country__c = 'United Kingdom',
            Industry = 'Others',
            Validation_Status__c = CommonsConstants.ACC_SYNC_STATUS_PENDING
        );
        insert acc;

        Address__c address = new Address__c(
            Account__c = acc.Id,
            Primary_Billing__c = true,
            Primary_Shipping__c = true,
            Created_From_Account__c = true,
            Country__c = 'United Kingdom',
            Validation_Status__c = CommonsConstants.ACC_SYNC_STATUS_PENDING
        );
        insert address;

        Test.startTest();
            
        IntegrationHandler.updateAccountValidationStatusToReadyForReview(
            new Set<Id>{acc.Id}
        );
        
        Account updatedAccount = [SELECT Id, Validation_Status__c FROM Account WHERE Id = :acc.Id];
        System.assertEquals(CommonsConstants.ACC_VALIDATION_STATUS_READY_FOR_REVIEW, updatedAccount.Validation_Status__c);

        Address__c updatedAddress = [SELECT Id, Validation_Status__c FROM Address__c WHERE Id = :address.Id];
        System.assertEquals(CommonsConstants.ACC_VALIDATION_STATUS_READY_FOR_REVIEW, updatedAddress.Validation_Status__c);

        Test.stopTest();
    }
}