uipath-commons/main/default/objects/Account/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <description>This required field will be used to capture the country on the creation of a new account. It will populate the country on the new address records for accounts. The standard billing and shipping address fields on account will be made read only.</description>
    <label>Country</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Country_Global_List</valueSetName>
    </valueSet>
</CustomField>

uipath-commons/main/default/objects/Account/fields/DnB_Country__c.field-meta.xml
<CustomField>
        <fullName>DnB_Country__c</fullName>
        <label>DnB Country</label>
        <length>50</length>
        <type>Text</type>
    </CustomField>

uipath-commons/main/default/objects/Account/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <description>Used to sync with address object at account creation</description>
    <label>State</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Country__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>States_Global_List</valueSetName>
    </valueSet>
</CustomField>

uipath-core/main/default/globalValueSets/Country_Global_List.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Afghanistan</fullName>
    </customValue>
    <customValue>
        <fullName>Aland Islands</fullName>
    </customValue>
    <customValue>
        <fullName>Albania</fullName>
    </customValue>
    <customValue>
        <fullName>Algeria</fullName>
    </customValue>
    <customValue>
        <fullName>Andorra</fullName>
    </customValue>
    <customValue>
        <fullName>Angola</fullName>
    </customValue>
    <customValue>
        <fullName>Anguilla</fullName>
    </customValue>
    <customValue>
        <fullName>Antarctica</fullName>
    </customValue>
    <customValue>
        <fullName>Antigua and Barbuda</fullName>
    </customValue>
    <customValue>
        <fullName>Argentina</fullName>
    </customValue>
    <customValue>
        <fullName>Armenia</fullName>
    </customValue>
    <customValue>
        <fullName>Aruba</fullName>
    </customValue>
    <customValue>
        <fullName>Australia</fullName>
    </customValue>
    <customValue>
        <fullName>Austria</fullName>
    </customValue>
    <customValue>
        <fullName>Azerbaijan</fullName>
    </customValue>
    <customValue>
        <fullName>Bahamas</fullName>
    </customValue>
    <customValue>
        <fullName>Bahrain</fullName>
    </customValue>
    <customValue>
        <fullName>Bangladesh</fullName>
    </customValue>
    <customValue>
        <fullName>Barbados</fullName>
    </customValue>
    <customValue>
        <fullName>Belarus</fullName>
    </customValue>
    <customValue>
        <fullName>Belgium</fullName>
    </customValue>
    <customValue>
        <fullName>Belize</fullName>
    </customValue>
    <customValue>
        <fullName>Benin</fullName>
    </customValue>
    <customValue>
        <fullName>Bermuda</fullName>
    </customValue>
    <customValue>
        <fullName>Bhutan</fullName>
    </customValue>
    <customValue>
        <fullName>Bolivia, Plurinational State of</fullName>
    </customValue>
    <customValue>
        <fullName>Bonaire, Sint Eustatius and Saba</fullName>
    </customValue>
    <customValue>
        <fullName>Bosnia and Herzegovina</fullName>
    </customValue>
    <customValue>
        <fullName>Botswana</fullName>
    </customValue>
    <customValue>
        <fullName>Bouvet Island</fullName>
    </customValue>
    <customValue>
        <fullName>China</fullName>
    </customValue>
    <customValue>
        <fullName>India</fullName>
    </customValue>
    <description>Created for the new Address object and will be used for other objects (involved in integration with NetSuite)</description>
    <masterLabel>Country Global List</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet>

uipath-commons/main/default/globalValueSets/States_Global_List.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Acre</fullName>
    </customValue>
    <customValue>
        <fullName>Aguascalientes</fullName>
    </customValue>
    <customValue>
        <fullName>Alabama</fullName>
    </customValue>
    <customValue>
        <fullName>Alagoas</fullName>
    </customValue>
    <customValue>
        <fullName>Alaska</fullName>
    </customValue>
    <customValue>
        <fullName>Alberta</fullName>
    </customValue>
    <customValue>
        <fullName>Amapá</fullName>
    </customValue>
    <customValue>
        <fullName>Amazonas</fullName>
    </customValue>
    <customValue>
        <fullName>Andaman and Nicobar Islands</fullName>
    </customValue>
    <customValue>
        <fullName>Andhra Pradesh</fullName>
    </customValue>
    <customValue>
        <fullName>Anhui</fullName>
    </customValue>
    <customValue>
        <fullName>Arizona</fullName>
    </customValue>
    <customValue>
        <fullName>Arkansas</fullName>
    </customValue>
    <customValue>
        <fullName>Arunachal Pradesh</fullName>
    </customValue>
    <customValue>
        <fullName>Assam</fullName>
    </customValue>
    <customValue>
        <fullName>Bahia</fullName>
    </customValue>
    <customValue>
        <fullName>Baja California</fullName>
    </customValue>
    <customValue>
        <fullName>Baja California Sur</fullName>
    </customValue>
    <customValue>
        <fullName>Beijing</fullName>
    </customValue>
    <customValue>
        <fullName>Bihar</fullName>
    </customValue>
    <customValue>
        <fullName>British Columbia</fullName>
    </customValue>
    <customValue>
        <fullName>California</fullName>
    </customValue>
    <customValue>
        <fullName>Campeche</fullName>
    </customValue>
    <customValue>
        <fullName>Ceara</fullName>
    </customValue>
    <customValue>
        <fullName>Chandigarh</fullName>
    </customValue>
    <customValue>
        <fullName>Chhattisgarh</fullName>
    </customValue>
    <customValue>
        <fullName>Chiapas</fullName>
    </customValue>
    <customValue>
        <fullName>Chihuahua</fullName>
    </customValue>
    <customValue>
        <fullName>Chinese Taipei</fullName>
    </customValue>
    <customValue>
        <fullName>Chongqing</fullName>
    </customValue>
    <description>Created for the new Address object and will be used for other objects (involved in integration with NetSuite)</description>
    <masterLabel>States Global List</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet>

uipath-commons/main/default/classes/AccountValidationFunction.cls
public with sharing class AccountValidationFunction implements SObjectToSObjectFunction {

    private final Map<Id, SObject> existingRecords;
    private final fflib_SObjectDomain domain;

    public AccountValidationFunction(Map<Id, SObject> existingRecords,fflib_SObjectDomain domain) {
        this.existingRecords = existingRecords;
        this.domain=domain;
    }

    public SObject apply(Account modifiedAccount) {


        validateStatePopulatedForChinaAustralia(modifiedAccount);

        //Validate during updates
        if(existingRecords!=null && !existingRecords.isEmpty()){
            validateIfDnBCountryChanged(modifiedAccount);
        }

        return modifiedAccount;
    }

    public SObject apply(SObject record) {
        return apply((Account) record);
    }

    private void validateIfDnBCountryChanged(Account acc) {

        Account oldAcc = (Account) existingRecords.get(acc.Id);

        if (
            String.isNotBlank(acc.DnB_Country__c) &&
                String.isBlank(oldAcc.DnB_Country__c)
            ) {
            if (acc.DnB_Country__c != acc.Country__c) {
                acc.addError(
                    domain.error(
                        'You cannot select a D&B Company from a different country.',
                        acc
                    )
                );
            }
        }
    }

    private void validateStatePopulatedForChinaAustralia(Account acc) {
        if (isCountryChinaOrAustraliaOrIndia(acc) && acc.State__c == null) {
            acc.State__c.addError(
                domain.error(
                    'State is required if Country is ' + acc.Country__c,
                    acc,
                    Account.State__c
                )
            );
        }
    }

    private Boolean isCountryChinaOrAustraliaOrIndia(Account acc) {
        return (acc.Country__c == 'China' || acc.Country__c == 'Australia' || acc.Country__c == 'India');
    }


}