uipath-commons/main/default/objects/Account/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <description>This required field will be used to capture the country on the creation of a new account. It will populate the country on the new address records for accounts. The standard billing and shipping address fields on account will be made read only.</description>
    <label>Country</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Country_Global_List</valueSetName>
    </valueSet>
</CustomField>

uipath-commons/main/default/objects/Account/fields/Primary_Subsidiary__c.field-meta.xml
<CustomField>
        <fullName>Primary_Subsidiary__c</fullName>
        <description>UiPath Subsidiaries that will be set on Account creation based on the Country-Subsidiary mapping</description>
        <inlineHelpText>UiPath Subsidiary that is working with this Customer</inlineHelpText>
        <label>Primary Subsidiary</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>UiPath SRL</fullName>
                </value>
                <value>
                    <fullName>UiPath INC</fullName>
                </value>
                <value>
                    <fullName>UiPath KK</fullName>
                </value>
                <value>
                    <fullName>UiPath Netherlands BV</fullName>
                </value>
                <value>
                    <fullName>ProcessGold International BV</fullName>
                </value>
                <value>
                    <fullName>MagnaView BV</fullName>
                </value>
                <value>
                    <fullName>ProcessGold AG</fullName>
                </value>
                <value>
                    <fullName>ProcessGold BV</fullName>
                </value>
                <value>
                    <fullName>UiPath Ltd. (India)</fullName>
                </value>
                <value>
                    <fullName>UiPath GMBH</fullName>
                </value>
                <value>
                    <fullName>Process Gold BV</fullName>
                    <isActive>false</isActive>
                    <label>Process Gold BV</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </CustomField>

uipath-core/main/default/globalValueSets/Country_Global_List.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Afghanistan</fullName>
    </customValue>
    <customValue>
        <fullName>Aland Islands</fullName>
    </customValue>
    <customValue>
        <fullName>Albania</fullName>
    </customValue>
    <customValue>
        <fullName>Algeria</fullName>
    </customValue>
    <customValue>
        <fullName>Andorra</fullName>
    </customValue>
    <customValue>
        <fullName>Angola</fullName>
    </customValue>
    <customValue>
        <fullName>Anguilla</fullName>
    </customValue>
    <customValue>
        <fullName>Antarctica</fullName>
    </customValue>
    <customValue>
        <fullName>Antigua and Barbuda</fullName>
    </customValue>
    <customValue>
        <fullName>Argentina</fullName>
    </customValue>
    <customValue>
        <fullName>Armenia</fullName>
    </customValue>
    <customValue>
        <fullName>Aruba</fullName>
    </customValue>
    <customValue>
        <fullName>Australia</fullName>
    </customValue>
    <customValue>
        <fullName>Austria</fullName>
    </customValue>
    <customValue>
        <fullName>Azerbaijan</fullName>
    </customValue>
    <customValue>
        <fullName>Bahamas</fullName>
    </customValue>
    <customValue>
        <fullName>Bahrain</fullName>
    </customValue>
    <customValue>
        <fullName>Bangladesh</fullName>
    </customValue>
    <customValue>
        <fullName>Barbados</fullName>
    </customValue>
    <customValue>
        <fullName>Belarus</fullName>
    </customValue>
    <customValue>
        <fullName>Belgium</fullName>
    </customValue>
    <customValue>
        <fullName>Belize</fullName>
    </customValue>
    <customValue>
        <fullName>Benin</fullName>
    </customValue>
    <customValue>
        <fullName>Bermuda</fullName>
    </customValue>
    <customValue>
        <fullName>Bhutan</fullName>
    </customValue>
    <customValue>
        <fullName>Bolivia, Plurinational State of</fullName>
    </customValue>
    <customValue>
        <fullName>Bonaire, Sint Eustatius and Saba</fullName>
    </customValue>
    <customValue>
        <fullName>Bosnia and Herzegovina</fullName>
    </customValue>
    <customValue>
        <fullName>Botswana</fullName>
    </customValue>
    <customValue>
        <fullName>Bouvet Island</fullName>
    </customValue>
    <description>Created for the new Address object and will be used for other objects (involved in integration with NetSuite)</description>
    <masterLabel>Country Global List</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet>

uipath-commons/main/default/classes/AccountSetSubsidiaryFunction.cls
/**
 * Sets subsidiary on each account. Uses Country__c to determine subsidiart
 */
public class AccountSetSubsidiaryFunction implements SObjectToSObjectFunction {
  private Map<String, String> countrySubsidiaryMap;

  public AccountSetSubsidiaryFunction(
    Map<String, String> countrySubsidiaryMap
  ) {
    this.countrySubsidiaryMap = countrySubsidiaryMap;
  }

  public SObject apply(Account acc) {
    //take the first 40 characters as the label field has a max 40 chars
    String accountCountryToFind = acc.Country__c.left(40).toLowerCase();
    String countrySubsidiary = countrySubsidiaryMap.get(accountCountryToFind);
    if (String.IsNotBlank(countrySubsidiary)) {
      acc.Primary_Subsidiary__c = countrySubsidiaryMap.get(
        accountCountryToFind
      );
    }
    return acc;
  }

  public SObject apply(SObject record) {
    return apply((Account) record);
  }
}