uipath-commons/main/default/objects/Account/fields/CSAT__c.field-meta.xml
<CustomField>
        <fullName>CSAT__c</fullName>
        <label>CSAT</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Percent</type>
    </CustomField>

uipath-commons/main/default/objects/Account/fields/LD_USE_DnB_Optimize__c.field-meta.xml
<CustomField>
    <fullName>LD_USE_DnB_Optimize__c</fullName>
    <defaultValue>true</defaultValue>
    <description>“Checked” will allow a match from Optimizer, where an “Unchecked” box will exclude the record
from matching.</description>
    <label>Allow D&amp;B Optimizer</label>
    <type>Checkbox</type>
</CustomField>

uipath-service/main/default/objects/Case/fields/Closure_Classification__c.field-meta.xml
<CustomField>
    <fullName>Closure_Classification__c</fullName>
    <label>Closure Classification</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>3rd Party not under support scope</fullName>
            </value>
            <value>
                <fullName>Answer/Solution Provided</fullName>
            </value>
            <value>
                <fullName>Answer/Solution provided(Referring KB)</fullName>
            </value>
            <value>
                <fullName>Bug</fullName>
                <isActive>false</isActive>
                <label>Bug</label>
            </value>
            <value>
                <fullName>Bug - Reported as JIRA</fullName>
            </value>
            <value>
                <fullName>By Design</fullName>
                <isActive>false</isActive>
                <label>By Design</label>
            </value>
            <value>
                <fullName>Cannot Reproduce</fullName>
                <isActive>false</isActive>
                <label>Cannot Reproduce</label>
            </value>
            <value>
                <fullName>Client Infrastructure</fullName>
                <isActive>false</isActive>
                <label>Client Infrastructure</label>
            </value>
            <value>
                <fullName>Code / Logic</fullName>
                <isActive>false</isActive>
                <label>Code / Logic</label>
            </value>
            <value>
                <fullName>Configuration</fullName>
                <isActive>false</isActive>
                <label>Configuration</label>
            </value>
            <value>
                <fullName>Customer/Environment Specific</fullName>
            </value>
            <value>
                <fullName>Customer Abandoned</fullName>
            </value>
            <value>
                <fullName>Customer Found Solution(Referring KB)</fullName>
            </value>
            <value>
                <fullName>Enhancement Request</fullName>
            </value>
            <value>
                <fullName>Fixed</fullName>
                <isActive>false</isActive>
                <label>Fixed</label>
            </value>
            <value>
                <fullName>Hardware Failure</fullName>
                <isActive>false</isActive>
                <label>Hardware Failure</label>
            </value>
            <value>
                <fullName>How To</fullName>
                <isActive>false</isActive>
                <label>How To</label>
            </value>
            <value>
                <fullName>Incomplete</fullName>
                <isActive>false</isActive>
                <label>Incomplete</label>
            </value>
            <value>
                <fullName>Known Issue</fullName>
                <isActive>false</isActive>
                <label>Known Issue</label>
            </value>
            <value>
                <fullName>No Response from Customer</fullName>
                <isActive>false</isActive>
                <label>No Response from Customer</label>
            </value>
            <value>
                <fullName>Product Limitation</fullName>
                <isActive>false</isActive>
                <label>Product Limitation</label>
            </value>
            <value>
                <fullName>Resolved</fullName>
                <isActive>false</isActive>
                <label>Resolved</label>
            </value>
            <value>
                <fullName>Software Failure</fullName>
                <isActive>false</isActive>
                <label>Software Failure</label>
            </value>
            <value>
                <fullName>Third Party</fullName>
                <isActive>false</isActive>
                <label>Third Party</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

uipath-service/main/default/objects/Case/fields/CSAT__c.field-meta.xml
<CustomField>
    <fullName>CSAT__c</fullName>
    <defaultValue>0.00</defaultValue>
    <label>CSAT</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

uipath-service/main/default/objects/Case/fields/Related_To__c.field-meta.xml
<CustomField>
    <fullName>Related_To__c</fullName>
    <label>Product Component</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Academic Alliance</fullName>
            </value>
            <value>
                <fullName>Academy</fullName>
            </value>
            <value>
                <fullName>Apps</fullName>
                <label>Action Center</label>
            </value>
            <value>
                <fullName>Activation</fullName>
                <isActive>false</isActive>
                <label>Activation</label>
            </value>
            <value>
                <fullName>Activities</fullName>
                <isActive>false</isActive>
                <label>Activities</label>
            </value>
            <value>
                <fullName>AI Capabilities</fullName>
                <isActive>false</isActive>
                <label>AI Capabilities</label>
            </value>
            <value>
                <fullName>AI Fabric</fullName>
            </value>
            <value>
                <fullName>Attended browser embedding SDK</fullName>
            </value>
            <value>
                <fullName>Cloud Platform</fullName>
                <label>Automation Cloud</label>
            </value>
            <value>
                <fullName>Connect Enterprise</fullName>
                <label>Automation Hub</label>
            </value>
            <value>
                <fullName>Automation Ready Programs</fullName>
            </value>
            <value>
                <fullName>Certification</fullName>
            </value>
            <value>
                <fullName>Document Understanding</fullName>
            </value>
            <value>
                <fullName>Feedback</fullName>
            </value>
            <value>
                <fullName>IT Automation</fullName>
            </value>
            <value>
                <fullName>Kibana</fullName>
                <isActive>false</isActive>
                <label>Kibana</label>
            </value>
            <value>
                <fullName>Learning Platform Inquiries</fullName>
            </value>
            <value>
                <fullName>Licensing</fullName>
                <label>License</label>
            </value>
            <value>
                <fullName>Orchestrator</fullName>
            </value>
            <value>
                <fullName>Orchestrator Mobile</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Others</fullName>
                <isActive>false</isActive>
                <label>Others</label>
            </value>
            <value>
                <fullName>Partner Product</fullName>
            </value>
            <value>
                <fullName>Partner Training</fullName>
            </value>
            <value>
                <fullName>Portal</fullName>
            </value>
            <value>
                <fullName>Process Gold</fullName>
                <label>Process Mining</label>
            </value>
            <value>
                <fullName>Reporting</fullName>
                <isActive>false</isActive>
                <label>Reporting</label>
            </value>
            <value>
                <fullName>Robot</fullName>
            </value>
            <value>
                <fullName>Studio</fullName>
            </value>
            <value>
                <fullName>Studio X</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

uipath-service/main/default/objects/Case/fields/Solution__c.field-meta.xml
<CustomField>
    <fullName>Solution__c</fullName>
    <inlineHelpText>Technical summary of the solution</inlineHelpText>
    <label>Solution</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

uipath-service/main/default/objects/Case/fields/Sub_Component__c.field-meta.xml
<CustomField>
    <fullName>Sub_Component__c</fullName>
    <label>Sub Component</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Related_To__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Abby</fullName>
            </value>
            <value>
                <fullName>Abbyy_FineReader</fullName>
            </value>
            <value>
                <fullName>Abbyy_FlexiCapture</fullName>
            </value>
            <value>
                <fullName>Academic Alliance</fullName>
            </value>
            <value>
                <fullName>Academic Alliance Edition</fullName>
            </value>
            <value>
                <fullName>Academy Trainings</fullName>
            </value>
            <value>
                <fullName>Account</fullName>
            </value>
            <value>
                <fullName>Account Inquiries</fullName>
            </value>
            <value>
                <fullName>Account Merger</fullName>
            </value>
            <value>
                <fullName>Activation</fullName>
            </value>
            <value>
                <fullName>Active Directory Domain Services Activities</fullName>
            </value>
            <value>
                <fullName>Activites_Keyword Based_Classifier Trainer</fullName>
            </value>
            <value>
                <fullName>Activities_Computer Vision</fullName>
            </value>
            <value>
                <fullName>Activities_Core</fullName>
            </value>
            <value>
                <fullName>Activities_Custom</fullName>
            </value>
            <value>
                <fullName>Activities_Database</fullName>
            </value>
            <value>
                <fullName>Activities_Excel</fullName>
            </value>
            <value>
                <fullName>Activities_FTP</fullName>
            </value>
            <value>
                <fullName>Activities_GoogleSutite</fullName>
                <label>Activities_GoogleSuite</label>
            </value>
            <value>
                <fullName>Activities_IT_Automation</fullName>
            </value>
            <value>
                <fullName>Activities_Java</fullName>
            </value>
            <value>
                <fullName>Activities_Mail</fullName>
            </value>
            <value>
                <fullName>Activities_OCR</fullName>
            </value>
            <value>
                <fullName>Activities_Office365</fullName>
            </value>
            <value>
                <fullName>Activities_Others</fullName>
            </value>
            <value>
                <fullName>Activities_PDF</fullName>
            </value>
            <value>
                <fullName>Activities_Python</fullName>
            </value>
            <value>
                <fullName>Activities_SalesforceConnector</fullName>
            </value>
            <value>
                <fullName>Activities_SAP_BAPI</fullName>
            </value>
            <value>
                <fullName>Activities_Terminal</fullName>
            </value>
            <value>
                <fullName>Others</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

uipath-service/main/default/classes/CaseCreateChildCaseQueueableTest.cls
@isTest
private class CaseCreateChildCaseQueueableTest {
  @isTest
  private static void createChildCaseQueueableTest() {
    Id incidentRecordTypeID = CaseMetadata.IncidentRecordType;

    User testUser = [SELECT Id FROM User WHERE Id = :UserInfo.getUserId()];
    System.runAs(testUser) {
      Group grp = new Group(Name = 'Product_Support_Queue', type = 'Queue');
      insert grp;
      QueuesObject queue = new QueueSObject(QueueID = grp.id, SobjectType = 'Case');
      insert queue;
    }

    Account a1 = new Account(
      Name = 'NewAccountABC',
      BillingCountry = 'United Kingdom',
      Industry = 'Others',
      LD_USE_DnB_Optimize__c = false
    );
    insert a1;

    Contact con = new Contact(
      FirstName = 'Testadasda',
      LastName = 'Test',
      Email = 'asdasdad.test@test.com',
      AccountId = a1.Id,
      MailingCountry = 'Australia',
      MailingState = '',
      Title = 'Test',
      LeadSource = 'Webinar'
    );
    insert con;

    Case cs = new Case(Subject = 'Test', RecordTypeId = incidentRecordTypeID, Status = 'New', CSAT__c = 1.00);
    insert cs;
    cs.Status = 'Closed';
    cs.Closure_Classification__c = '3rd Party not under support scope';
    cs.Related_To__c = 'AI Fabric';
    cs.Sub_Component__c = 'Others';
    cs.Solution__c = 'No solution. This is a test.';
    cs.SuppliedEmail = 'asdasdad.test@test.com';
    cs.ContactId = con.Id;
    cs.CSAT__c = 4.00;
    update cs;

    CaseCreateChildCaseQueueable createChildCaseQueueable = new CaseCreateChildCaseQueueable(new List<Case>{ cs });
    createChildCaseQueueable.execute(null);

    List<Case> children = [SELECT Id FROM Case WHERE ParentId = :cs.Id];
    System.assertEquals(1, children.size());
  }
}