uipath-commons/main/default/objects/Account/fields/CSM__c.field-meta.xml
<CustomField>
        <fullName>CSM__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Client Success Manager</description>
        <inlineHelpText>Select the Client Success Manager for this account</inlineHelpText>
        <label>CSM</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Accounts2</relationshipName>
        <type>Lookup</type>
    </CustomField>

uipath-commons/main/default/objects/Account/fields/Support_Technical_Advisor__c.field-meta.xml
<CustomField>
        <fullName>Support_Technical_Advisor__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Support Technical Advisor</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Support_Technical_Advisor</relationshipName>
        <type>Lookup</type>
    </CustomField>

uipath-commons/main/default/objects/Account/recordTypes/Customer.recordType-meta.xml
<RecordType>
    <fullName>Customer</fullName>
    <active>true</active>
    <description>Customer account, i.e., account of a company with purchase transactions</description>
    <label>Customer</label>
</RecordType>

uipath-service/main/default/objects/Case/fields/Account_CSM__c.field-meta.xml
<CustomField>
    <fullName>Account_CSM__c</fullName>
    <formula>Account.CSM__c</formula>
    <label>Account CSM</label>
    <type>Text</type>
</CustomField>

uipath-service/main/default/objects/Case/fields/Account_STA__c.field-meta.xml
<CustomField>
    <fullName>Account_STA__c</fullName>
    <formula>Account.Support_Technical_Advisor__c</formula>
    <label>Account STA</label>
    <type>Text</type>
</CustomField>

uipath-service/main/default/objects/Case/fields/No_of_Emails_Sent__c.field-meta.xml
<CustomField>
    <fullName>No_of_Emails_Sent__c</fullName>
    <label>No. of Emails Sent</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

uipath-service/main/default/objects/Case/recordTypes/Incident.recordType-meta.xml
<RecordType>
    <fullName>Incident</fullName>
    <active>true</active>
    <businessProcess>Service Request%2FIncident</businessProcess>
    <description>Ticket created to track faults or system error experienced by customer.</description>
    <label>Incident</label>
</RecordType>

uipath-service/main/default/classes/CaseTeamMemberQueueableTest.cls
@isTest
public class CaseTeamMemberQueueableTest {
  @TestSetup
  static void makeData() {
    Test.startTest();
    insertCaseTeamRole();
    Test.stopTest();
    Account account = new Account(Name = 'John');
    account.BillingStreet = 'Test Street';
    account.BillingCity = 'Test City';
    account.BillingPostalCode = 'SW1 3DWW';
    account.BillingCountry = 'United Kingdom';
    account.Phone = '1234567890';
    account.Industry = 'Others';
    Id userId;
    try {
      userId = [SELECT Id FROM User WHERE Profile.Name = 'Customer Success Manager' AND IsActive = true LIMIT 1].Id;
    } catch (Exception e) {
      userId = UserInfo.getUserId();
    }
    account.CSM__c = userId;
    account.Support_Technical_Advisor__c = userId;
    insert account;
  }

  @future
  private static void insertCaseTeamRole() {
    CaseTeamRole csmTeamRole = new CaseTeamRole();
    csmTeamRole.Name = CaseMetadata.CSM_ROLE;
    csmTeamRole.AccessLevel = 'Read';
    CaseTeamRole ctmTeamRole = new CaseTeamRole();
    ctmTeamRole.Name = CaseMetadata.CTM_ROLE;
    ctmTeamRole.AccessLevel = 'Edit';

    Database.insert(new List<CaseTeamRole>{ csmTeamRole, ctmTeamRole }, false);
  }

  static testMethod void addDefaultTeamMembers_onInsert() {
    Case incidentCase = new Case();
    incidentCase.RecordTypeId = CaseMetadata.IncidentRecordType;
    incidentCase.Subject = 'Incident Case';
    incidentCase.Status = 'New';
    incidentCase.AccountId = [SELECT Id FROM Account LIMIT 1].Id;
    incidentCase.No_of_Emails_Sent__c = 1;
    insert incidentCase;
    incidentCase = [SELECT Id, Account_CSM__c, Account_STA__c FROM Case];
    Test.startTest();
    new CaseTeamMemberQueueable(new List<Case>{ incidentCase }).work();
    Test.stopTest();
    System.assertEquals(1, [SELECT Id FROM CaseTeamMember].size(), 'Case Team members is inserted');
  }

  static testMethod void addDefaultTeamMembers_onUpdate() {
    Case incidentCase = new Case();
    incidentCase.RecordTypeId = CaseMetadata.IncidentRecordType;
    incidentCase.Subject = 'Incident Case';
    incidentCase.Status = 'New';
    incidentCase.No_of_Emails_Sent__c = 1;
    insert incidentCase;

    Test.startTest();
    incidentCase.AccountId = [SELECT Id FROM Account LIMIT 1].Id;
    update incidentCase;
    incidentCase = [SELECT Id, AccountId, Account_CSM__c, Account_STA__c FROM Case];
    CaseTeamMemberQueueable.addDefaultTeamMembers(
      new List<Case>{ incidentCase },
      new Map<Id, Case>{ incidentCase.Id => incidentCase }
    );
    new CaseTeamMemberQueueable(new List<Case>{ incidentCase }).work();
    Test.stopTest();
    System.assertEquals(1, [SELECT Id FROM CaseTeamMember].size(), 'Case Team members is updated');
  }
}