uipath-commons/main/default/objects/Account/fields/DnB_City__c.field-meta.xml
<CustomField>
        <fullName>DnB_City__c</fullName>
        <description>D&amp;B address will be synced to custom D&amp;B address fields on account. From there, they can be synced to the address object. These fields are hidden and used in the background for syncing logic.</description>
        <label>DnB City</label>
        <length>40</length>
        <type>Text</type>
    </CustomField>

uipath-commons/main/default/objects/Account/fields/DnB_Country__c.field-meta.xml
<CustomField>
        <fullName>DnB_Country__c</fullName>
        <label>DnB Country</label>
        <length>50</length>
        <type>Text</type>
    </CustomField>

uipath-commons/main/default/objects/Account/fields/DnB_State_Province__c.field-meta.xml
<CustomField>
    <fullName>DnB_State_Province__c</fullName>
    <label>DnB State/Province</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

uipath-commons/main/default/objects/Account/fields/DnB_Street__c.field-meta.xml
<CustomField>
        <fullName>DnB_Street__c</fullName>
        <description>D&amp;B address will be synced to custom D&amp;B address fields on account. From there, they can be synced to the address object. These fields are hidden and used in the background for syncing logic.</description>
        <label>DnB Street</label>
        <type>TextArea</type>
    </CustomField>

uipath-commons/main/default/objects/Account/fields/DnB_Zip_Postal_Code__c.field-meta.xml
<CustomField>
        <fullName>DnB_Zip_Postal_Code__c</fullName>
        <description>D&amp;B address will be synced to custom D&amp;B address fields on account. From there, they can be synced to the address object. These fields are hidden and used in the background for syncing logic.</description>
        <label>DnB Zip/Postal Code</label>
        <length>20</length>
        <type>Text</type>
    </CustomField>

uipath-commons/main/default/objects/Account/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <description>Used to sync with address object at account creation</description>
    <label>State</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Country__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>States_Global_List</valueSetName>
    </valueSet>
</CustomField>

uipath-commons/main/default/objects/Address__c/Address__c.object-meta.xml
<CustomObject>
    <description>Object to hold the Customer Address details</description>
    <label>Address</label>
    <nameField>
        <displayFormat>ADD-{000000}</displayFormat>
        <label>Address ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Addresses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

uipath-commons/main/default/objects/Address__c/fields/Account__c.field-meta.xml
<CustomField>
        <fullName>Account__c</fullName>
        <description>Parent Account</description>
        <inlineHelpText>Parent Account</inlineHelpText>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Addresses</relationshipLabel>
        <relationshipName>Addresses</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </CustomField>

uipath-commons/main/default/objects/Address__c/fields/City__c.field-meta.xml
<CustomField>
        <fullName>City__c</fullName>
        <description>City</description>
        <inlineHelpText>City</inlineHelpText>
        <label>City</label>
        <length>40</length>
        <type>Text</type>
    </CustomField>

uipath-commons/main/default/objects/Address__c/fields/Primary_Billing__c.field-meta.xml
<CustomField>
        <fullName>Primary_Billing__c</fullName>
        <defaultValue>false</defaultValue>
        <description>To note the primary billing address on the Account</description>
        <inlineHelpText>Check the box if this is the primary billing address on the Account. Account can have only one primary billing Address at a time</inlineHelpText>
        <label>Primary Billing</label>
        <type>Checkbox</type>
    </CustomField>

uipath-commons/main/default/objects/Address__c/fields/State__c.field-meta.xml
<CustomField>
        <fullName>State__c</fullName>
        <description>State</description>
        <inlineHelpText>State</inlineHelpText>
        <label>State</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Country__c</controllingField>
            <restricted>true</restricted>
            <valueSetName>States_Global_List</valueSetName>
        </valueSet>
    </CustomField>

uipath-commons/main/default/objects/Address__c/fields/Street_Line_1__c.field-meta.xml
<CustomField>
        <fullName>Street_Line_1__c</fullName>
        <description>Address Street</description>
        <inlineHelpText>Address Street</inlineHelpText>
        <label>Street Line 1</label>
        <length>150</length>
        <type>Text</type>
    </CustomField>

uipath-commons/main/default/objects/Address__c/fields/Street_Line_2__c.field-meta.xml
<CustomField>
        <fullName>Street_Line_2__c</fullName>
        <description>Street Address</description>
        <inlineHelpText>Street Address Line 2</inlineHelpText>
        <label>Street Line 2</label>
        <length>105</length>
        <type>Text</type>
    </CustomField>

uipath-commons/main/default/objects/Address__c/fields/Zip_Postal_Code__c.field-meta.xml
<CustomField>
        <fullName>Zip_Postal_Code__c</fullName>
        <description>Zip/Postal Code</description>
        <inlineHelpText>Zip/Postal Code</inlineHelpText>
        <label>Zip/Postal Code</label>
        <length>20</length>
        <type>Text</type>
    </CustomField>

uipath-commons/main/default/globalValueSets/States_Global_List.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Acre</fullName>
    </customValue>
    <customValue>
        <fullName>Aguascalientes</fullName>
    </customValue>
    <customValue>
        <fullName>Alabama</fullName>
    </customValue>
    <customValue>
        <fullName>Alagoas</fullName>
    </customValue>
    <customValue>
        <fullName>Alaska</fullName>
    </customValue>
    <customValue>
        <fullName>Alberta</fullName>
    </customValue>
    <customValue>
        <fullName>Amapá</fullName>
    </customValue>
    <customValue>
        <fullName>Amazonas</fullName>
    </customValue>
    <customValue>
        <fullName>Andaman and Nicobar Islands</fullName>
    </customValue>
    <customValue>
        <fullName>Andhra Pradesh</fullName>
    </customValue>
    <customValue>
        <fullName>Anhui</fullName>
    </customValue>
    <customValue>
        <fullName>Arizona</fullName>
    </customValue>
    <customValue>
        <fullName>Arkansas</fullName>
    </customValue>
    <customValue>
        <fullName>Arunachal Pradesh</fullName>
    </customValue>
    <customValue>
        <fullName>Assam</fullName>
    </customValue>
    <customValue>
        <fullName>Bahia</fullName>
    </customValue>
    <customValue>
        <fullName>Baja California</fullName>
    </customValue>
    <customValue>
        <fullName>Baja California Sur</fullName>
    </customValue>
    <customValue>
        <fullName>Beijing</fullName>
    </customValue>
    <customValue>
        <fullName>Bihar</fullName>
    </customValue>
    <customValue>
        <fullName>British Columbia</fullName>
    </customValue>
    <customValue>
        <fullName>California</fullName>
    </customValue>
    <customValue>
        <fullName>Campeche</fullName>
    </customValue>
    <customValue>
        <fullName>Ceara</fullName>
    </customValue>
    <customValue>
        <fullName>Chandigarh</fullName>
    </customValue>
    <customValue>
        <fullName>Chhattisgarh</fullName>
    </customValue>
    <customValue>
        <fullName>Chiapas</fullName>
    </customValue>
    <customValue>
        <fullName>Chihuahua</fullName>
    </customValue>
    <customValue>
        <fullName>Chinese Taipei</fullName>
    </customValue>
    <customValue>
        <fullName>Chongqing</fullName>
    </customValue>
    <description>Created for the new Address object and will be used for other objects (involved in integration with NetSuite)</description>
    <masterLabel>States Global List</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet>

uipath-commons/main/default/classes/AccountDNBPrimaryAddressQueueable.cls
/**
 * Updates Primary address with all DnB address details
 */
public with sharing class AccountDNBPrimaryAddressQueueable extends AbstractQueueable {
  private final List<SObject> accountsLst;
  private final Map<Id, SObject> oldAccountsMap;

  public AccountDNBPrimaryAddressQueueable(List<SObject> accountsLst, Map<Id, SObject> oldAccountsMap) {
    super('AccountDNBPrimaryAddressQueueable');
    this.accountsLst = accountsLst;
    this.oldAccountsMap = oldAccountsMap;
  }

  public override void work() {
    this.processDNBAddress(this.accountsLst, oldAccountsMap);
  }

  /**

     */
  private void processDNBAddress(List<SObject> accountList, Map<Id, SObject> oldAccountsMap) {
    Map<Id, Address__c> addressMap = getAddresses(accountList);

    List<Address__c> addressToUpdate = new List<Address__c>();
    for (Account acc : (List<Account>) accountList) {
      Account oldAccount = (Account) oldAccountsMap.get(acc.Id);
      if (addressMap.containsKey(acc.Id)) {
        Address__c address = addressMap.get(acc.Id);
        //Only run the first time the D&B account/address is set
        Address__c comlpetedaddress = null;
        if (String.IsNotBlank(acc.DnB_City__c) && String.IsBlank(oldAccount.DnB_City__c)) {
          comlpetedaddress = populateAddress(acc, address);
          comlpetedaddress.RecordTypeId = Schema.SObjectType.Address__c.getRecordTypeInfosByDeveloperName()
            .get(CommonsConstants.ADDRESS_RECORD_TYPE_LOCKDOWN)
            .getRecordTypeId();
        }

        if (comlpetedaddress != null)
          addressToUpdate.add(comlpetedaddress);
      }
    }
    update addressToUpdate;
  }

  private Address__c populateAddress(Account acc, Address__c address) {
    address.City__c = acc.DnB_City__c;
    if (String.IsNotBlank(acc.DnB_Street__c)) {
      if (String.IsBlank(address.State__c) && String.IsNotBlank(acc.DnB_State_Province__c)) {
        address.State__c = acc.DnB_State_Province__c;
      }
      address.Street_Line_1__c = acc.DnB_Street__c.left(150);
      if (acc.DnB_Street__c.length() > 150) {
        address.Street_Line_2__c = acc.DnB_Street__c.substring(150, acc.DnB_Street__c.length());
      }
    }
    if (String.IsNotBlank(acc.DnB_Zip_Postal_Code__c)) {
      address.Zip_Postal_Code__c = acc.DnB_Zip_Postal_Code__c;
      if (acc.DnB_Country__c == 'United States') {
        address.Zip_Postal_Code__c = (acc.DnB_Zip_Postal_Code__c).left(5);
      }
    }
    return address;
  }

  private Map<Id, Address__c> getAddresses(List<Account> accList) {
    Map<Id, Address__c> addressMap = new Map<Id, Address__c>();

    List<Address__c> addressList = [
      SELECT Id, Account__c, State__c, Street_Line_1__c, Street_Line_2__c, City__c, Zip_Postal_Code__c
      FROM Address__c
      WHERE Account__c IN :accList AND Primary_Billing__c = true AND City__c = null
    ];

    for (Address__c addr : addressList) {
      if (!addressMap.containsKey(addr.Account__c)) {
        addressMap.put(addr.Account__c, addr);
      }
    }
    return addressMap;
  }
  /**
   * create an address record for when an account is updated using D&B address
   * @param existingRecords
   */
  public static void updateAddressForDnBCompany(List<Account> accounts, Map<Id, SObject> existingAccounts) {
    SObjectPredicate hasChanged = new HasRecordChanged(
      new Set<SObjectField>{ Account.DnB_City__c, Account.DnB_Street__c, Account.DnB_Zip_Postal_Code__c },
      accounts,
      existingAccounts
    );
    List<Account> eligibleAccounts = (List<Account>) Collection.of(accounts)
      .filter(Match.field(Account.DnB_City__c).hasValue())
      .filter(hasChanged)
      .asList();

    if (!eligibleAccounts.isEmpty()) {
      AbstractQueueable.enqueue(new AccountDNBPrimaryAddressQueueable(eligibleAccounts, existingAccounts));
    }
  }
}