uipath-commons/main/default/objects/Account/fields/Geo__c.field-meta.xml
<CustomField>
        <fullName>Geo__c</fullName>
        <label>Geo</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>AMER</fullName>
                </value>
                <value>
                    <fullName>APAC</fullName>
                </value>
                <value>
                    <fullName>EMEA</fullName>
                </value>
                <value>
                    <fullName>Japan</fullName>
                </value>
                <value>
                    <fullName>India</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </CustomField>

uipath-commons/main/default/objects/Account/fields/Region__c.field-meta.xml
<CustomField>
    <fullName>Region__c</fullName>
    <label>Region</label>
    
        <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>ANZ</fullName>
            </value>
            <value>
                <fullName>BFS</fullName>
            </value>
            <value>
                <fullName>Canada</fullName>
            </value>
            <value>
                <fullName>Greater China</fullName>
            </value>
            <value>
                <fullName>GOV</fullName>
            </value>
            <value>
                <fullName>India</fullName>
            </value>
            <value>
                <fullName>Korea</fullName>
            </value>
            <value>
                <fullName>LATAM</fullName>
            </value>
            <value>
                <fullName>MEA</fullName>
            </value>
            <value>
                <fullName>Nordics</fullName>
            </value>
            <value>
                <fullName>NorthCentral</fullName>
            </value>
            <value>
                <fullName>NorthEast</fullName>
            </value>
            <value>
                <fullName>NorthWest</fullName>
            </value>
            <value>
                <fullName>Others</fullName>
            </value>
            <value>
                <fullName>SEA</fullName>
            </value>
            <value>
                <fullName>SouthWest</fullName>
            </value>
            <value>
                <fullName>SouthCentral</fullName>
            </value>
            <value>
                <fullName>SouthEast</fullName>
            </value>
            <value>
                <fullName>UKI</fullName>
            </value>
            <value>
                <fullName>CE</fullName>
            </value>
            <value>
                <fullName>EECIS</fullName>
            </value>
            <value>
                <fullName>France</fullName>
            </value>
            <value>
                <fullName>Italy/Greece</fullName>
            </value>
            <value>
                <fullName>Iberia</fullName>
            </value>
            <value>
                <fullName>Benelux</fullName>
            </value>
            <value>
                <fullName>Japan</fullName>
            </value>
            <value>
                <fullName>Hokkaido</fullName>
            </value>
            <value>
                <fullName>Tohoku</fullName>
            </value>
            <value>
                <fullName>Kanto</fullName>
            </value>
            <value>
                <fullName>Chubu</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

uipath-commons/main/default/objects/Account/fields/Region_Specific__c.field-meta.xml
<CustomField>
        <fullName>Region_Specific__c</fullName>
        <label>Region Specific</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Enterprise Tier 1</fullName>
                </value>
                <value>
                    <fullName>Enterprise Tier 2</fullName>
                </value>
                <value>
                    <fullName>Enterprise Tier 3</fullName>
                </value>
                <value>
                    <fullName>Velocity Tier 1</fullName>
                </value>
                <value>
                    <fullName>Velocity Tier 2</fullName>
                </value>
                <value>
                    <fullName>Velocity Tier 3</fullName>
                </value>
                <value>
                    <fullName>BPO Accounts</fullName>
                </value>
                <value>
                    <fullName>India Business</fullName>
                </value>
                <value>
                    <fullName>Government</fullName>
                </value>
                <value>
                    <fullName>SOE</fullName>
                </value>
                <value>
                    <fullName>MNC</fullName>
                </value>
                <value>
                    <fullName>Commercial</fullName>
                </value>
                <value>
                    <fullName>Private</fullName>
                </value>
                <value>
                    <fullName>Joint Venture</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </CustomField>

uipath-commons/main/default/classes/AccountSetRegionSpecificTierFunction.cls
public with sharing class AccountSetRegionSpecificTierFunction implements SObjectToSObjectFunction {
  /**
   * Set Region Specific Field based on Tier level
   * *ProcessBuilder clean-up: Acc Segmentation - Update Reg Specific
   */
  public SObject apply(Account acc) {
    if (
      acc.Geo__c == 'AMER' &&
      acc.Region__c != 'Canada' &&
      acc.Region__c != 'LATAM'
    ) {
      // Enterprise Tier 3 - AMER
      if (
        acc.AnnualRevenue >= 1000000000.00 &&
        ((acc.NumberOfEmployees < 1000 &&
        acc.AnnualRevenue < 6000000000.00) ||
        (acc.NumberOfEmployees >= 1000 &&
        acc.NumberOfEmployees < 3000 &&
        acc.AnnualRevenue < 4000000000.00) ||
        (acc.NumberOfEmployees >= 3000 &&
        acc.NumberOfEmployees < 5000 &&
        acc.AnnualRevenue < 2000000000.00))
      ) {
        acc.Region_Specific__c = 'Enterprise Tier 3';
      } else if (
        (acc.NumberOfEmployees < 1000 &&
        acc.AnnualRevenue >= 6000000000.00) ||
        (acc.NumberOfEmployees >= 1000 &&
        acc.NumberOfEmployees < 3000 &&
        acc.AnnualRevenue >= 4000000000.00 &&
        acc.AnnualRevenue < 10000000000.00) ||
        (acc.NumberOfEmployees >= 3000 &&
        acc.NumberOfEmployees < 5000 &&
        acc.AnnualRevenue >= 2000000000.00 &&
        acc.AnnualRevenue < 10000000000.00) ||
        (acc.NumberOfEmployees >= 5000 &&
        acc.NumberOfEmployees < 10000 &&
        acc.AnnualRevenue >= 1000000000.00 &&
        acc.AnnualRevenue < 6000000000.00) ||
        (acc.NumberOfEmployees >= 10000 &&
        acc.AnnualRevenue >= 1000000000.00 &&
        acc.AnnualRevenue < 4000000000.00)
      ) {
        // Enterprise Tier 2 - AMER
        acc.Region_Specific__c = 'Enterprise Tier 2';
      } else if (
        (acc.NumberOfEmployees >= 1000 &&
        acc.NumberOfEmployees < 5000 &&
        acc.AnnualRevenue >= 10000000000.00) ||
        (acc.NumberOfEmployees >= 5000 &&
        acc.NumberOfEmployees < 10000 &&
        acc.AnnualRevenue >= 6000000000.00) ||
        (acc.NumberOfEmployees >= 10000 &&
        acc.AnnualRevenue >= 4000000000.00)
      ) {
        // Enterprise Tier 1 - AMER
        acc.Region_Specific__c = 'Enterprise Tier 1';
      } else if (
        acc.AnnualRevenue >= 1.00 &&
        ((acc.NumberOfEmployees < 1000 &&
        acc.AnnualRevenue < 650000000.00) ||
        (acc.NumberOfEmployees >= 1000 &&
        acc.NumberOfEmployees < 2000 &&
        acc.AnnualRevenue < 500000000.00) ||
        (acc.NumberOfEmployees >= 2000 &&
        acc.NumberOfEmployees < 3500 &&
        acc.AnnualRevenue < 250000000.00))
      ) {
        // Velocity Tier 3 - AMER
        acc.Region_Specific__c = 'Velocity Tier 3';
      } else if (
        (acc.NumberOfEmployees < 1000 &&
        acc.AnnualRevenue >= 650000000.00 &&
        acc.AnnualRevenue < 1000000000.00) ||
        (acc.NumberOfEmployees >= 1000 &&
        acc.NumberOfEmployees < 2000 &&
        acc.AnnualRevenue >= 500000000.00 &&
        acc.AnnualRevenue < 750000000.00) ||
        (acc.NumberOfEmployees >= 2000 &&
        acc.NumberOfEmployees < 3500 &&
        acc.AnnualRevenue >= 250000000.00 &&
        acc.AnnualRevenue < 750000000.00) ||
        (acc.NumberOfEmployees >= 3500 &&
        acc.NumberOfEmployees < 5000 &&
        acc.AnnualRevenue >= 1.00 &&
        acc.AnnualRevenue < 650000000.00) ||
        (acc.NumberOfEmployees >= 5000 &&
        acc.AnnualRevenue >= 1.00 &&
        acc.AnnualRevenue < 500000000.00)
      ) {
        // Velocity Tier 2 - AMER
        acc.Region_Specific__c = 'Velocity Tier 2';
      } else if (
        (acc.NumberOfEmployees >= 1000 &&
        acc.NumberOfEmployees < 3500 &&
        acc.AnnualRevenue >= 750000000.00 &&
        acc.AnnualRevenue < 1000000000.00) ||
        (acc.NumberOfEmployees >= 3500 &&
        acc.NumberOfEmployees < 5000 &&
        acc.AnnualRevenue >= 650000000.00 &&
        acc.AnnualRevenue < 1000000000.00) ||
        (acc.NumberOfEmployees >= 5000 &&
        acc.AnnualRevenue >= 500000000.00 &&
        acc.AnnualRevenue < 1000000000.00)
      ) {
        // Velocity Tier 1 - AMER
        acc.Region_Specific__c = 'Velocity Tier 1';
      }
    }
    return acc;
  }

  public SObject apply(SObject record) {
    return apply((Account) record);
  }
}