uipath-commons/main/default/objects/Account/fields/LD_USE_DnB_Optimize__c.field-meta.xml
<CustomField>
    <fullName>LD_USE_DnB_Optimize__c</fullName>
    <defaultValue>true</defaultValue>
    <description>“Checked” will allow a match from Optimizer, where an “Unchecked” box will exclude the record
from matching.</description>
    <label>Allow D&amp;B Optimizer</label>
    <type>Checkbox</type>
</CustomField>

uipath-commons/main/default/objects/Account/fields/Sync_Status__c.field-meta.xml
<CustomField>
    <fullName>Sync_Status__c</fullName>
    <description>Indicated the status of the product against integration</description>
    <inlineHelpText>Not Valid - default sync status for new records
Valid - Ready to be synced to NetSuite
Pending - Updates on record ready to be synced to NetSuite
Synced - Synced to NetSuite
Error - Error while syncing
Do Not Sync - Archive from syncing</inlineHelpText>
    <label>Sync Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Sync_Status</valueSetName>
    </valueSet>
</CustomField>

uipath-commons/main/default/objects/Account/fields/Validation_Status__c.field-meta.xml
<CustomField>
    <fullName>Validation_Status__c</fullName>
    <description>Used by the Data Stewards to flag the Account validation status</description>
    <inlineHelpText>When Data Stewards set the status to &quot;Validated&quot; call to boomi integration will be made</inlineHelpText>
    <label>Validation Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Data_Steward_Validation_Status</valueSetName>
    </valueSet>
</CustomField>

uipath-commons/main/default/globalValueSets/Data_Steward_Validation_Status.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>In Review</fullName>
    </customValue>
    <customValue>
        <fullName>Pending</fullName>
        <default>true</default>
        <label>Pending</label>
    </customValue>
    <customValue>
        <fullName>Ready For Review</fullName>
    </customValue>
    <customValue>
        <fullName>Review Complete</fullName>
    </customValue>
    <customValue>
        <fullName>Validated</fullName>
    </customValue>
    <description>Validation Status values to be used by the Data Stewards on Accounts, Addresses etc</description>
    <masterLabel>Data Steward Validation Status</masterLabel>
</GlobalValueSet>

uipath-commons/main/default/globalValueSets/Sync_Status.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Do Not Sync</fullName>
    </customValue>
    <customValue>
        <fullName>Error</fullName>
    </customValue>
    <customValue>
        <fullName>Not Valid</fullName>
        <default>true</default>
        <label>Not Valid</label>
    </customValue>
    <customValue>
        <fullName>Pending</fullName>
    </customValue>
    <customValue>
        <fullName>Synced</fullName>
    </customValue>
    <customValue>
        <fullName>Valid</fullName>
    </customValue>
    <description>Sync Status used to maintain various integration status</description>
    <masterLabel>Sync Status</masterLabel>
</GlobalValueSet>

uipath-commons/main/default/classes/AccountIntegrationServiceTest.cls
@IsTest
public with sharing class AccountIntegrationServiceTest {
  @IsTest
  public static void publishesInsertsToNetsuite() {
    Account acc = new Account(
      Name = 'Test 1',
      BillingCountry = 'United Kingdom',
      Industry = 'Others',
      LD_USE_DnB_Optimize__c = false,
      Sync_Status__c = CommonsConstants.ACC_SYNC_STATUS_VALID
    );

    //Set to force a sync publish - which normally happens via a queueable
    OrchestratorNotifierQueueable.forceSyncMode = true;
    insert acc;

    System.assertEquals(
      true,
      [SELECT Id, UiPath__Details__c FROM UiPath__UiPathLog__c LIMIT 1]
        .UiPath__Details__c.contains(CommonsConstants.ACC_UIPATH_SF_CONNECTOR_TEMPLATE),
      'There should be a publish attempt in the logs'
    );
  }

  @IsTest
  public static void publishesUpdatesToNetsuite() {
    Account acc = new Account(
      Name = 'Test 1',
      BillingCountry = 'United Kingdom',
      Industry = 'Others',
      LD_USE_DnB_Optimize__c = false,
      Validation_Status__c = CommonsConstants.ACC_VALIDATION_STATUS_VALIDATED
    );

    //Set to force a sync publish - which normally happens via a queueable
    insert acc;

    acc.BillingCountry = 'India';
    acc.Sync_Status__c = CommonsConstants.ACC_SYNC_STATUS_VALID;

    OrchestratorNotifierQueueable.forceSyncMode = true;
    update acc;

    System.assertEquals(
      true,
      [SELECT Id, UiPath__Details__c FROM UiPath__UiPathLog__c LIMIT 1]
        .UiPath__Details__c.contains(CommonsConstants.ACC_UIPATH_SF_CONNECTOR_TEMPLATE),
      'There should be a publish attempt in the logs'
    );
  }
}