uipath-commons/main/default/objects/Account/fields/Legal__c.field-meta.xml
<CustomField>
        <fullName>Legal__c</fullName>
        <label>Legal  Entity Name</label>
        <length>200</length>
        <type>Text</type>
    </CustomField>

uipath-commons/main/default/objects/Account/fields/Overwrite_Annual_Revenue__c.field-meta.xml
<CustomField>
    <fullName>Overwrite_Annual_Revenue__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Used to exclude accounts from being updated with revenue from D&amp;B</description>
    <inlineHelpText>SLTECH-251</inlineHelpText>
    <label>Overwrite Annual Revenue</label>
    <type>Checkbox</type>
</CustomField>

uipath-commons/main/default/objects/Account/fields/Overwrite_Legal_Entity_Name__c.field-meta.xml
<CustomField>
        <fullName>Overwrite_Legal_Entity_Name__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Used by Data Stewards</inlineHelpText>
        <label>Overwrite Legal Entity Name</label>
        <type>Checkbox</type>
    </CustomField>

uipath-commons/main/default/objects/Account/fields/Revenue_Source__c.field-meta.xml
<CustomField>
    <fullName>Revenue_Source__c</fullName>
    <label>Revenue Source</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Dun &amp; Bradstreet</fullName>
            </value>
            <value>
                <fullName>Discover.org</fullName>
            </value>
            <value>
                <fullName>Company Website</fullName>
            </value>
            <value>
                <fullName>Public / Regulatory filing</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

uipath-commons/main/default/classes/AccountDnBSyncQueueable.cls
public with sharing class AccountDnBSyncQueueable extends AbstractQueueable {
  /**
   * Set Revenue Source field on Account
   * If Account AnnualRevenue is equal to DNBoptimizer__DnBCompanyRecord__r.DNBoptimizer__SalesVolumeUSDollars__c populates Revenue Source with Dun & Bradstreet
   */

  public virtual class HasMetDnBQueueableCriteria implements SObjectPredicate {
    List<SObject> validatedAccounts = new List<SObject>();
  
    public HasMetDnBQueueableCriteria(List<SObject> records) {
      validatedAccounts.addAll(
        Collection.of(records)
          .filter(
            Match.field(Account.AnnualRevenue)
              .equals(null)
              .also(Account.DNBoptimizer__DnBCompanyRecord__c)
              .hasValue()
              .also(Account.Overwrite_Annual_Revenue__c)
              .equals(false)
          )
          .asList()
      );
  
      validatedAccounts.addAll(
        Collection.of(records)
          .filter(
            Match.field(Account.Revenue_Source__c)
              .equals(null)
              .also(Account.DNBoptimizer__DnBCompanyRecord__c)
              .hasValue()
          )
          .asList()
      );
  
      validatedAccounts.addAll(
        Collection.of(records)
          .filter(
            Match.field(Account.Legal__c)
              .equals(null)
              .also(Account.DNBoptimizer__DnBCompanyRecord__c)
              .hasValue()
              .also(Account.Overwrite_Legal_Entity_Name__c)
              .equals(false)
          )
          .asList()
      );
    }
  
    public Boolean apply(SObject record) {
      return !validatedAccounts.isEmpty();
    }
  }  

  private final List<SObject> accountsLst;

  public AccountDnBSyncQueueable(List<SObject> accountsLst) {
    super('AccountDnBSyncQueueable');
    this.accountsLst = accountsLst;
  }

  public override void work() {
    this.setDnBFields(this.accountsLst);
  }

  private void setDnBFields(List<SObject> accountsLst) {
    List<Account> accounts = (List<Account>) accountsLst;
    accounts = [
      SELECT
        Id,
        Overwrite_Annual_Revenue__c,
        Overwrite_Legal_Entity_Name__c,
        Revenue_Source__c,
        AnnualRevenue,
        Legal__c,
        DNBoptimizer__DnBCompanyRecord__r.DNBoptimizer__BusinessName__c,
        DNBoptimizer__DnBCompanyRecord__r.DNBoptimizer__SalesVolumeUSDollars__c
      FROM Account
      WHERE Id IN :accounts AND DNBoptimizer__DnBCompanyRecord__c != null
    ];

    if (!accounts.isEmpty()) {
      for (Account acc : accounts) {
        if (
          acc.DNBoptimizer__DnBCompanyRecord__r.DNBoptimizer__SalesVolumeUSDollars__c !=
          null &&
          acc.AnnualRevenue == null &&
          acc.Overwrite_Annual_Revenue__c == false
        ) {
          acc.AnnualRevenue = acc.DNBoptimizer__DnBCompanyRecord__r.DNBoptimizer__SalesVolumeUSDollars__c;
          acc.Revenue_Source__c = 'Dun & Bradstreet';
        }

        if (
          acc.Revenue_Source__c == null &&
          acc.DNBoptimizer__DnBCompanyRecord__r.DNBoptimizer__SalesVolumeUSDollars__c ==
          acc.AnnualRevenue
        ) {
          acc.Revenue_Source__c = 'Dun & Bradstreet';
        }

        if (
          acc.DNBoptimizer__DnBCompanyRecord__r.DNBoptimizer__BusinessName__c !=
          null &&
          acc.Legal__c == null &&
          acc.Overwrite_Legal_Entity_Name__c == false
        ) {
          acc.Legal__c = acc.DNBoptimizer__DnBCompanyRecord__r.DNBoptimizer__BusinessName__c;
        }
      }
      update accounts;
    }
  }
}