uipath-commons/main/default/objects/Account/fields/Legal__c.field-meta.xml
<CustomField>
        <fullName>Legal__c</fullName>
        <label>Legal  Entity Name</label>
        <length>200</length>
        <type>Text</type>
    </CustomField>

uipath-commons/main/default/objects/Account/fields/Overwrite_Annual_Revenue__c.field-meta.xml
<CustomField>
    <fullName>Overwrite_Annual_Revenue__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Used to exclude accounts from being updated with revenue from D&amp;B</description>
    <inlineHelpText>SLTECH-251</inlineHelpText>
    <label>Overwrite Annual Revenue</label>
    <type>Checkbox</type>
</CustomField>

uipath-commons/main/default/objects/Account/fields/Overwrite_Legal_Entity_Name__c.field-meta.xml
<CustomField>
        <fullName>Overwrite_Legal_Entity_Name__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Used by Data Stewards</inlineHelpText>
        <label>Overwrite Legal Entity Name</label>
        <type>Checkbox</type>
    </CustomField>

uipath-commons/main/default/objects/Account/fields/Revenue_Source__c.field-meta.xml
<CustomField>
    <fullName>Revenue_Source__c</fullName>
    <label>Revenue Source</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Dun &amp; Bradstreet</fullName>
            </value>
            <value>
                <fullName>Discover.org</fullName>
            </value>
            <value>
                <fullName>Company Website</fullName>
            </value>
            <value>
                <fullName>Public / Regulatory filing</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

uipath-commons/main/default/classes/HasMetDnBQueueableCriteria.cls
public class HasMetDnBQueueableCriteria implements SObjectPredicate {
  List<SObject> validatedAccounts = new List<SObject>();

  public HasMetDnBQueueableCriteria(List<SObject> records) {
    validatedAccounts.addAll(
      Collection.of(records)
        .filter(
          Match.field(Account.AnnualRevenue)
            .equals(null)
            .also(Account.DNBoptimizer__DnBCompanyRecord__c)
            .hasValue()
            .also(Account.Overwrite_Annual_Revenue__c)
            .equals(false)
        )
        .asList()
    );

    validatedAccounts.addAll(
      Collection.of(records)
        .filter(
          Match.field(Account.Revenue_Source__c)
            .equals(null)
            .also(Account.DNBoptimizer__DnBCompanyRecord__c)
            .hasValue()
        )
        .asList()
    );

    validatedAccounts.addAll(
      Collection.of(records)
        .filter(
          Match.field(Account.Legal__c)
            .equals(null)
            .also(Account.DNBoptimizer__DnBCompanyRecord__c)
            .hasValue()
            .also(Account.Overwrite_Legal_Entity_Name__c)
            .equals(false)
        )
        .asList()
    );
  }

  public Boolean apply(SObject record) {
    return !validatedAccounts.isEmpty();
  }
}