uipath-commons/main/default/objects/Account/fields/Legal__c.field-meta.xml
<CustomField>
        <fullName>Legal__c</fullName>
        <label>Legal  Entity Name</label>
        <length>200</length>
        <type>Text</type>
    </CustomField>

uipath-commons/main/default/objects/Account/fields/Overwrite_Annual_Revenue__c.field-meta.xml
<CustomField>
    <fullName>Overwrite_Annual_Revenue__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Used to exclude accounts from being updated with revenue from D&amp;B</description>
    <inlineHelpText>SLTECH-251</inlineHelpText>
    <label>Overwrite Annual Revenue</label>
    <type>Checkbox</type>
</CustomField>

uipath-commons/main/default/objects/Account/fields/Revenue_Source__c.field-meta.xml
<CustomField>
    <fullName>Revenue_Source__c</fullName>
    <label>Revenue Source</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Dun &amp; Bradstreet</fullName>
            </value>
            <value>
                <fullName>Discover.org</fullName>
            </value>
            <value>
                <fullName>Company Website</fullName>
            </value>
            <value>
                <fullName>Public / Regulatory filing</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

uipath-commons/main/default/classes/AccountDnBSyncQueueableTest.cls
/**
 * TODO REWRITE with fflib Mocking
 */
@isTest
private class AccountDnBSyncQueueableTest {
  @isTest
  private static void setDnBSyncQueueableTest() {
    DNBoptimizer__DnBCompanyRecord__c dnbCompanyRecord = new DNBoptimizer__DnBCompanyRecord__c(
      DNBoptimizer__BusinessName__c = 'DnBTest1',
      Name = '1234',
      DNBoptimizer__SalesVolumeUSDollars__c = 150000000.00
    );

    insert dnbCompanyRecord;

    Account account1 = new Account(
      Name = 'Test1',
      BillingCountry = 'China',
      Industry = 'Apparel',
      Revenue_Source__c = null,
      Legal__c = null,
      DNBoptimizer__DnBCompanyRecord__c = dnbCompanyRecord.Id,
      AnnualRevenue = null,
      Overwrite_Annual_Revenue__c = false
    );
    insert account1;

    AccountDnBSyncQueueable accSetAnnualRevenueQueueable = new AccountDnBSyncQueueable(
      new List<SObject>{ account1 }
    );
    accSetAnnualRevenueQueueable.execute(null);

    List<Account> updatedAccount = [
      SELECT Id, AnnualRevenue
      FROM Account
      WHERE Id = :account1.Id
      LIMIT 1
    ];

    System.assertEquals(150000000.00, updatedAccount[0].AnnualRevenue);
  }
}