uipath-commons/main/default/objects/Account/fields/Max_of_Services_Quarter__c.field-meta.xml
<CustomField>
        <fullName>Max_of_Services_Quarter__c</fullName>
        <formula>IF(Sum_of_Open_Renewals__c &lt; 100000, 6,  
IF((Sum_of_Open_Renewals__c &gt;= 100000 &amp;&amp; Sum_of_Open_Renewals__c &lt; 200000), 12,  
IF((Sum_of_Open_Renewals__c &gt;=200000 &amp;&amp; Sum_of_Open_Renewals__c &lt; 500000), 18, 
IF((Sum_of_Open_Renewals__c &gt;= 500000 &amp;&amp; Sum_of_Open_Renewals__c &lt; 750000), 30, 
IF((Sum_of_Open_Renewals__c &gt;= 750000 &amp;&amp; Sum_of_Open_Renewals__c &lt; 1000000),42, 
IF(Sum_of_Open_Renewals__c &gt;= 1000000, 60, 0) ) ) ) ) )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Available Requests</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </CustomField>

uipath-commons/main/default/objects/Account/fields/of_Proactive_services__c.field-meta.xml
<CustomField>
    <fullName>of_Proactive_services__c</fullName>
    <label># of Proactive services/ quarter</label>
    <precision>11</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

uipath-commons/main/default/objects/Account/fields/requests_this_quarter__c.field-meta.xml
<CustomField>
        <fullName>requests_this_quarter__c</fullName>
        <label>Requests Consumed</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </CustomField>

uipath-service/main/default/classes/AccountProactiveServiceQueueable.cls
/**
 * TODO REWRITE
 * Move to Service Layer
 * this code was just moved here from the sync Trigger context into a Queueable Context.
 * Needs to be rewritten entirely
 * Updates the Proactive Request service count
 */
public with sharing class AccountProactiveServiceQueueable extends AbstractQueueable {
  private final List<SObject> cases;

  public AccountProactiveServiceQueueable(List<SObject> cases) {
    super('AccountProactiveServiceQueueable');
    this.cases = cases;
  }

  public override void work() {
    this.validateAndUpdateCounter(this.cases);
  }

  private void validateAndUpdateCounter(List<SObject> cases) {
    User newUser = [
      SELECT
        Id,
        ContactId,
        Account.of_Proactive_services__c,
        Account.Max_of_Services_Quarter__c,
        Account.requests_this_quarter__c,
        AccountId
      FROM User
      WHERE Id = :Userinfo.getUserId()
    ];

    if (newUser.ContactId == null) {
      return;
    }

    List<Account> accountsToUpdate = new List<Account>();
    for (Case newCase : (List<Case>) cases) {
      if (newCase.RecordtypeId != CaseMetadata.ProactiveCareRecordType) {
        continue;
      }
      if (nullAsZero(newUser.Account.requests_this_quarter__c) >= newUser.Account.Max_of_Services_Quarter__c) {
        throw new DMLException(
          'You cannot create a Proactive Service for this quarter as you have already availed the new case for this quarter.'
        );
      }
      Account account = new Account();
      account.Id = newUser.AccountId;
      account.of_Proactive_services__c = nullAsZero(newUser.Account.of_Proactive_services__c) + 5;
      account.requests_this_quarter__c = nullAsZero(newUser.Account.requests_this_quarter__c) + 1;
      accountsToUpdate.add(account);
    }
    if (!accountsToUpdate.isEmpty()) {
      update accountsToUpdate;
    }
  }

  private static Decimal nullAsZero(Decimal value) {
    return (value == null) ? 0 : value;
  }
}