uipath-commons/main/default/objects/Account/fields/Max_of_Services_Quarter__c.field-meta.xml
<CustomField>
        <fullName>Max_of_Services_Quarter__c</fullName>
        <formula>IF(Sum_of_Open_Renewals__c &lt; 100000, 6,  
IF((Sum_of_Open_Renewals__c &gt;= 100000 &amp;&amp; Sum_of_Open_Renewals__c &lt; 200000), 12,  
IF((Sum_of_Open_Renewals__c &gt;=200000 &amp;&amp; Sum_of_Open_Renewals__c &lt; 500000), 18, 
IF((Sum_of_Open_Renewals__c &gt;= 500000 &amp;&amp; Sum_of_Open_Renewals__c &lt; 750000), 30, 
IF((Sum_of_Open_Renewals__c &gt;= 750000 &amp;&amp; Sum_of_Open_Renewals__c &lt; 1000000),42, 
IF(Sum_of_Open_Renewals__c &gt;= 1000000, 60, 0) ) ) ) ) )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Available Requests</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </CustomField>

uipath-commons/main/default/objects/Account/fields/of_Proactive_services__c.field-meta.xml
<CustomField>
    <fullName>of_Proactive_services__c</fullName>
    <label># of Proactive services/ quarter</label>
    <precision>11</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

uipath-commons/main/default/objects/Account/fields/requests_this_quarter__c.field-meta.xml
<CustomField>
        <fullName>requests_this_quarter__c</fullName>
        <label>Requests Consumed</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </CustomField>

uipath-commons/main/default/objects/Account/recordTypes/Partner.recordType-meta.xml
<RecordType>
    <fullName>Partner</fullName>
    <active>true</active>
    <description>UiPath prospective or existing Partner Account</description>
    <label>Partner</label>
</RecordType>

uipath-service/main/default/objects/Case/fields/Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Start_Date__c</fullName>
    <inlineHelpText>Please allow us 15 days to plan and decide on the next course of action</inlineHelpText>
    <label>Start Date</label>
    <type>Date</type>
</CustomField>

uipath-service/main/default/classes/AccountProactiveServiceQueueableTest.cls
@IsTest
public class AccountProactiveServiceQueueableTest {
  @TestSetup
  static void makeData() {
    Account account = new Account(Name = 'John');
    account.BillingStreet = 'Test Street';
    account.BillingCity = 'Test City';
    account.BillingPostalCode = 'SW1 3DWW';
    account.BillingCountry = 'United Kingdom';
    account.Phone = '1234567890';
    account.Industry = 'Others';
    insert account;

    Contact contact = new Contact();
    contact.LastName = 'Doe';
    contact.AccountId = account.Id;
    contact.Email = 'john.doe@uipathTest.com';
    insert contact;

    List<Profile> profiles = [SELECT Id FROM Profile WHERE Name = 'UiPath Japan Partner Community'];
    if (profiles.isEmpty()) {
      return;
    }

    User communityUser = new User();
    communityUser.ProfileId = profiles.get(0).Id;
    communityUser.FirstName = 'John';
    communityUser.LastName = 'Doe';
    communityUser.Alias = 'Doe';
    communityUser.Email = 'john.doe@uipathTest.com';
    communityUser.Username = 'john.doe@uipathTest.com';
    communityUser.TimeZoneSidKey = 'America/Los_Angeles';
    communityUser.EmailEncodingKey = 'UTF-8';
    communityUser.LanguageLocaleKey = 'en_US';
    communityUser.LocaleSidKey = 'en_US';
    communityUser.ContactId = contact.Id;
    insert communityUser;
  }

  static testMethod void validateAndUpdateCounter_newProactiveCaseIsCreated() {
    List<User> communityUsers = [SELECT Id FROM User WHERE Username = 'john.doe@uipathTest.com'];
    if (communityUsers.isEmpty()) {
      return;
    }
    System.runAs(communityUsers.get(0)) {
      Case proactiveCareCase = new Case();
      proactiveCareCase.RecordTypeId = CaseMetadata.ProactiveCareRecordType;
      proactiveCareCase.Subject = 'Proactive Case';
      proactiveCareCase.Status = 'New';
      proactiveCareCase.Start_Date__c = System.today().addDays(15);
      Test.startTest();
      new AccountProactiveServiceQueueable(new List<Case>{ proactiveCareCase }).execute(null);
      Test.stopTest();
    }

    Account account = [
      SELECT Id, of_Proactive_services__c, Max_of_Services_Quarter__c, requests_this_quarter__c
      FROM Account
      LIMIT 1
    ];
    System.assertEquals(5, account.of_Proactive_services__c, 'Proactive Services count');
    System.assertEquals(6, account.Max_of_Services_Quarter__c, 'Maximum Services allowed this quarter.');
    System.assertEquals(1, account.requests_this_quarter__c, 'Requests this Quarter.');
  }
}