uipath-commons/main/default/objects/Account/fields/NS_Customer_Internal_ID__c.field-meta.xml
<CustomField>
    <fullName>NS_Customer_Internal_ID__c</fullName>
    <caseSensitive>true</caseSensitive>
    <description>NetSuite unique internal record Id for the customer record</description>
    <externalId>true</externalId>
    <inlineHelpText>NetSuite unique internal record Id for the customer record</inlineHelpText>
    <label>NS Customer Internal ID</label>
    <length>50</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

uipath-commons/main/default/objects/Account/fields/Sync_Status__c.field-meta.xml
<CustomField>
    <fullName>Sync_Status__c</fullName>
    <description>Indicated the status of the product against integration</description>
    <inlineHelpText>Not Valid - default sync status for new records
Valid - Ready to be synced to NetSuite
Pending - Updates on record ready to be synced to NetSuite
Synced - Synced to NetSuite
Error - Error while syncing
Do Not Sync - Archive from syncing</inlineHelpText>
    <label>Sync Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Sync_Status</valueSetName>
    </valueSet>
</CustomField>

uipath-commons/main/default/objects/Account/fields/Validation_Status__c.field-meta.xml
<CustomField>
    <fullName>Validation_Status__c</fullName>
    <description>Used by the Data Stewards to flag the Account validation status</description>
    <inlineHelpText>When Data Stewards set the status to &quot;Validated&quot; call to boomi integration will be made</inlineHelpText>
    <label>Validation Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Data_Steward_Validation_Status</valueSetName>
    </valueSet>
</CustomField>

uipath-commons/main/default/globalValueSets/Data_Steward_Validation_Status.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>In Review</fullName>
    </customValue>
    <customValue>
        <fullName>Pending</fullName>
        <default>true</default>
        <label>Pending</label>
    </customValue>
    <customValue>
        <fullName>Ready For Review</fullName>
    </customValue>
    <customValue>
        <fullName>Review Complete</fullName>
    </customValue>
    <customValue>
        <fullName>Validated</fullName>
    </customValue>
    <description>Validation Status values to be used by the Data Stewards on Accounts, Addresses etc</description>
    <masterLabel>Data Steward Validation Status</masterLabel>
</GlobalValueSet>

uipath-commons/main/default/globalValueSets/Sync_Status.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Do Not Sync</fullName>
    </customValue>
    <customValue>
        <fullName>Error</fullName>
    </customValue>
    <customValue>
        <fullName>Not Valid</fullName>
        <default>true</default>
        <label>Not Valid</label>
    </customValue>
    <customValue>
        <fullName>Pending</fullName>
    </customValue>
    <customValue>
        <fullName>Synced</fullName>
    </customValue>
    <customValue>
        <fullName>Valid</fullName>
    </customValue>
    <description>Sync Status used to maintain various integration status</description>
    <masterLabel>Sync Status</masterLabel>
</GlobalValueSet>

uipath-commons/main/default/classes/AccountSetSyncStatusFunction.cls
/**
 * Sets Sync Status on each account. This drives integration logic in Boomi
 */
public class AccountSetSyncStatusFunction implements SObjectToSObjectFunction {
  private Map<Id, SObject> oldAccounts;

  public AccountSetSyncStatusFunction(Map<Id, SObject> oldAccounts) {
    this.oldAccounts = oldAccounts;
  }

  public SObject apply(Account acc) {
    Account oldAcc = (Account) oldAccounts.get(acc.Id);
    if (
      (accountStatusNotDoNotSync(oldAcc)) &&
      (validationStatusChanged(oldAcc, acc)) &&
      (ValidationStatusSetToValidated(acc))
    ) {
      if (accountAlreadyExistsInNetsuite(acc)) {
        acc.Sync_Status__c = CommonsConstants.ACC_SYNC_STATUS_PENDING;
      } else {
        acc.Sync_Status__c = CommonsConstants.ACC_SYNC_STATUS_VALID;
      }
    }
    return acc;
  }

  private Boolean accountAlreadyExistsInNetsuite(Account acc) {
    return null != acc.NS_Customer_Internal_ID__c;
  }

  private Boolean ValidationStatusSetToValidated(Account acc) {
    return acc.Validation_Status__c ==
      CommonsConstants.ACC_VALIDATION_STATUS_VALIDATED;
  }

  private Boolean validationStatusChanged(Account oldAcc, Account acc) {
    return oldAcc.Validation_Status__c != acc.Validation_Status__c;
  }

  private Boolean accountStatusNotDoNotSync(Account oldAcc) {
    return oldAcc.Sync_Status__c !=
      CommonsConstants.ACC_SYNC_STATUS_DO_NOT_SYNC;
  }

  public SObject apply(SObject record) {
    return apply((Account) record);
  }

  public static void deriveSyncStatusForValidatedAccount(
    List<Account> accounts,
    Map<Id, SObject> existingAccounts
  ) {
    SObjectPredicate haveStatusesChanged = new HasRecordChanged(
      new Set<SObjectField>{
        Account.Sync_Status__c,
        Account.Validation_Status__c
      },
      accounts,
      existingAccounts
    );

    Collection.of(accounts)
      .filter(haveStatusesChanged)
      .mapAll(new AccountSetSyncStatusFunction(existingAccounts));
  }
}