uipath-commons/main/default/objects/Account/fields/Sync_Status__c.field-meta.xml
<CustomField>
    <fullName>Sync_Status__c</fullName>
    <description>Indicated the status of the product against integration</description>
    <inlineHelpText>Not Valid - default sync status for new records
Valid - Ready to be synced to NetSuite
Pending - Updates on record ready to be synced to NetSuite
Synced - Synced to NetSuite
Error - Error while syncing
Do Not Sync - Archive from syncing</inlineHelpText>
    <label>Sync Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Sync_Status</valueSetName>
    </valueSet>
</CustomField>

uipath-commons/main/default/objects/Account/fields/Validation_Status__c.field-meta.xml
<CustomField>
    <fullName>Validation_Status__c</fullName>
    <description>Used by the Data Stewards to flag the Account validation status</description>
    <inlineHelpText>When Data Stewards set the status to &quot;Validated&quot; call to boomi integration will be made</inlineHelpText>
    <label>Validation Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Data_Steward_Validation_Status</valueSetName>
    </valueSet>
</CustomField>

uipath-sales/main/default/objects/Case/fields/Bill_To__c.field-meta.xml
<CustomField>
    <fullName>Bill_To__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Bill To</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Cases (Bill To)</relationshipLabel>
    <relationshipName>Cases2</relationshipName>
    <type>Lookup</type>
</CustomField>

uipath-sales/main/default/objects/Case/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

uipath-sales/main/default/objects/Opportunity/fields/Sold_to_Partner__c.field-meta.xml
<CustomField>
    <fullName>Sold_to_Partner__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sold to Partner</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Opportunities (Sold to Partner)</relationshipLabel>
    <relationshipName>Sold_to_Partner</relationshipName>
    <type>Lookup</type>
</CustomField>

uipath-commons/main/default/globalValueSets/Data_Steward_Validation_Status.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>In Review</fullName>
    </customValue>
    <customValue>
        <fullName>Pending</fullName>
        <default>true</default>
        <label>Pending</label>
    </customValue>
    <customValue>
        <fullName>Ready For Review</fullName>
    </customValue>
    <customValue>
        <fullName>Review Complete</fullName>
    </customValue>
    <customValue>
        <fullName>Validated</fullName>
    </customValue>
    <description>Validation Status values to be used by the Data Stewards on Accounts, Addresses etc</description>
    <masterLabel>Data Steward Validation Status</masterLabel>
</GlobalValueSet>

uipath-commons/main/default/globalValueSets/Sync_Status.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Do Not Sync</fullName>
    </customValue>
    <customValue>
        <fullName>Error</fullName>
    </customValue>
    <customValue>
        <fullName>Not Valid</fullName>
        <default>true</default>
        <label>Not Valid</label>
    </customValue>
    <customValue>
        <fullName>Pending</fullName>
    </customValue>
    <customValue>
        <fullName>Synced</fullName>
    </customValue>
    <customValue>
        <fullName>Valid</fullName>
    </customValue>
    <description>Sync Status used to maintain various integration status</description>
    <masterLabel>Sync Status</masterLabel>
</GlobalValueSet>

uipath-sales/main/default/classes/SalesCaseBillToWOppQueueableTest.cls
@isTest
public class SalesCaseBillToWOppQueueableTest {
  @isTest
  private static void testUpdateBillToOnUpdate() {
    Id legalRequestRecordTypeId = SalesCaseMetadata.LegalRequestRecordType;

    Account accountRecord = new Account(
      Name = 'New Account',
      BillingCountry = 'United Kingdom',
      Industry = 'Others',
      Validation_Status__c = 'Validated',
      Sync_Status__c = 'Synced'
    );
    insert accountRecord;

    List<Opportunity> opportunities = new List<Opportunity>();
    Opportunity oppRecord1 = new Opportunity(
      Name = 'Test',
      StageName = 'Prospecting',
      CloseDate = System.today(),
      Sold_to_Partner__c = accountRecord.Id,
      Amount = 100,
      Description = 'Test description'
    );
    opportunities.add(oppRecord1);

    Opportunity oppRecord2 = new Opportunity(
      Name = 'Test',
      StageName = 'Prospecting',
      CloseDate = System.today(),
      Amount = 100,
      Description = 'Test description'
    );
    opportunities.add(oppRecord2);
    insert opportunities;

    List<Case> cases = new List<Case>();
    Case cs1 = new Case(
      Subject = 'Test',
      Opportunity__c = oppRecord1.Id,
      AccountId = accountRecord.Id,
      RecordTypeId = legalRequestRecordTypeId,
      Status = 'New'
    );
    cases.add(cs1);

    Case cs2 = new Case(
      Subject = 'Test',
      Opportunity__c = oppRecord2.Id,
      AccountId = accountRecord.Id,
      RecordTypeId = legalRequestRecordTypeId,
      Status = 'New'
    );
    cases.add(cs2);
    insert cases;

    Test.StartTest();

    SalesCaseBillToWOppQueueable salesCaseBillToWOppQueueable = new SalesCaseBillToWOppQueueable(
      new List<Case>{ cs1, cs2 }
    );
    salesCaseBillToWOppQueueable.execute(null);

    List<Case> caseRecord = [SELECT Id, Bill_To__r.Name FROM Case WHERE Id = :cs1.Id OR Id = :cs2.Id LIMIT 2];
    System.assertEquals('New Account', caseRecord[0].Bill_To__r.Name);
    System.assertEquals('New Account', caseRecord[1].Bill_To__r.Name);
    Test.StopTest();
  }
}