uipath-service/main/default/objects/Case/fields/Account_CSM__c.field-meta.xml
<CustomField>
    <fullName>Account_CSM__c</fullName>
    <formula>Account.CSM__c</formula>
    <label>Account CSM</label>
    <type>Text</type>
</CustomField>

uipath-service/main/default/objects/Case/fields/Account_STA__c.field-meta.xml
<CustomField>
    <fullName>Account_STA__c</fullName>
    <formula>Account.Support_Technical_Advisor__c</formula>
    <label>Account STA</label>
    <type>Text</type>
</CustomField>

uipath-service/main/default/objects/Case/recordTypes/Academy.recordType-meta.xml
<RecordType>
    <fullName>Academy</fullName>
    <active>true</active>
    <businessProcess>Academy</businessProcess>
    <label>Academy</label>
</RecordType>

uipath-service/main/default/objects/Case/recordTypes/Engagement_Request.recordType-meta.xml
<RecordType>
    <fullName>Engagement_Request</fullName>
    <active>true</active>
    <businessProcess>Engagement Request</businessProcess>
    <description>Ticket created to request L2 and L3 support.</description>
    <label>Expert Request</label>
</RecordType>

uipath-service/main/default/objects/Case/recordTypes/Incident.recordType-meta.xml
<RecordType>
    <fullName>Incident</fullName>
    <active>true</active>
    <businessProcess>Service Request%2FIncident</businessProcess>
    <description>Ticket created to track faults or system error experienced by customer.</description>
    <label>Incident</label>
</RecordType>

uipath-service/main/default/objects/Case/recordTypes/Japan_Academy.recordType-meta.xml
<RecordType>
    <fullName>Japan_Academy</fullName>
    <active>true</active>
    <businessProcess>Sales Operation</businessProcess>
    <label>Japan Academy</label>
</RecordType>

uipath-service/main/default/objects/Case/recordTypes/Japan_Engagement_Request.recordType-meta.xml
<RecordType>
    <fullName>Japan_Engagement_Request</fullName>
    <active>true</active>
    <businessProcess>Engagement Request</businessProcess>
    <label>Japan Engagement Request</label>
</RecordType>

uipath-service/main/default/objects/Case/recordTypes/Japan_Incident.recordType-meta.xml
<RecordType>
    <fullName>Japan_Incident</fullName>
    <active>true</active>
    <businessProcess>Service Request%2FIncident</businessProcess>
    <label>Japan Incident</label>
</RecordType>

uipath-service/main/default/objects/Case/recordTypes/Japan_Licensing.recordType-meta.xml
<RecordType>
    <fullName>Japan_Licensing</fullName>
    <active>true</active>
    <businessProcess>Sales Operation</businessProcess>
    <label>Japan Licensing</label>
</RecordType>

uipath-service/main/default/objects/Case/recordTypes/Proactive_Care.recordType-meta.xml
<RecordType>
    <fullName>Proactive_Care</fullName>
    <active>true</active>
    <businessProcess>Service Request%2FIncident</businessProcess>
    <description>For Proactive Support Portal Users</description>
    <label>Proactive Care</label>
</RecordType>

uipath-service/main/default/objects/Case/recordTypes/Sales_Operation.recordType-meta.xml
<RecordType>
    <fullName>Sales_Operation</fullName>
    <active>true</active>
    <businessProcess>Sales Operation</businessProcess>
    <label>Sales Operation</label>
</RecordType>

uipath-service/main/default/objects/Case/recordTypes/Service_Incident.recordType-meta.xml
<RecordType>
    <fullName>Service_Incident</fullName>
    <active>true</active>
    <businessProcess>Service Incident</businessProcess>
    <description>Ticket created to track an identical issue reported independently by multiple customers.</description>
    <label>Service Incident</label>
</RecordType>

uipath-service/main/default/objects/Case/recordTypes/Service_Request.recordType-meta.xml
<RecordType>
    <fullName>Service_Request</fullName>
    <active>true</active>
    <businessProcess>Service Request%2FIncident</businessProcess>
    <description>Ticket created for service enablement for customers.</description>
    <label>Service Request</label>
</RecordType>

uipath-service/main/default/objects/CPQ_Controls__mdt/CPQ_Controls__mdt.object-meta.xml
<CustomObject>
    <label>CPQ Controls</label>
    <pluralLabel>CPQ Controls</pluralLabel>
</CustomObject>

uipath-service/main/default/objects/CPQ_Controls__mdt/fields/Case_C_CaseTriggerHandler__c.field-meta.xml
<CustomField>
    <fullName>Case_C_CaseTriggerHandler__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Should &apos;CaseTriggerHandler&apos; process case&apos; related to CPQ opportunities</inlineHelpText>
    <label>Case-C-CaseTriggerHandler</label>
    <type>Checkbox</type>
</CustomField>

uipath-service/main/default/objects/CPQ_Controls__mdt/fields/Opp_CPQ_Record_Type_Developer_Name__c.field-meta.xml
<CustomField>
    <fullName>Opp_CPQ_Record_Type_Developer_Name__c</fullName>
    <defaultValue>&quot;CPQ&quot;</defaultValue>
    <inlineHelpText>The Developer Name for the Opportunity CPQ Record Name - this controls which opportunities are defined to be &apos;in-scope&apos; for the exclusion mechanism.</inlineHelpText>
    <label>CPQ Record Type Developer Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

uipath-service/main/default/classes/CaseMetadata.cls
public without sharing class CaseMetadata {
  public static final String CSM_ROLE = 'CSM';
  public static final String CTM_ROLE = 'Case Team Member';
  public static final String CASE_NUMBER = '##CASE_NUMBER##';

  public static final STRING PENDING_FROM_PRODUCT = 'Pending from Product';
  public static final STRING PENDING_FROM_INFRA = 'Pending from Infra/MCS';
  public static final STRING PENDING_FROM_SR_TECH = 'Pending from Sr. Tech Support';
  public static final STRING PENDING_FROM_TECH = 'Pending from Tech Support';

  //Service Record Types
  private static final String ACADEMY = 'Academy';
  private static final String ENGAGEMENT_REQUEST = 'Engagement_Request';
  private static final String INCIDENT = 'Incident';
  private static final String JAPAN_ACADEMY = 'Japan_Academy';
  private static final String JAPAN_ENGAGEMENT_REQUEST = 'Japan_Engagement_Request';
  private static final String JAPAN_INCIDENT = 'Japan_Incident';
  private static final String JAPAN_LICENSING = 'Japan_Licensing';
  private static final String PROACTIVE_CARE = 'Proactive_Care';
  private static final String SALES_OPERATION = 'Sales_Operation';
  private static final String SERVICE_INCIDENT = 'Service_Incident';
  private static final String SERVICE_REQUEST = 'Service_Request';

  public static Id getRecordTypeId(String developerName) {
    Id recordTypeId = Schema.SObjectType.Case.getRecordTypeInfosByDeveloperName().get(developerName).getRecordTypeId();
    return recordTypeId;
  }

  public static Id EngagementRequestRecordType {
    get {
      return getRecordTypeId(ENGAGEMENT_REQUEST);
    }
    set;
  }

  public static Id JapanEngagementRequestRecordType {
    get {
      return getRecordTypeId(JAPAN_ENGAGEMENT_REQUEST);
    }
    set;
  }

  public static Id AcademyRecordType {
    get {
      return getRecordTypeId(ACADEMY);
    }
    set;
  }

  public static Id ProactiveCareRecordType {
    get {
      return getRecordTypeId(PROACTIVE_CARE);
    }
    set;
  }
  public static Id IncidentRecordType {
    get {
      return getRecordTypeId(INCIDENT);
    }
    set;
  }

  public static Id JapanAcademyRecordType {
    get {
      return getRecordTypeId(JAPAN_ACADEMY);
    }
    set;
  }

  public static Id JapanIncidentRecordType {
    get {
      return getRecordTypeId(JAPAN_INCIDENT);
    }
    set;
  }

  public static Id JapanLicensingRecordType {
    get {
      return getRecordTypeId(JAPAN_LICENSING);
    }
    set;
  }

  public static Id SalesOperationRecordType {
    get {
      return getRecordTypeId(SALES_OPERATION);
    }
    set;
  }

  public static Id ServiceRequestRecordType {
    get {
      return getRecordTypeId(SERVICE_REQUEST);
    }
    set;
  }

  public static Id ServiceIncidentRecordType {
    get {
      return getRecordTypeId(SERVICE_INCIDENT);
    }
    set;
  }

  public static CPQ_Controls__mdt CPQControls {
    get {
      if (CPQControls == null) {
        CPQControls = [
          SELECT Id, Opp_CPQ_Record_Type_Developer_Name__c, Case_C_CaseTriggerHandler__c
          FROM CPQ_Controls__mdt
          LIMIT 1
        ];
      }
      return CPQControls;
    }
    set;
  }

  public static Map<String, Id> TeamRoleMap {
    get {
      if (TeamRoleMap == null) {
        TeamRoleMap = new Map<String, Id>();
        for (CaseTeamRole teamRole : [SELECT Id, Name FROM CaseTeamRole WHERE Name IN (:CSM_ROLE, :CTM_ROLE)]) {
          TeamRoleMap.put(teamRole.Name, teamRole.Id);
        }
      }
      return TeamRoleMap;
    }
    set;
  }

  public static Map<Schema.SObjectField, String> FieldToRoleMap {
    get {
      if (FieldToRoleMap == null) {
        FieldToRoleMap = new Map<Schema.SObjectField, String>();
        FieldToRoleMap.put(Case.Account_CSM__c, CSM_ROLE);
        FieldToRoleMap.put(Case.Account_STA__c, CTM_ROLE);
      }
      return FieldToRoleMap;
    }
    set;
  }
}