uipath-service/main/default/objects/Case/fields/Actual_Result__c.field-meta.xml
<CustomField>
    <fullName>Actual_Result__c</fullName>
    <label>Actual Result</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

uipath-service/main/default/objects/Case/fields/Case_Web_Form_Region__c.field-meta.xml
<CustomField>
    <fullName>Case_Web_Form_Region__c</fullName>
    <label>Case Web Form Region</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Japan</fullName>
            </value>
            <value>
                <fullName>Cloud Enterprise</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

uipath-service/main/default/objects/Case/fields/Copy_From_Parent_Case__c.field-meta.xml
<CustomField>
    <fullName>Copy_From_Parent_Case__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Copy From Parent Case</label>
    <type>Checkbox</type>
</CustomField>

uipath-service/main/default/objects/Case/fields/Expected_Result__c.field-meta.xml
<CustomField>
    <fullName>Expected_Result__c</fullName>
    <label>Expected Result</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

uipath-service/main/default/objects/Case/fields/Related_To__c.field-meta.xml
<CustomField>
    <fullName>Related_To__c</fullName>
    <label>Product Component</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Academic Alliance</fullName>
            </value>
            <value>
                <fullName>Academy</fullName>
            </value>
            <value>
                <fullName>Apps</fullName>
                <label>Action Center</label>
            </value>
            <value>
                <fullName>Activation</fullName>
                <isActive>false</isActive>
                <label>Activation</label>
            </value>
            <value>
                <fullName>Activities</fullName>
                <isActive>false</isActive>
                <label>Activities</label>
            </value>
            <value>
                <fullName>AI Capabilities</fullName>
                <isActive>false</isActive>
                <label>AI Capabilities</label>
            </value>
            <value>
                <fullName>AI Fabric</fullName>
            </value>
            <value>
                <fullName>Attended browser embedding SDK</fullName>
            </value>
            <value>
                <fullName>Cloud Platform</fullName>
                <label>Automation Cloud</label>
            </value>
            <value>
                <fullName>Connect Enterprise</fullName>
                <label>Automation Hub</label>
            </value>
            <value>
                <fullName>Automation Ready Programs</fullName>
            </value>
            <value>
                <fullName>Certification</fullName>
            </value>
            <value>
                <fullName>Document Understanding</fullName>
            </value>
            <value>
                <fullName>Feedback</fullName>
            </value>
            <value>
                <fullName>IT Automation</fullName>
            </value>
            <value>
                <fullName>Kibana</fullName>
                <isActive>false</isActive>
                <label>Kibana</label>
            </value>
            <value>
                <fullName>Learning Platform Inquiries</fullName>
            </value>
            <value>
                <fullName>Licensing</fullName>
                <label>License</label>
            </value>
            <value>
                <fullName>Orchestrator</fullName>
            </value>
            <value>
                <fullName>Orchestrator Mobile</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Others</fullName>
                <isActive>false</isActive>
                <label>Others</label>
            </value>
            <value>
                <fullName>Partner Product</fullName>
            </value>
            <value>
                <fullName>Partner Training</fullName>
            </value>
            <value>
                <fullName>Portal</fullName>
            </value>
            <value>
                <fullName>Process Gold</fullName>
                <label>Process Mining</label>
            </value>
            <value>
                <fullName>Reporting</fullName>
                <isActive>false</isActive>
                <label>Reporting</label>
            </value>
            <value>
                <fullName>Robot</fullName>
            </value>
            <value>
                <fullName>Studio</fullName>
            </value>
            <value>
                <fullName>Studio X</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

uipath-service/main/default/objects/Case/fields/Steps_To_Reproduce_The_Issue__c.field-meta.xml
<CustomField>
    <fullName>Steps_To_Reproduce_The_Issue__c</fullName>
    <label>Steps To Reproduce The Issue</label>
    <type>TextArea</type>
</CustomField>

uipath-service/main/default/objects/Case/fields/Sub_Component__c.field-meta.xml
<CustomField>
    <fullName>Sub_Component__c</fullName>
    <label>Sub Component</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Related_To__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Abby</fullName>
            </value>
            <value>
                <fullName>Abbyy_FineReader</fullName>
            </value>
            <value>
                <fullName>Abbyy_FlexiCapture</fullName>
            </value>
            <value>
                <fullName>Academic Alliance</fullName>
            </value>
            <value>
                <fullName>Academic Alliance Edition</fullName>
            </value>
            <value>
                <fullName>Academy Trainings</fullName>
            </value>
            <value>
                <fullName>Account</fullName>
            </value>
            <value>
                <fullName>Account Inquiries</fullName>
            </value>
            <value>
                <fullName>Account Merger</fullName>
            </value>
            <value>
                <fullName>Activation</fullName>
            </value>
            <value>
                <fullName>Active Directory Domain Services Activities</fullName>
            </value>
            <value>
                <fullName>Activites_Keyword Based_Classifier Trainer</fullName>
            </value>
            <value>
                <fullName>Activities_Computer Vision</fullName>
            </value>
            <value>
                <fullName>Activities_Core</fullName>
            </value>
            <value>
                <fullName>Activities_Custom</fullName>
            </value>
            <value>
                <fullName>Activities_Database</fullName>
            </value>
            <value>
                <fullName>Activities_Excel</fullName>
            </value>
            <value>
                <fullName>Activities_FTP</fullName>
            </value>
            <value>
                <fullName>Activities_GoogleSutite</fullName>
                <label>Activities_GoogleSuite</label>
            </value>
            <value>
                <fullName>Activities_IT_Automation</fullName>
            </value>
            <value>
                <fullName>Activities_Java</fullName>
            </value>
            <value>
                <fullName>Activities_Mail</fullName>
            </value>
            <value>
                <fullName>Activities_OCR</fullName>
            </value>
            <value>
                <fullName>Activities_Office365</fullName>
            </value>
            <value>
                <fullName>Activities_Others</fullName>
            </value>
            <value>
                <fullName>Activities_PDF</fullName>
            </value>
            <value>
                <fullName>Activities_Python</fullName>
            </value>
            <value>
                <fullName>Activities_SalesforceConnector</fullName>
            </value>
            <value>
                <fullName>Activities_SAP_BAPI</fullName>
            </value>
            <value>
                <fullName>Activities_Terminal</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

uipath-service/main/default/objects/Case/fields/What_You_Want_Us_To_Do__c.field-meta.xml
<CustomField>
    <fullName>What_You_Want_Us_To_Do__c</fullName>
    <label>What You Want Us To Do</label>
    <type>TextArea</type>
</CustomField>

uipath-service/main/default/objects/Case/fields/Workaround__c.field-meta.xml
<CustomField>
    <fullName>Workaround__c</fullName>
    <label>Workaround</label>
    <type>TextArea</type>
</CustomField>

uipath-service/main/default/classes/CaseCopyFromParentERFunction.cls
public with sharing class CaseCopyFromParentERFunction implements SObjectToSObjectFunction {
  public static Map<Id, Case> parentCaseMap = new Map<Id, Case>();
  public CaseCopyFromParentERFunction(List<Case> cases) {
    Set<Id> parentIds = new Set<Id>();
    for (Case record : cases) {
      parentIds.add(record.ParentId);
    }

    for (Case parentCase : [
      SELECT
        Id,
        ContactId,
        Description,
        Issue__c,
        Priority,
        Related_To__c,
        Sub_Component__c,
        Subject,
        Actual_Result__c,
        Case_Web_Form_Region__c,
        Expected_Result__c,
        Frequency__c,
        Steps_To_Reproduce_The_Issue__c,
        What_You_Want_Us_To_Do__c,
        Workaround__c
      FROM Case
      WHERE Id IN :parentIds
    ]) {
      parentCaseMap.put(parentCase.Id, parentCase);
    }
  }

  public SObject apply(Case record) {
    if (!parentCaseMap.containsKey(record.ParentId)) {
      return null;
    }
    Case parentCase = parentCaseMap.get(record.ParentId);
    record.ContactId = parentCase.ContactId;
    record.Description = parentCase.Description;
    record.Issue__c = parentCase.Issue__c;
    record.Priority = parentCase.Priority;
    record.Related_To__c = parentCase.Related_To__c;
    record.Sub_Component__c = parentCase.Sub_Component__c;
    String parentSubject = (parentCase.Subject != null) ? parentCase.Subject : '';
    if (record.CaseNumber != null) {
      record.Subject = 'ER: ' + record.CaseNumber + ' ' + parentSubject;
    } else {
      record.Subject = 'ER: ' + CaseMetadata.CASE_NUMBER + ' ' + parentSubject;
    }
    if (record.RecordTypeId == CaseMetadata.JapanEngagementRequestRecordType) {
      record.Actual_Result__c = parentCase.Actual_Result__c;
      record.Case_Web_Form_Region__c = parentCase.Case_Web_Form_Region__c;
      record.Expected_Result__c = parentCase.Expected_Result__c;
      record.Frequency__c = parentCase.Frequency__c;
      record.Steps_To_Reproduce_The_Issue__c = parentCase.Steps_To_Reproduce_The_Issue__c;
      record.What_You_Want_Us_To_Do__c = parentCase.What_You_Want_Us_To_Do__c;
      record.Workaround__c = parentCase.Workaround__c;
    }
    return record;
  }

  public SObject apply(SObject record) {
    return apply((Case) record);
  }

  public static void deriveChildCaseFromParent(List<SObject> Records) {
    Collection.of(Records)
      .filter(
        Match.field(Case.RecordTypeId)
          .isIn(
            new Set<String>{ CaseMetadata.EngagementRequestRecordType, CaseMetadata.JapanEngagementRequestRecordType }
          )
      )
      .mapSome(
        Match.field(Case.Copy_From_Parent_Case__c)
          .hasValue()
          .also(Case.Copy_From_Parent_Case__c)
          .equals(true)
          .also(Case.Status)
          .notEquals('Closed')
          .also(Case.ParentId)
          .hasValue(),
        new CaseCopyFromParentERFunction(Records)
      );
  }

  public static void deriveChildCaseFromParent(List<SObject> Records, Map<Id, SObject> existingCases) {
    SObjectPredicate hasChanged = new HasRecordChanged(
      new Set<SObjectField>{ Case.Copy_From_Parent_Case__c },
      Records,
      existingCases
    );
    Collection.of(Records)
      .filter(hasChanged)
      .filter(
        Match.field(Case.RecordTypeId)
          .isIn(
            new Set<String>{ CaseMetadata.EngagementRequestRecordType, CaseMetadata.JapanEngagementRequestRecordType }
          )
      )
      .mapSome(
        Match.field(Case.Copy_From_Parent_Case__c)
          .hasValue()
          .also(Case.Copy_From_Parent_Case__c)
          .equals(true)
          .also(Case.Status)
          .notEquals('Closed')
          .also(Case.ParentId)
          .hasValue(),
        new CaseCopyFromParentERFunction(Records)
      );
  }
}