uipath-service/main/default/objects/Case/fields/Awaiting_Pending_Reason__c.field-meta.xml
<CustomField>
    <fullName>Awaiting_Pending_Reason__c</fullName>
    <label>Awaiting/Pending  Reason</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending from Tech Support</fullName>
            </value>
            <value>
                <fullName>Pending from Sr. Tech Support</fullName>
            </value>
            <value>
                <fullName>Pending from Infra/MCS</fullName>
            </value>
            <value>
                <fullName>Pending from Product</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

uipath-service/main/default/objects/Case/fields/Pending_Product_Timestamp__c.field-meta.xml
<CustomField>
    <fullName>Pending_Product_Timestamp__c</fullName>
    <label>Pending Product Timestamp</label>
    <type>DateTime</type>
</CustomField>

uipath-service/main/default/classes/CasePendingReasonChangeFunctionTest.cls
@IsTest
public class CasePendingReasonChangeFunctionTest {
  @IsTest
  private static void derivePendingTimestamps_onERCaseUpdate() {
    Id caseId = fflib_IDGenerator.generate(Case.SObjectType);
    Id engagementRecordTypeId = CaseMetadata.EngagementRequestRecordType;
    Case oldCase = new Case(Id = caseId, Subject = 'Test', RecordTypeId = engagementRecordTypeId, Status = 'New');
    Case updatedCase = new Case(
      Id = caseId,
      Subject = 'Test',
      RecordTypeId = engagementRecordTypeId,
      Awaiting_Pending_Reason__c = CaseMetadata.PENDING_FROM_PRODUCT
    );
    fflib_SObjectDomain.Test.Database.onUpdate(
      new List<Case>{ updatedCase },
      new Map<Id, SObject>{ oldCase.Id => oldCase }
    );

    fflib_SObjectDomain.triggerHandler(Cases.class);
    System.assertNotEquals(null, updatedCase.Pending_Product_Timestamp__c, 'Pending Product Timestamp is not null');
  }
}