uipath-service/main/default/objects/Case/fields/Awaiting_Pending_Reason__c.field-meta.xml
<CustomField>
    <fullName>Awaiting_Pending_Reason__c</fullName>
    <label>Awaiting/Pending  Reason</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending from Tech Support</fullName>
            </value>
            <value>
                <fullName>Pending from Sr. Tech Support</fullName>
            </value>
            <value>
                <fullName>Pending from Infra/MCS</fullName>
            </value>
            <value>
                <fullName>Pending from Product</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

uipath-service/main/default/objects/Case/fields/Pending_Infra_MCS_Time_stamp__c.field-meta.xml
<CustomField>
    <fullName>Pending_Infra_MCS_Time_stamp__c</fullName>
    <label>Pending Infra/MCS Time stamp</label>
    <type>DateTime</type>
</CustomField>

uipath-service/main/default/objects/Case/fields/Pending_Product_Timestamp__c.field-meta.xml
<CustomField>
    <fullName>Pending_Product_Timestamp__c</fullName>
    <label>Pending Product Timestamp</label>
    <type>DateTime</type>
</CustomField>

uipath-service/main/default/objects/Case/fields/Pending_Sr_Tech_Support_time_stamp__c.field-meta.xml
<CustomField>
    <fullName>Pending_Sr_Tech_Support_time_stamp__c</fullName>
    <label>Pending Sr.Tech Support time stamp</label>
    <type>DateTime</type>
</CustomField>

uipath-service/main/default/objects/Case/fields/Pending_Tech_support_time_stamp__c.field-meta.xml
<CustomField>
    <fullName>Pending_Tech_support_time_stamp__c</fullName>
    <label>Pending Tech support time stamp</label>
    <type>DateTime</type>
</CustomField>

uipath-service/main/default/classes/CasePendingReasonChangeFunction.cls
public with sharing class CasePendingReasonChangeFunction implements SObjectToSObjectFunction {
  public CasePendingReasonChangeFunction(List<Case> cases) {
  }

  public SObject apply(Case record) {
    if (record.Awaiting_Pending_Reason__c == CaseMetadata.PENDING_FROM_PRODUCT) {
      record.Pending_Product_Timestamp__c = System.now();
    } else if (record.Awaiting_Pending_Reason__c == CaseMetadata.PENDING_FROM_INFRA) {
      record.Pending_Infra_MCS_Time_stamp__c = System.now();
    } else if (record.Awaiting_Pending_Reason__c == CaseMetadata.PENDING_FROM_SR_TECH) {
      record.Pending_Sr_Tech_Support_time_stamp__c = System.now();
    } else if (record.Awaiting_Pending_Reason__c == CaseMetadata.PENDING_FROM_TECH) {
      record.Pending_Tech_support_time_stamp__c = System.now();
    }
    return record;
  }

  public SObject apply(SObject record) {
    return apply((Case) record);
  }

  public static void derivePendingTimestamps(List<SObject> cases, Map<Id, SObject> existingCases) {
    SObjectPredicate hasChanged = new HasRecordChanged(
      new Set<SObjectField>{ Case.Awaiting_Pending_Reason__c },
      cases,
      existingCases
    );

    Collection.of(cases)
      .filter(hasChanged)
      .filter(
        Match.field(Case.RecordTypeId)
          .isIn(
            new Set<String>{ CaseMetadata.EngagementRequestRecordType, CaseMetadata.JapanEngagementRequestRecordType }
          )
          .also(Case.Awaiting_Pending_Reason__c)
          .hasValue()
          .also(Case.Awaiting_Pending_Reason__c)
          .isIn(
            new Set<String>{
              CaseMetadata.PENDING_FROM_PRODUCT,
              CaseMetadata.PENDING_FROM_INFRA,
              CaseMetadata.PENDING_FROM_SR_TECH,
              CaseMetadata.PENDING_FROM_TECH
            }
          )
      )
      .mapAll(new CasePendingReasonChangeFunction(cases));
  }
}