uipath-service/main/default/objects/Case/fields/Case_Owner_is_Queue__c.field-meta.xml
<CustomField>
    <fullName>Case_Owner_is_Queue__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Checked when case owner is a queue. Unchecked when case owner is a user.</description>
    <label>Case Owner is Queue</label>
    <type>Checkbox</type>
</CustomField>

uipath-service/main/default/objects/Case/fields/CSAT__c.field-meta.xml
<CustomField>
    <fullName>CSAT__c</fullName>
    <defaultValue>0.00</defaultValue>
    <label>CSAT</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

uipath-service/main/default/objects/Case/fields/Related_To__c.field-meta.xml
<CustomField>
    <fullName>Related_To__c</fullName>
    <label>Product Component</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Academic Alliance</fullName>
            </value>
            <value>
                <fullName>Academy</fullName>
            </value>
            <value>
                <fullName>Apps</fullName>
                <label>Action Center</label>
            </value>
            <value>
                <fullName>Activation</fullName>
                <isActive>false</isActive>
                <label>Activation</label>
            </value>
            <value>
                <fullName>Activities</fullName>
                <isActive>false</isActive>
                <label>Activities</label>
            </value>
            <value>
                <fullName>AI Capabilities</fullName>
                <isActive>false</isActive>
                <label>AI Capabilities</label>
            </value>
            <value>
                <fullName>AI Fabric</fullName>
            </value>
            <value>
                <fullName>Attended browser embedding SDK</fullName>
            </value>
            <value>
                <fullName>Cloud Platform</fullName>
                <label>Automation Cloud</label>
            </value>
            <value>
                <fullName>Connect Enterprise</fullName>
                <label>Automation Hub</label>
            </value>
            <value>
                <fullName>Automation Ready Programs</fullName>
            </value>
            <value>
                <fullName>Certification</fullName>
            </value>
            <value>
                <fullName>Document Understanding</fullName>
            </value>
            <value>
                <fullName>Feedback</fullName>
            </value>
            <value>
                <fullName>IT Automation</fullName>
            </value>
            <value>
                <fullName>Kibana</fullName>
                <isActive>false</isActive>
                <label>Kibana</label>
            </value>
            <value>
                <fullName>Learning Platform Inquiries</fullName>
            </value>
            <value>
                <fullName>Licensing</fullName>
                <label>License</label>
            </value>
            <value>
                <fullName>Orchestrator</fullName>
            </value>
            <value>
                <fullName>Orchestrator Mobile</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Others</fullName>
                <isActive>false</isActive>
                <label>Others</label>
            </value>
            <value>
                <fullName>Partner Product</fullName>
            </value>
            <value>
                <fullName>Partner Training</fullName>
            </value>
            <value>
                <fullName>Portal</fullName>
            </value>
            <value>
                <fullName>Process Gold</fullName>
                <label>Process Mining</label>
            </value>
            <value>
                <fullName>Reporting</fullName>
                <isActive>false</isActive>
                <label>Reporting</label>
            </value>
            <value>
                <fullName>Robot</fullName>
            </value>
            <value>
                <fullName>Studio</fullName>
            </value>
            <value>
                <fullName>Studio X</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

uipath-service/main/default/objects/Case/fields/Sub_Component__c.field-meta.xml
<CustomField>
    <fullName>Sub_Component__c</fullName>
    <label>Sub Component</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Related_To__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Abby</fullName>
            </value>
            <value>
                <fullName>Abbyy_FineReader</fullName>
            </value>
            <value>
                <fullName>Abbyy_FlexiCapture</fullName>
            </value>
            <value>
                <fullName>Academic Alliance</fullName>
            </value>
            <value>
                <fullName>Academic Alliance Edition</fullName>
            </value>
            <value>
                <fullName>Academy Trainings</fullName>
            </value>
            <value>
                <fullName>Account</fullName>
            </value>
            <value>
                <fullName>Account Inquiries</fullName>
            </value>
            <value>
                <fullName>Account Merger</fullName>
            </value>
            <value>
                <fullName>Activation</fullName>
            </value>
            <value>
                <fullName>Active Directory Domain Services Activities</fullName>
            </value>
            <value>
                <fullName>Activites_Keyword Based_Classifier Trainer</fullName>
            </value>
            <value>
                <fullName>Activities_Computer Vision</fullName>
            </value>
            <value>
                <fullName>Activities_Core</fullName>
            </value>
            <value>
                <fullName>Activities_Custom</fullName>
            </value>
            <value>
                <fullName>Activities_Database</fullName>
            </value>
            <value>
                <fullName>Activities_Excel</fullName>
            </value>
            <value>
                <fullName>Activities_FTP</fullName>
            </value>
            <value>
                <fullName>Activities_GoogleSutite</fullName>
                <label>Activities_GoogleSuite</label>
            </value>
            <value>
                <fullName>Activities_IT_Automation</fullName>
            </value>
            <value>
                <fullName>Activities_Java</fullName>
            </value>
            <value>
                <fullName>Activities_Mail</fullName>
            </value>
            <value>
                <fullName>Activities_OCR</fullName>
            </value>
            <value>
                <fullName>Activities_Office365</fullName>
            </value>
            <value>
                <fullName>Activities_Others</fullName>
            </value>
            <value>
                <fullName>Activities_PDF</fullName>
            </value>
            <value>
                <fullName>Activities_Python</fullName>
            </value>
            <value>
                <fullName>Activities_SalesforceConnector</fullName>
            </value>
            <value>
                <fullName>Activities_SAP_BAPI</fullName>
            </value>
            <value>
                <fullName>Activities_Terminal</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

uipath-service/main/default/classes/CaseCreateChildCaseQueueable.cls
/**
 * Creates Child Case when the parent Case is Closed and CSAT > 2
 */
public with sharing class CaseCreateChildCaseQueueable extends AbstractQueueable {
  private final List<SObject> cases;
  private static Boolean isAlreadyRun = false;

  public CaseCreateChildCaseQueueable(List<SObject> cases) {
    super('CaseCreateChildCaseQueueable');
    this.cases = cases;
  }

  public override void work() {
    this.createChildCase(this.cases);
  }

  private void createChildCase(List<Case> cases) {
    List<Case> children = new List<Case>();

    Group productSuportQueue = [SELECT Id FROM Group WHERE Type = 'Queue' AND NAME = 'Product_Support_Queue' LIMIT 1];

    for (Case cs : cases) {
      Case child = new Case(
        BusinessHoursId = cs.BusinessHoursId,
        Case_Owner_is_Queue__c = true,
        CurrencyIsoCode = cs.CurrencyIsoCode,
        Description = cs.Description,
        OwnerId = productSuportQueue.Id,
        ParentId = cs.Id,
        RecordTypeId = cs.RecordTypeId,
        Related_To__c = cs.Related_To__c,
        Status = 'New',
        Sub_Component__c = cs.Sub_Component__c,
        Subject = 'DSAT FollowUp: ' + cs.Subject
      );
      children.add(child);
    }

    if (!children.isEmpty()) {
      insert children;
    }
  }

  public static void createChildCases(List<SObject> cases, Map<Id, SObject> existingCases) {
    SObjectPredicate hasChanged = new HasRecordChanged(
      new Set<SObjectField>{ Case.Status, Case.CSAT__c },
      cases,
      existingCases
    );

    List<Case> eligibleCases = Collection.of(cases)
      .filter(hasChanged)
      .filter(
        Match.field(Case.RecordTypeId)
          .isIn(new Set<String>{ CaseMetadata.IncidentRecordType })
          .also(Case.Status)
          .equals('Closed')
          .also(Case.CSAT__c)
          .lessThanOrEquals(2)
      )
      .asList();

    if (!eligibleCases.isEmpty()) {
      if (!isAlreadyRun) {
        isAlreadyRun = true;
        AbstractQueueable.enqueue(new CaseCreateChildCaseQueueable(eligibleCases));
      }
    }
  }
}