uipath-service/main/default/objects/Case/fields/Case_Re_Open_Date__c.field-meta.xml
<CustomField>
    <fullName>Case_Re_Open_Date__c</fullName>
    <label>Case Re Open Date</label>
    <type>Date</type>
</CustomField>

uipath-service/main/default/objects/Case/fields/No_of_Emails_Received__c.field-meta.xml
<CustomField>
    <fullName>No_of_Emails_Received__c</fullName>
    <defaultValue>0</defaultValue>
    <label>No. of Emails Received</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

uipath-service/main/default/objects/Case/fields/Reopen__c.field-meta.xml
<CustomField>
    <fullName>Reopen__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Once the status from closed to any other status it should be checked</description>
    <label>Reopen</label>
    <type>Checkbox</type>
</CustomField>

uipath-service/main/default/classes/CaseReOpenFunctionTest.cls
@IsTest
public class CaseReOpenFunctionTest {
  @IsTest
  private static void testDeriveCaseReOpen() {
    Id caseId = fflib_IDGenerator.generate(Case.SObjectType);
    Id incidentRecordTypeID = CaseMetadata.IncidentRecordType;
    Case oldCase = new Case(
      Id = caseId,
      Subject = 'Test',
      RecordTypeId = incidentRecordTypeID,
      Status = 'New',
      No_of_Emails_Received__c = 0
    );
    Case updatedCase = new Case(
      Id = caseId,
      Subject = 'Test',
      RecordTypeId = incidentRecordTypeID,
      Status = 'Resolved',
      No_of_Emails_Received__c = 2
    );
    fflib_SObjectDomain.Test.Database.onUpdate(
      new List<Case>{ updatedCase },
      new Map<Id, SObject>{ oldCase.Id => oldCase }
    );

    fflib_SObjectDomain.triggerHandler(Cases.class);
    System.assertEquals(system.today(), updatedCase.Case_Re_Open_Date__c);
    System.assertEquals(true, updatedCase.Reopen__c);
  }
}