uipath-service/main/default/objects/Case/fields/Case_Re_Open_Date__c.field-meta.xml
<CustomField>
    <fullName>Case_Re_Open_Date__c</fullName>
    <label>Case Re Open Date</label>
    <type>Date</type>
</CustomField>

uipath-service/main/default/objects/Case/fields/No_of_Emails_Received__c.field-meta.xml
<CustomField>
    <fullName>No_of_Emails_Received__c</fullName>
    <defaultValue>0</defaultValue>
    <label>No. of Emails Received</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

uipath-service/main/default/objects/Case/fields/Reopen__c.field-meta.xml
<CustomField>
    <fullName>Reopen__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Once the status from closed to any other status it should be checked</description>
    <label>Reopen</label>
    <type>Checkbox</type>
</CustomField>

uipath-service/main/default/classes/CaseReOpenFunction.cls
public with sharing class CaseReOpenFunction implements SObjectToSObjectFunction {
  private Map<Id, SObject> oldCases;

  public CaseReOpenFunction(List<Case> cases) {
    this.oldCases = oldCases;
  }

  public SObject apply(Case caseRecord) {
    caseRecord.Case_Re_Open_Date__c = system.today();
    caseRecord.Reopen__c = true;
    return caseRecord;
  }

  public SObject apply(SObject record) {
    return apply((Case) record);
  }

  public static void deriveCaseReOpen(List<SObject> cases, Map<Id, SObject> existingCases) {
    HasRecordChanged hasRecordChanged = new HasRecordChanged(
      new Set<SObjectField>{ Case.No_of_Emails_Received__c },
      cases,
      existingCases
    );

    Collection.of(cases)
      .filter(HasRecordChanged)
      .filter(
        Match.field(Case.RecordTypeId)
          .isIn(
            new Set<String>{
              CaseMetadata.IncidentRecordType,
              CaseMetadata.ServiceRequestRecordType,
              CaseMetadata.SalesOperationRecordType,
              CaseMetadata.AcademyRecordType,
              CaseMetadata.JapanAcademyRecordType,
              CaseMetadata.JapanLicensingRecordType,
              CaseMetadata.JapanIncidentRecordType
            }
          )
      )
      .mapSome(Match.field(Case.Status).equals('Resolved'), new CaseReOpenFunction(cases));
  }
}