uipath-service/main/default/objects/Case/fields/Cause__c.field-meta.xml
<CustomField>
    <fullName>Cause__c</fullName>
    <inlineHelpText>This will contain the assumed cause</inlineHelpText>
    <label>Cause</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

uipath-service/main/default/objects/Case/fields/Comm_Update__c.field-meta.xml
<CustomField>
    <fullName>Comm_Update__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Comm Update</label>
    <type>Checkbox</type>
</CustomField>

uipath-service/main/default/objects/Case/fields/Problem__c.field-meta.xml
<CustomField>
    <fullName>Problem__c</fullName>
    <inlineHelpText>This will contain the technical summary of the identified problem/question</inlineHelpText>
    <label>Problem</label>
    <length>32072</length>
    <type>Html</type>
</CustomField>

uipath-service/main/default/objects/Case/fields/Solution__c.field-meta.xml
<CustomField>
    <fullName>Solution__c</fullName>
    <inlineHelpText>Technical summary of the solution</inlineHelpText>
    <label>Solution</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

uipath-service/main/default/objects/Case/fields/Solution_Instructions__c.field-meta.xml
<CustomField>
    <fullName>Solution_Instructions__c</fullName>
    <inlineHelpText>Instructions to apply the solution</inlineHelpText>
    <label>Solution Instructions</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

uipath-service/main/default/objects/Case/fields/Validation__c.field-meta.xml
<CustomField>
    <fullName>Validation__c</fullName>
    <inlineHelpText>In case the ticket is a Problem and not a How To every problem should be accompanied by proof of it&apos;s existence and cause and how it was validated</inlineHelpText>
    <label>Validation/Steps Taken so far</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

uipath-service/main/default/objects/Case/recordTypes/Incident.recordType-meta.xml
<RecordType>
    <fullName>Incident</fullName>
    <active>true</active>
    <businessProcess>Service Request%2FIncident</businessProcess>
    <description>Ticket created to track faults or system error experienced by customer.</description>
    <label>Incident</label>
</RecordType>

uipath-service/main/default/objects/Living_Summary_History__c/Living_Summary_History__c.object-meta.xml
<CustomObject>
    <label>Living Summary History</label>
    <nameField>
        <label>Living Summary History Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Living Summary History</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

uipath-service/main/default/classes/CaseLivingSummaryQueueableTest.cls
@IsTest
public class CaseLivingSummaryQueueableTest {
  @TestSetup
  static void makeData() {
    Account account = new Account(Name = 'John');
    account.BillingStreet = 'Test Street';
    account.BillingCity = 'Test City';
    account.BillingPostalCode = 'SW1 3DWW';
    account.BillingCountry = 'United Kingdom';
    account.Phone = '1234567890';
    account.Industry = 'Others';
    insert account;
    Entitlement entitlement = new Entitlement();
    entitlement.AccountId = account.Id;
    entitlement.Name = 'Standard Account';
    insert entitlement;
  }

  static testMethod void createLivingSummaryHistory_onUpdateCase() {
    Case incidentCase = new Case();
    incidentCase.RecordTypeId = CaseMetadata.IncidentRecordType;
    incidentCase.Subject = 'Incident  Case';
    incidentCase.Status = 'New';
    incidentCase.Problem__c = 'Some Problem';
    incidentCase.Cause__c = 'Some Cause';
    insert incidentCase;
    Map<Id, Case> existingCases = new Map<Id, Case>(
      [SELECT Id, Problem__c, Cause__c, Validation__c, Solution__c, Solution_Instructions__c FROM Case LIMIT 1]
    );
    incidentCase.Problem__c = 'Updated Problem';
    incidentCase.Cause__c = 'Updated Cause';
    update incidentCase;
    Test.startTest();
    System.debug('### Comm_Update__c ' + incidentCase);
    new CaseLivingSummaryQueueable(new List<Case>{ incidentCase }, existingCases).work();
    Test.stopTest();
    List<Living_Summary_History__c> summaryHistory = [SELECT Id FROM Living_Summary_History__c];
    System.assertEquals(2, summaryHistory.size(), 'Expecting Living Summary History to be created');
  }
}