uipath-service/main/default/objects/Case/fields/Cause__c.field-meta.xml
<CustomField>
    <fullName>Cause__c</fullName>
    <inlineHelpText>This will contain the assumed cause</inlineHelpText>
    <label>Cause</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

uipath-service/main/default/objects/Case/fields/Problem__c.field-meta.xml
<CustomField>
    <fullName>Problem__c</fullName>
    <inlineHelpText>This will contain the technical summary of the identified problem/question</inlineHelpText>
    <label>Problem</label>
    <length>32072</length>
    <type>Html</type>
</CustomField>

uipath-service/main/default/objects/Case/fields/Solution__c.field-meta.xml
<CustomField>
    <fullName>Solution__c</fullName>
    <inlineHelpText>Technical summary of the solution</inlineHelpText>
    <label>Solution</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

uipath-service/main/default/objects/Case/fields/Solution_Instructions__c.field-meta.xml
<CustomField>
    <fullName>Solution_Instructions__c</fullName>
    <inlineHelpText>Instructions to apply the solution</inlineHelpText>
    <label>Solution Instructions</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

uipath-service/main/default/objects/Case/fields/Validation__c.field-meta.xml
<CustomField>
    <fullName>Validation__c</fullName>
    <inlineHelpText>In case the ticket is a Problem and not a How To every problem should be accompanied by proof of it&apos;s existence and cause and how it was validated</inlineHelpText>
    <label>Validation/Steps Taken so far</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

uipath-service/main/default/objects/Living_Summary_History__c/Living_Summary_History__c.object-meta.xml
<CustomObject>
    <label>Living Summary History</label>
    <nameField>
        <label>Living Summary History Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Living Summary History</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

uipath-service/main/default/objects/Living_Summary_History__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Living Summary History</relationshipLabel>
    <relationshipName>Living_Summary_History</relationshipName>
    <type>Lookup</type>
</CustomField>

uipath-service/main/default/objects/Living_Summary_History__c/fields/Field_Name__c.field-meta.xml
<CustomField>
    <fullName>Field_Name__c</fullName>
    <label>Field Name</label>
    <type>TextArea</type>
</CustomField>

uipath-service/main/default/objects/Living_Summary_History__c/fields/New_Value__c.field-meta.xml
<CustomField>
    <fullName>New_Value__c</fullName>
    <label>New Value</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

uipath-service/main/default/objects/Living_Summary_History__c/fields/Old_Value__c.field-meta.xml
<CustomField>
    <fullName>Old_Value__c</fullName>
    <label>Old Value</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

uipath-service/main/default/classes/CaseLivingSummaryQueueable.cls
/**
 * TODO REWRITE
 * Move to Service Layer
 * this code was just moved here from the sync Trigger context into a Queueable Context.
 * Needs to be rewritten entirely
 * Inserts the Living Summary History on field changes
 */
public with sharing class CaseLivingSummaryQueueable extends AbstractQueueable {
  private final List<SObject> cases;
  private final Map<Id, SObject> oldCasessMap;
  public CaseLivingSummaryQueueable(List<SObject> cases, Map<Id, SObject> oldCasessMap) {
    super('CaseLivingSummaryQueueable');
    this.cases = cases;
    this.oldCasessMap = oldCasessMap;
  }

  public override void work() {
    System.debug('CaseLivingSummaryQueueable work');
    this.createLivingSummaryHistory(cases, oldCasessMap);
  }

  public void createLivingSummaryHistory(List<Case> cases, Map<Id, SObject> existingCases) {
    Set<SObjectField> caseFields = new Set<SObjectField>{
      Case.Problem__c,
      Case.Cause__c,
      Case.Validation__c,
      Case.Solution__c,
      Case.Solution_Instructions__c
    };
    SObjectPredicate hasChanged = new HasRecordChanged(caseFields, cases, existingCases);
    List<Case> eligibleCases = (List<Case>) Collection.of(cases).filter(hasChanged).asList();

    if (!eligibleCases.isEmpty()) {
      List<Living_Summary_History__c> livingSummaryHistoryList = new List<Living_Summary_History__c>();
      for (Case newCase : eligibleCases) {
        Case oldCase = (Case) existingCases.get(newCase.Id);
        oldCase.get(Case.Problem__c);
        for (SObjectField caseField : caseFields) {
          if (oldCase.get(caseField) != newCase.get(caseField)) {
            Living_Summary_History__c livingSummary = new Living_Summary_History__c();
            livingSummary.Case__c = newCase.Id;
            livingSummary.Field_Name__c = caseField.getDescribe().getName();
            livingSummary.New_Value__c = (String) newCase.get(caseField);
            livingSummary.Old_Value__c = (String) oldCase.get(caseField);
            livingSummaryHistoryList.add(livingSummary);
            break;
          }
        }
      }
      if (!livingSummaryHistoryList.isEmpty()) {
        System.debug(livingSummaryHistoryList.size());
        System.debug(livingSummaryHistoryList);

        insert livingSummaryHistoryList;
      }
    }
  }
}