uipath-service/main/default/objects/Case/fields/Comm_Value__c.field-meta.xml
<CustomField>
    <fullName>Comm_Value__c</fullName>
    <label>Comm Value</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>FR Sent</fullName>
            </value>
            <value>
                <fullName>Comm Violated</fullName>
            </value>
            <value>
                <fullName>Comm Completed</fullName>
            </value>
            <value>
                <fullName>Comm Success</fullName>
            </value>
            <value>
                <fullName>FR Voilated</fullName>
            </value>
            <value>
                <fullName>Comm Running</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

uipath-service/main/default/objects/Case/fields/First_Response_Time_Stamp__c.field-meta.xml
<CustomField>
    <fullName>First_Response_Time_Stamp__c</fullName>
    <label>First Response Time Stamp</label>
    <type>DateTime</type>
</CustomField>

uipath-service/main/default/objects/Case/fields/No_of_Emails_Sent__c.field-meta.xml
<CustomField>
    <fullName>No_of_Emails_Sent__c</fullName>
    <label>No. of Emails Sent</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

uipath-service/main/default/classes/CaseUpdateCommValueFunction.cls
public with sharing class CaseUpdateCommValueFunction implements SObjectToSObjectFunction {
  private Map<Id, SObject> oldCases;

  public CaseUpdateCommValueFunction(List<Case> cases) {
    this.oldCases = oldCases;
  }

  public SObject apply(Case caseRecord) {
    if (
      caseRecord.RecordTypeId == CaseMetadata.AcademyRecordType ||
      caseRecord.RecordTypeId == CaseMetadata.SalesOperationRecordType ||
      caseRecord.RecordTypeId == CaseMetadata.ServiceRequestRecordType
    ) {
      caseRecord.Status = 'Customer Action';
    } else {
      caseRecord.Status = 'In Process';
    }
    caseRecord.First_Response_Time_Stamp__c = System.now();
    caseRecord.Comm_Value__c = 'FR Sent';
    return caseRecord;
  }

  public SObject apply(SObject record) {
    return apply((Case) record);
  }

  public static void deriveCommValue(List<Case> records) {
    Collection.of(records)
      .mapSome(
        Match.field(Case.First_Response_Time_Stamp__c)
          .equals(null)
          .also(Case.No_of_Emails_Sent__c)
          .equals(2)
          .also(Case.RecordTypeId)
          .isIn(
            new Set<String>{
              CaseMetadata.IncidentRecordType,
              CaseMetadata.ServiceRequestRecordType,
              CaseMetadata.EngagementRequestRecordType,
              CaseMetadata.JapanEngagementRequestRecordType,
              CaseMetadata.JapanAcademyRecordType,
              CaseMetadata.AcademyRecordType,
              CaseMetadata.SalesOperationRecordType,
              CaseMetadata.JapanLicensingRecordType,
              CaseMetadata.JapanIncidentRecordType,
              CaseMetadata.ServiceIncidentRecordType
            }
          ),
        new CaseUpdateCommValueFunction(records)
      );
  }
}