uipath-service/main/default/objects/Case/fields/Continue_with_Unassigned_Account__c.field-meta.xml
<CustomField>
    <fullName>Continue_with_Unassigned_Account__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Display  warning message if account=&apos;Unassigned Account&apos; at the time case closure if it is checked</description>
    <label>Continue with Unassigned Account?</label>
    <type>Checkbox</type>
</CustomField>

uipath-service/main/default/objects/Case/fields/Resolution_Summary__c.field-meta.xml
<CustomField>
    <fullName>Resolution_Summary__c</fullName>
    <description>It is required when status=closed</description>
    <label>Resolution Summary</label>
    <length>131072</length>
    <type>Html</type>
</CustomField>

uipath-service/main/default/objects/Case/fields/Solution__c.field-meta.xml
<CustomField>
    <fullName>Solution__c</fullName>
    <inlineHelpText>Technical summary of the solution</inlineHelpText>
    <label>Solution</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

uipath-service/main/default/objects/Case/fields/Steps_Performed__c.field-meta.xml
<CustomField>
    <fullName>Steps_Performed__c</fullName>
    <label>Steps Performed</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

uipath-service/main/default/classes/CaseSetAutocloseStepsFunction.cls
public with sharing class CaseSetAutocloseStepsFunction implements SObjectToSObjectFunction {
  private Map<Id, SObject> oldCases;

  public CaseSetAutocloseStepsFunction(List<Case> cases) {
    this.oldCases = oldCases;
  }

  public SObject apply(Case caseRecord) {
    caseRecord.Solution__c = 'Autoclose Case Origin Email case';
    caseRecord.Steps_Performed__c = 'Autoclose Case Origin Email case';
    caseRecord.Resolution_Summary__c = 'Autoclose Case Origin Email case';
    caseRecord.Continue_with_Unassigned_Account__c = true;
    return caseRecord;
  }

  public SObject apply(SObject record) {
    return apply((Case) record);
  }

  public static void deriveAutocloseSteps(List<Case> records) {
    Collection.of(records)
      .filter(
        Match.field(Case.RecordTypeId)
          .isIn(
            new Set<String>{
              CaseMetadata.IncidentRecordType,
              CaseMetadata.AcademyRecordType,
              CaseMetadata.SalesOperationRecordType,
              CaseMetadata.ServiceRequestRecordType
            }
          )
      )
      .mapSome(
        Match.field(Case.Origin)
          .equals('Email')
          .also(Case.SuppliedEmail)
          .notIn(new Set<String>{ 'notify@ringcentral.com', 'service@ringcentral.com' }),
        new CaseSetAutocloseStepsFunction(records)
      );
  }
}