uipath-service/main/default/objects/Case/fields/Continue_with_Unassigned_Account__c.field-meta.xml
<CustomField>
    <fullName>Continue_with_Unassigned_Account__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Display  warning message if account=&apos;Unassigned Account&apos; at the time case closure if it is checked</description>
    <label>Continue with Unassigned Account?</label>
    <type>Checkbox</type>
</CustomField>

uipath-service/main/default/objects/Case/fields/Resolution_Summary__c.field-meta.xml
<CustomField>
    <fullName>Resolution_Summary__c</fullName>
    <description>It is required when status=closed</description>
    <label>Resolution Summary</label>
    <length>131072</length>
    <type>Html</type>
</CustomField>

uipath-service/main/default/objects/Case/fields/Solution__c.field-meta.xml
<CustomField>
    <fullName>Solution__c</fullName>
    <inlineHelpText>Technical summary of the solution</inlineHelpText>
    <label>Solution</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

uipath-service/main/default/objects/Case/fields/Steps_Performed__c.field-meta.xml
<CustomField>
    <fullName>Steps_Performed__c</fullName>
    <label>Steps Performed</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

uipath-service/main/default/classes/CaseSetAutocloseStepsFunctionTest.cls
@IsTest
public class CaseSetAutocloseStepsFunctionTest {
  @IsTest
  private static void testSetAutocloseStepsFunction() {
    Id caseId = fflib_IDGenerator.generate(Case.SObjectType);
    Id incidentRecordTypeID = CaseMetadata.IncidentRecordType;

    Case cs = new Case(
      Id = caseId,
      Subject = 'Test',
      RecordTypeId = incidentRecordTypeID,
      Status = 'New',
      Origin = 'Email'
    );

    fflib_SObjectDomain.Test.Database.onInsert(new List<Case>{ cs });

    fflib_SObjectDomain.triggerHandler(Cases.class);
    System.assertEquals(true, cs.Continue_with_Unassigned_Account__c);
    System.assertEquals('Autoclose Case Origin Email case', cs.Solution__c);
    System.assertEquals('Autoclose Case Origin Email case', cs.Steps_Performed__c);
    System.assertEquals('Autoclose Case Origin Email case', cs.Resolution_Summary__c);
  }
}