uipath-service/main/default/objects/Case/fields/Customer_Contact__c.field-meta.xml
<CustomField>
    <fullName>Customer_Contact__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Customer Contact</label>
    <type>Checkbox</type>
</CustomField>

uipath-service/main/default/objects/Case/fields/No_of_Emails_Sent__c.field-meta.xml
<CustomField>
    <fullName>No_of_Emails_Sent__c</fullName>
    <label>No. of Emails Sent</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

uipath-service/main/default/classes/CaseEmailSentFunction.cls
/**
 * Sets IsClosed_NotifyOnMail to TRUE after Closed Email is sent.
 */
public class CaseEmailSentFunction implements SObjectToSObjectFunction {
  public CaseEmailSentFunction(List<Case> cases) {
  }

  public SObject apply(Case record) {
    record.Customer_Contact__c = true;
    record.Status = 'Customer Action';
    return record;
  }

  public SObject apply(SObject record) {
    return apply((Case) record);
  }

  public static void deriveCustomerContact(List<SObject> Records, Map<Id, SObject> existingRecords) {
    SObjectPredicate hasChanged = new HasRecordChanged(
      new Set<SObjectField>{ Case.No_of_Emails_Sent__c },
      Records,
      existingRecords
    );

    Collection.of(Records)
      .filter(hasChanged)
      .filter(
        Match.field(Case.RecordTypeId)
          .isIn(
            new Set<String>{
              CaseMetadata.AcademyRecordType,
              CaseMetadata.SalesOperationRecordType,
              CaseMetadata.ServiceRequestRecordType
            }
          )
      )
      .mapSome(Match.field(Case.No_of_Emails_Sent__c).greaterThanOrEquals(2), new CaseEmailSentFunction(Records));
  }
}