uipath-service/main/default/objects/Case/fields/IsClosed_NotifyOnMail__c.field-meta.xml
<CustomField>
    <fullName>IsClosed_NotifyOnMail__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This flag is used in reopen notification process builder to avoid looping</description>
    <label>IsClosed_NotifyOnMail</label>
    <type>Checkbox</type>
</CustomField>

uipath-service/main/default/objects/Case/fields/No_of_Emails_Received__c.field-meta.xml
<CustomField>
    <fullName>No_of_Emails_Received__c</fullName>
    <defaultValue>0</defaultValue>
    <label>No. of Emails Received</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

uipath-service/main/default/classes/CaseReOpenEmailCheckboxFunction.cls
/**
 * Sets IsClosed_NotifyOnMail to TRUE after Closed Email is sent.
 */
public class CaseReOpenEmailCheckboxFunction implements SObjectToSObjectFunction {
  
    public CaseReOpenEmailCheckboxFunction(List<Case> cases) {
    }
  
    public SObject apply(Case record) {
      record.IsClosed_NotifyOnMail__c = TRUE;
      return record;
    }
  
    public SObject apply(SObject record) {
      return apply((Case) record);
    }
  
    public static void deriveCheckboxOnUpdate(List<Case> records) {

        SObjectPredicate hasChanged = new HasRecordChanged(
            new Set<SObjectField>{ Case.No_of_Emails_Received__c },
            cases,
            existingCases
          );

      Collection.of(accounts).filter(hasCountryChanged)
      .mapAll(new CaseReOpenEmailCheckboxFunction(records));

    }
  }
  