uipath-service/main/default/objects/Case/fields/Status_Resolved_Time_Stamp__c.field-meta.xml
<CustomField>
    <fullName>Status_Resolved_Time_Stamp__c</fullName>
    <label>Resolved Time Stamp</label>
    <type>DateTime</type>
</CustomField>

uipath-service/main/default/objects/Case/fields/Total_time_duration__c.field-meta.xml
<CustomField>
    <fullName>Total_time_duration__c</fullName>
    <label>Total Time Taken To Close in Minutes</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

uipath-service/main/default/classes/CaseCalculateTotalTimeFunctionTest.cls
@IsTest
public class CaseCalculateTotalTimeFunctionTest {
  @IsTest
  private static void testDeriveTotalTimeOnUpdate() {
    Id caseId = fflib_IDGenerator.generate(Case.SObjectType);
    Id incidentRecordTypeID = CaseMetadata.IncidentRecordType;
    Case oldCase = new Case(Id = caseId, Subject = 'Test', RecordTypeId = incidentRecordTypeID, Status = 'New');

    Case updatedCase = new Case(Id = caseId, Subject = 'Test', RecordTypeId = incidentRecordTypeID, Status = 'Closed');

    fflib_SObjectDomain.Test.Database.onUpdate(
      new List<Case>{ updatedCase },
      new Map<Id, SObject>{ oldCase.Id => oldCase }
    );

    fflib_SObjectDomain.triggerHandler(Cases.class);
    System.assertEquals(true, updatedCase.Total_time_duration__c > 3);
    System.assertEquals(true, updatedCase.Status_Resolved_Time_Stamp__c < system.now());
  }
}