uipath-commons/main/default/objects/Address__c/Address__c.object-meta.xml
<CustomObject>
    <description>Object to hold the Customer Address details</description>
    <label>Address</label>
    <nameField>
        <displayFormat>ADD-{000000}</displayFormat>
        <label>Address ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Addresses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

uipath-commons/main/default/objects/Address__c/fields/State__c.field-meta.xml
<CustomField>
        <fullName>State__c</fullName>
        <description>State</description>
        <inlineHelpText>State</inlineHelpText>
        <label>State</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Country__c</controllingField>
            <restricted>true</restricted>
            <valueSetName>States_Global_List</valueSetName>
        </valueSet>
    </CustomField>

uipath-commons/main/default/globalValueSets/States_Global_List.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Acre</fullName>
    </customValue>
    <customValue>
        <fullName>Aguascalientes</fullName>
    </customValue>
    <customValue>
        <fullName>Alabama</fullName>
    </customValue>
    <customValue>
        <fullName>Alagoas</fullName>
    </customValue>
    <customValue>
        <fullName>Alaska</fullName>
    </customValue>
    <customValue>
        <fullName>Alberta</fullName>
    </customValue>
    <customValue>
        <fullName>Amapá</fullName>
    </customValue>
    <customValue>
        <fullName>Amazonas</fullName>
    </customValue>
    <customValue>
        <fullName>Andaman and Nicobar Islands</fullName>
    </customValue>
    <customValue>
        <fullName>Andhra Pradesh</fullName>
    </customValue>
    <customValue>
        <fullName>Anhui</fullName>
    </customValue>
    <customValue>
        <fullName>Arizona</fullName>
    </customValue>
    <customValue>
        <fullName>Arkansas</fullName>
    </customValue>
    <customValue>
        <fullName>Arunachal Pradesh</fullName>
    </customValue>
    <customValue>
        <fullName>Assam</fullName>
    </customValue>
    <customValue>
        <fullName>Bahia</fullName>
    </customValue>
    <customValue>
        <fullName>Baja California</fullName>
    </customValue>
    <customValue>
        <fullName>Baja California Sur</fullName>
    </customValue>
    <customValue>
        <fullName>Beijing</fullName>
    </customValue>
    <customValue>
        <fullName>Bihar</fullName>
    </customValue>
    <customValue>
        <fullName>British Columbia</fullName>
    </customValue>
    <customValue>
        <fullName>California</fullName>
    </customValue>
    <customValue>
        <fullName>Campeche</fullName>
    </customValue>
    <customValue>
        <fullName>Ceara</fullName>
    </customValue>
    <customValue>
        <fullName>Chandigarh</fullName>
    </customValue>
    <customValue>
        <fullName>Chhattisgarh</fullName>
    </customValue>
    <customValue>
        <fullName>Chiapas</fullName>
    </customValue>
    <customValue>
        <fullName>Chihuahua</fullName>
    </customValue>
    <customValue>
        <fullName>Chinese Taipei</fullName>
    </customValue>
    <customValue>
        <fullName>Chongqing</fullName>
    </customValue>
    <description>Created for the new Address object and will be used for other objects (involved in integration with NetSuite)</description>
    <masterLabel>States Global List</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet>

uipath-commons/main/default/classes/AccountMetadata.cls
public without sharing class AccountMetadata {

    private static List<String> AvailableCountryStatesCached;

    public static List<String> AvailableCountryStates {
        get {
            if (AvailableCountryStatesCached == null) {
                AvailableCountryStatesCached = new List<String>();

                Schema.DescribeFieldResult stateResult = Address__c.State__c.getDescribe();
                List<Schema.PicklistEntry> statePLE = stateResult.getPicklistValues();

                for (Schema.PicklistEntry entry : statePLE) {
                    AvailableCountryStatesCached.add(entry.getValue());
                }
            }
            return AvailableCountryStatesCached;
        }
    }


    private static Map<String, String> CountryCodesCached;

    public static Map<String, String> CountryCodes {
        get {
            if (CountryCodesCached == null) {
                CountryCodesCached = new Map<String, String>();

                //Retrieve Country Codes
                Schema.DescribeFieldResult countryCodeResult = User.Countrycode.getDescribe();
                List<Schema.PicklistEntry> countryPLE = countryCodeResult.getPicklistValues();
                for (Schema.PicklistEntry entry : countryPLE) {
                    CountryCodesCached.put(entry.getValue(), entry.getLabel());
                }
            }
            return CountryCodesCached;
        }
    }

}