uipath-sales/main/default/objects/Case/recordTypes/Finance_Request.recordType-meta.xml
<RecordType>
    <fullName>Finance_Request</fullName>
    <active>true</active>
    <businessProcess>Finance Request</businessProcess>
    <label>Finance Request</label>
</RecordType>

uipath-sales/main/default/objects/Case/recordTypes/Legal_Product_Request.recordType-meta.xml
<RecordType>
    <fullName>Legal_Product_Request</fullName>
    <active>true</active>
    <businessProcess>Legal Request</businessProcess>
    <label>Legal Product Request</label>
</RecordType>

uipath-sales/main/default/objects/Case/recordTypes/Legal_Request.recordType-meta.xml
<RecordType>
    <fullName>Legal_Request</fullName>
    <active>true</active>
    <businessProcess>Legal Request</businessProcess>
    <label>Legal Request</label>
</RecordType>

uipath-sales/main/default/objects/Case/recordTypes/UiPath_Japan_Partner_standard.recordType-meta.xml
<RecordType>
    <fullName>UiPath_Japan_Partner_standard</fullName>
    <active>true</active>
    <businessProcess>Japan Partner Support Process</businessProcess>
    <description>コミュニティ用に作成</description>
    <label>UiPath Japan Partner standard</label>
</RecordType>

uipath-sales/main/default/objects/Template_Mapping__mdt/Template_Mapping__mdt.object-meta.xml
<CustomObject>
    <description>Document Type to Conga template Id mappings.</description>
    <label>Template Mapping</label>
    <pluralLabel>Template Mappings</pluralLabel>
</CustomObject>

uipath-sales/main/default/objects/Template_Mapping__mdt/fields/CongaTemplateId__c.field-meta.xml
<CustomField>
    <fullName>CongaTemplateId__c</fullName>
    <label>Conga Template Id</label>
    <length>18</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

uipath-sales/main/default/objects/Template_Mapping__mdt/fields/DocumentLanguage__c.field-meta.xml
<CustomField>
    <fullName>DocumentLanguage__c</fullName>
    <label>Document Language</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>English</fullName>
                <default>true</default>
                <label>English</label>
            </value>
            <value>
                <fullName>日本語</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

uipath-sales/main/default/objects/Template_Mapping__mdt/fields/DocumentType__c.field-meta.xml
<CustomField>
    <fullName>DocumentType__c</fullName>
    <label>Document Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Academic Alliance Agreement</fullName>
                <default>true</default>
                <label>Academic Alliance Agreement</label>
            </value>
            <value>
                <fullName>Affiliate Adoption Agreement</fullName>
            </value>
            <value>
                <fullName>BAA</fullName>
            </value>
            <value>
                <fullName>BPO版EULA（MA）</fullName>
            </value>
            <value>
                <fullName>BPO版LO</fullName>
            </value>
            <value>
                <fullName>BPO版MSSA</fullName>
            </value>
            <value>
                <fullName>DPA</fullName>
            </value>
            <value>
                <fullName>EAAP Agreement</fullName>
            </value>
            <value>
                <fullName>EAAP Agreement for GSI</fullName>
            </value>
            <value>
                <fullName>EULA Addendum</fullName>
            </value>
            <value>
                <fullName>Federal Resale Addendum</fullName>
            </value>
            <value>
                <fullName>Federal System Integrator Partner Agreement</fullName>
            </value>
            <value>
                <fullName>Global Deal版EULA（MA）</fullName>
            </value>
            <value>
                <fullName>Global Deal版MSSA</fullName>
            </value>
            <value>
                <fullName>License Compliance Notice</fullName>
            </value>
            <value>
                <fullName>MPA Addendum</fullName>
            </value>
            <value>
                <fullName>MPA Indirect Resale + BPO Agreement (CN)</fullName>
            </value>
            <value>
                <fullName>MPA Indirect Resale Only Agreement (CN)</fullName>
            </value>
            <value>
                <fullName>MSSA</fullName>
            </value>
            <value>
                <fullName>NDA</fullName>
            </value>
            <value>
                <fullName>NDA（相互秘密保持契約）</fullName>
            </value>
            <value>
                <fullName>Partner BPO Only Agreement</fullName>
            </value>
            <value>
                <fullName>Partner Confirmation Letter</fullName>
            </value>
            <value>
                <fullName>Partner Resale + BPO Agreement</fullName>
            </value>
            <value>
                <fullName>Partner Resale Only Agreement</fullName>
            </value>
            <value>
                <fullName>Reverse Reseller</fullName>
            </value>
            <value>
                <fullName>Select One</fullName>
            </value>
            <value>
                <fullName>Teaming Agreement</fullName>
            </value>
            <value>
                <fullName>Technology Alliance Agreement</fullName>
            </value>
            <value>
                <fullName>Technology Alliance Deal Referral Addendum</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

uipath-sales/main/default/classes/SalesCaseMetadata.cls
public without sharing class SalesCaseMetadata {
  public static final String TECHNOLOGY_ALLIANCE_AGREEMENT = 'Technology Alliance Agreement';
  public static final String SIGNED = 'Signed';
  public static final String NOT_SIGNED = 'Not Signed';

  public static final String NON_EDITABLE_STANDARD = 'UiPath Template Non-Editable (Standard)';
  public static final String EDITABLE_STANDARD = 'UiPath Template Editable';

  //Cases Status
  public static final String PENDING_SALES_INFORMATION = 'Pending Sales Information';
  public static final String IN_PROGRESS = 'In Progress';
  public static final String DEAL_HUB_REVIEW = 'Deal Hub Review';
  public static final String FINANCE_REVIEW = 'Finance Review';
  public static final String LEGAL_REVIEW = 'Legal Review';
  public static final String READY_FOR_SIGNATURE = 'Ready for signature';
  public static final String MASTER_DATA_REVIEW = 'Master Data Review';

  //RecordType API Names
  private static final String LEGAL_PRODUCT_REQUEST = 'Legal_Product_Request';
  private static final String LEGAL_REQUEST = 'Legal_Request';
  private static final String UIPATH_JAPAN_PARTNER_STANDARD = 'UiPath_Japan_Partner_standard';
  private static final String FINANCE_REQUEST = 'Finance_Request';

  public static Id getRecordTypeId(String developerName) {
    Id recordTypeId = Schema.SObjectType.Case.getRecordTypeInfosByDeveloperName().get(developerName).getRecordTypeId();
    return recordTypeId;
  }

  public static Id LegalProductRequestRecordType {
    get {
      return getRecordTypeId(LEGAL_PRODUCT_REQUEST);
    }
    set;
  }

  public static Id LegalRequestRecordType {
    get {
      return getRecordTypeId(LEGAL_REQUEST);
    }
    set;
  }

  public static Id UiPathJapanPartnerStandardRecordType {
    get {
      return getRecordTypeId(UIPATH_JAPAN_PARTNER_STANDARD);
    }
    set;
  }

  public static Id FinanceRequestRecordType {
    get {
      return getRecordTypeId(FINANCE_REQUEST);
    }
    set;
  }

  public static Map<String, String> DocumentTypeMapping {
    get {
      if (DocumentTypeMapping == null) {
        DocumentTypeMapping = new Map<String, String>();
        for (Template_Mapping__mdt templateMapping : [
          SELECT Id, IsActive__c, CongaTemplateId__c, DocumentType__c
          FROM Template_Mapping__mdt
          WHERE IsActive__c = true AND DocumentLanguage__c = null
        ]) {
          DocumentTypeMapping.put(templateMapping.DocumentType__c, templateMapping.CongaTemplateId__c);
        }
      }
      return DocumentTypeMapping;
    }
    set;
  }

  public static Set<String> DocumentTypesWithLanguages {
    get {
      if (DocumentTypesWithLanguages == null) {
        DocumentTypesWithLanguages = new Set<String>();
        for (Template_Mapping__mdt templateMapping : [
          SELECT Id, IsActive__c, CongaTemplateId__c, DocumentType__c
          FROM Template_Mapping__mdt
          WHERE IsActive__c = true AND DocumentLanguage__c != null
        ]) {
          DocumentTypesWithLanguages.add(templateMapping.DocumentType__c);
        }
      }
      return DocumentTypesWithLanguages;
    }
    set;
  }

  public static Map<String, String> DocumentTypeLanguageMapping {
    get {
      if (DocumentTypeLanguageMapping == null) {
        DocumentTypeLanguageMapping = new Map<String, String>();
        for (Template_Mapping__mdt templateMapping : [
          SELECT Id, IsActive__c, CongaTemplateId__c, DocumentType__c, DocumentLanguage__c
          FROM Template_Mapping__mdt
          WHERE IsActive__c = true AND DocumentLanguage__c != null
        ]) {
          DocumentTypeLanguageMapping.put(
            templateMapping.DocumentLanguage__c + templateMapping.DocumentType__c,
            templateMapping.CongaTemplateId__c
          );
        }
      }
      return DocumentTypeLanguageMapping;
    }
    set;
  }
}