uipath-commons/main/default/objects/ZinfiConfiguration__c/ZinfiConfiguration__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Store settings for Zinfi Integration</description>
    <label>Zinfi Configuration</label>
</CustomObject>

uipath-commons/main/default/objects/ZinfiConfiguration__c/fields/WebHook__c.field-meta.xml
<CustomField>
    <fullName>WebHook__c</fullName>
    <description>Zinfi WebHook</description>
    <label>WebHook</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

uipath-commons/main/default/objects/ZinfiConfiguration__c/fields/WebhookEndPoint__c.field-meta.xml
<CustomField>
    <fullName>WebhookEndPoint__c</fullName>
    <description>Zinfi callout end point</description>
    <label>WebhookEndPoint</label>
    <type>Url</type>
</CustomField>

uipath-commons/main/default/objects/ZinfiConfiguration__c/fields/WebToken__c.field-meta.xml
<CustomField>
    <fullName>WebToken__c</fullName>
    <description>Zinfi WebToken</description>
    <label>WebToken</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

uipath-commons/main/default/classes/ZinfiSyncOnline.cls
/**
 * TODO refactor code in next iteration
 */
@SuppressWarnings('PMD')
public class ZinfiSyncOnline {
  @future(callout=true)
  public static void sendAccountFutureCall(Set<Id> IdList) {
    ZinfiConfiguration__c zinfiSetting = ZinfiConfiguration__c.getInstance();
    List<AccountWrapper> WList = new List<AccountWrapper>();
    /* List<Account> SoList = [SELECT Id,Name 
        FROM Account
        Where ID in:IdList];
        */
    for (string n : IdList) {
      AccountWrapper nw = new AccountWrapper();
      nw.Id = n;
      nw.Name = 'Name';
      WList.add(nw);
    }
    String strbdy = JSON.serialize(WList);
    System.debug(':::strbdy=' + strbdy);
    Http htp = new Http();
    HttpRequest hr = new HttpRequest();
    hr.setMethod('POST');
    hr.setEndPoint(zinfiSetting.WebhookEndPoint__c);

    hr.setBody(strbdy);
    hr.setHeader('Content-Type', 'application/json');
    hr.setHeader('Accept', 'application/json');
    hr.setHeader('WebToken', zinfiSetting.WebToken__c);
    hr.setHeader('WebHook', zinfiSetting.WebHook__c);
    System.debug(':::hr=' + hr);
    try {
      HttpResponse hs = htp.send(hr);
      String rsStr = hs.getBody();
      System.debug('***** response=' + rsStr);
      System.debug('***** StatusCode =' + hs.getStatusCode());
    } catch (Exception e) {
      System.debug('***** Exception=' + e.getMessage());
    }
  }

  public class AccountWrapper {
    public string Id;
    public string Name;
  }
}