uipath-sales/main/default/objects/AI_Early_Access_Program__c/AI_Early_Access_Program__c.object-meta.xml
<CustomObject>    
    <label>Early Access &amp; Adoption Program</label>
    <nameField>
        <displayFormat>EAAP-{0000}</displayFormat>
        <label>Program Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Early Access &amp; Adoption Programs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

uipath-sales/main/default/objects/Case/fields/AI_Early_Access_Program__c.field-meta.xml
<CustomField>
    <fullName>AI_Early_Access_Program__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>AI Early Access Program</label>
    <referenceTo>AI_Early_Access_Program__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>AI_Early_Access_Program</relationshipName>
    <type>Lookup</type>
</CustomField>

uipath-sales/main/default/objects/Case/fields/Conga_Template_2__c.field-meta.xml
<CustomField>
    <fullName>Conga_Template_2__c</fullName>
    <description>This field determines the template for the generating a document based on Document Type.</description>
    <inlineHelpText>This field determines the template for the generating a document based on Document Type.</inlineHelpText>
    <label>Conga Template</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

uipath-sales/main/default/objects/Case/fields/Document_Language__c.field-meta.xml
<CustomField>
    <fullName>Document_Language__c</fullName>
    <label>Document Language</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Document_Type__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>English</fullName>
            </value>
            <value>
                <fullName>日本語</fullName>
            </value>
            <value>
                <fullName>French</fullName>
            </value>
            <value>
                <fullName>Russian</fullName>
            </value>
            <value>
                <fullName>Polish</fullName>
            </value>
            <value>
                <fullName>Spanish</fullName>
            </value>
            <value>
                <fullName>Portuguese</fullName>
            </value>
            <value>
                <fullName>Chinese</fullName>
            </value>
            <value>
                <fullName>German</fullName>
                <isActive>false</isActive>
                <label>German</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

uipath-sales/main/default/objects/Case/fields/Document_Type__c.field-meta.xml
<CustomField>
    <fullName>Document_Type__c</fullName>
    <label>Document Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Academic Alliance Agreement</fullName>
            </value>
            <value>
                <fullName>Affiliate Adoption Agreement</fullName>
            </value>
            <value>
                <fullName>BAA</fullName>
            </value>
            <value>
                <fullName>DPA</fullName>
            </value>
            <value>
                <fullName>End Customer General Terms</fullName>
            </value>
            <value>
                <fullName>EULA Addendum</fullName>
            </value>
            <value>
                <fullName>Invoice</fullName>
            </value>
            <value>
                <fullName>Legal Inquiry</fullName>
            </value>
            <value>
                <fullName>MPA Addendum</fullName>
            </value>
            <value>
                <fullName>MPA Indirect Resale + BPO Agreement (CN)</fullName>
            </value>
            <value>
                <fullName>MPA Indirect Resale Only Agreement (CN)</fullName>
            </value>
            <value>
                <fullName>MSSA</fullName>
            </value>
            <value>
                <fullName>NDA</fullName>
            </value>
            <value>
                <fullName>NDA EAP</fullName>
            </value>
            <value>
                <fullName>Partner BPO Only Agreement</fullName>
            </value>
            <value>
                <fullName>Partner Resale + BPO Agreement</fullName>
            </value>
            <value>
                <fullName>Partner Resale Only Agreement</fullName>
            </value>
            <value>
                <fullName>Software License Broker</fullName>
            </value>
            <value>
                <fullName>Teaming Agreement</fullName>
            </value>
            <value>
                <fullName>Technology Alliance Agreement</fullName>
            </value>
            <value>
                <fullName>Trial Terms</fullName>
            </value>
            <value>
                <fullName>Undertaking by Original Software Developer (for Software) pre Signed</fullName>
            </value>
            <value>
                <fullName>USN Addendum</fullName>
            </value>
            <value>
                <fullName>Contract assignment to UiPath affiliate</fullName>
            </value>
            <value>
                <fullName>Termination</fullName>
            </value>
            <value>
                <fullName>Reverse Reseller</fullName>
            </value>
            <value>
                <fullName>Technology Alliance Agreement Addendum</fullName>
            </value>
            <value>
                <fullName>Technology Alliance Deal Referral Addendum</fullName>
            </value>
            <value>
                <fullName>License Compliance Notice</fullName>
            </value>
            <value>
                <fullName>Partner Confirmation Letter</fullName>
            </value>
            <value>
                <fullName>EAAP Agreement</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

uipath-sales/main/default/objects/Case/fields/Standard_Template__c.field-meta.xml
<CustomField>
    <fullName>Standard_Template__c</fullName>
    <inlineHelpText>Yes - Non-editable document will be generated (Contractual clauses cannot be amended; Products can be modified)
No - Editable document will be generated (Products and contractual clauses can be modified).</inlineHelpText>
    <label>Agreement Template</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
                <label>UiPath Template Non-Editable (Standard)</label>
            </value>
            <value>
                <fullName>No</fullName>
                <label>UiPath Template Editable</label>
            </value>
            <value>
                <fullName>Customer Template</fullName>
            </value>
            <value>
                <fullName>Partner Template</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

uipath-sales/main/default/objects/Template_Mapping__mdt/Template_Mapping__mdt.object-meta.xml
<CustomObject>
    <description>Document Type to Conga template Id mappings.</description>
    <label>Template Mapping</label>
    <pluralLabel>Template Mappings</pluralLabel>
</CustomObject>

uipath-sales/main/default/objects/Template_Mapping__mdt/fields/CongaTemplateId__c.field-meta.xml
<CustomField>
    <fullName>CongaTemplateId__c</fullName>
    <label>Conga Template Id</label>
    <length>18</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

uipath-sales/main/default/objects/Template_Mapping__mdt/fields/DocumentLanguage__c.field-meta.xml
<CustomField>
    <fullName>DocumentLanguage__c</fullName>
    <label>Document Language</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>English</fullName>
                <default>true</default>
                <label>English</label>
            </value>
            <value>
                <fullName>日本語</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

uipath-sales/main/default/objects/Template_Mapping__mdt/fields/DocumentType__c.field-meta.xml
<CustomField>
    <fullName>DocumentType__c</fullName>
    <label>Document Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Academic Alliance Agreement</fullName>
                <default>true</default>
                <label>Academic Alliance Agreement</label>
            </value>
            <value>
                <fullName>Affiliate Adoption Agreement</fullName>
            </value>
            <value>
                <fullName>BAA</fullName>
            </value>
            <value>
                <fullName>BPO版EULA（MA）</fullName>
            </value>
            <value>
                <fullName>BPO版LO</fullName>
            </value>
            <value>
                <fullName>BPO版MSSA</fullName>
            </value>
            <value>
                <fullName>DPA</fullName>
            </value>
            <value>
                <fullName>EAAP Agreement</fullName>
            </value>
            <value>
                <fullName>EAAP Agreement for GSI</fullName>
            </value>
            <value>
                <fullName>EULA Addendum</fullName>
            </value>
            <value>
                <fullName>Federal Resale Addendum</fullName>
            </value>
            <value>
                <fullName>Federal System Integrator Partner Agreement</fullName>
            </value>
            <value>
                <fullName>Global Deal版EULA（MA）</fullName>
            </value>
            <value>
                <fullName>Global Deal版MSSA</fullName>
            </value>
            <value>
                <fullName>License Compliance Notice</fullName>
            </value>
            <value>
                <fullName>MPA Addendum</fullName>
            </value>
            <value>
                <fullName>MPA Indirect Resale + BPO Agreement (CN)</fullName>
            </value>
            <value>
                <fullName>MPA Indirect Resale Only Agreement (CN)</fullName>
            </value>
            <value>
                <fullName>MSSA</fullName>
            </value>
            <value>
                <fullName>NDA</fullName>
            </value>
            <value>
                <fullName>NDA（相互秘密保持契約）</fullName>
            </value>
            <value>
                <fullName>Partner BPO Only Agreement</fullName>
            </value>
            <value>
                <fullName>Partner Confirmation Letter</fullName>
            </value>
            <value>
                <fullName>Partner Resale + BPO Agreement</fullName>
            </value>
            <value>
                <fullName>Partner Resale Only Agreement</fullName>
            </value>
            <value>
                <fullName>Reverse Reseller</fullName>
            </value>
            <value>
                <fullName>Select One</fullName>
            </value>
            <value>
                <fullName>Teaming Agreement</fullName>
            </value>
            <value>
                <fullName>Technology Alliance Agreement</fullName>
            </value>
            <value>
                <fullName>Technology Alliance Deal Referral Addendum</fullName>
            </value>
            <value>
                <fullName>Undertaking by Original Software Developer (for Software) pre Signed</fullName>
            </value>
            <value>
                <fullName>USN Addendum</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

uipath-sales/main/default/classes/SalesCaseDocumentTypeFunctionTest.cls
@IsTest
public class SalesCaseDocumentTypeFunctionTest {
  @IsTest
  private static void whenDocumentTypeAloneIsPresent_setTemplateId() {
    Id caseId = fflib_IDGenerator.generate(Case.SObjectType);
    Id accessId = fflib_IDGenerator.generate(AI_Early_Access_Program__c.SObjectType);

    Id reccordTypeId = SalesCaseMetadata.FinanceRequestRecordType;
    for (Template_Mapping__mdt templateMapping : [
      SELECT Id, IsActive__c, CongaTemplateId__c, DocumentType__c
      FROM Template_Mapping__mdt
      WHERE IsActive__c = true AND DocumentLanguage__c = null
      LIMIT 10
    ]) {
      Case newCase = new Case(
        Id = caseId,
        Subject = 'Test',
        RecordTypeId = reccordTypeId,
        Status = 'New',
        Document_Type__c = templateMapping.DocumentType__c,
        Conga_Template_2__c = ''
      );

      if (newCase.Document_Type__c.startsWith('EAAP Agreement')) {
        newCase.AI_Early_Access_Program__c = accessId;
      }
      if (newCase.Document_Type__c == 'Undertaking by Original Software Developer (for Software) pre Signed') {
        newCase.Standard_Template__c = SalesCaseMetadata.NON_EDITABLE_STANDARD;
      }
      if (newCase.Document_Type__c == 'USN Addendum') {
        continue;
      }
      fflib_SObjectDomain.Test.Database.onInsert(new List<Case>{ newCase });
      fflib_SObjectDomain.triggerHandler(SalesCases.class);
      System.assertEquals(
        newCase.Conga_Template_2__c,
        SalesCaseMetadata.DocumentTypeMapping.get(newCase.Document_Type__c)
      );
    }
  }

  @IsTest
  private static void whenDocumentTypeAndLanguageArePresent_setTemplateId() {
    Id caseId = fflib_IDGenerator.generate(Case.SObjectType);
    Id reccordTypeId = SalesCaseMetadata.FinanceRequestRecordType;

    for (Template_Mapping__mdt templateMapping : [
      SELECT Id, IsActive__c, CongaTemplateId__c, DocumentType__c, DocumentLanguage__c
      FROM Template_Mapping__mdt
      WHERE IsActive__c = true AND DocumentLanguage__c != null
    ]) {
      Case newCase = new Case(
        Id = caseId,
        Subject = 'Test',
        RecordTypeId = reccordTypeId,
        Status = 'New',
        Document_Type__c = templateMapping.DocumentType__c,
        Document_Language__c = templateMapping.DocumentLanguage__c,
        Conga_Template_2__c = ''
      );

      if (newCase.Document_Type__c.startsWith('MPA Indirect Resale') || newCase.Document_Type__c != 'DPA') {
        continue;
      }
      fflib_SObjectDomain.Test.Database.onInsert(new List<Case>{ newCase });
      fflib_SObjectDomain.triggerHandler(SalesCases.class);
      System.assertEquals(
        newCase.Conga_Template_2__c,
        SalesCaseMetadata.DocumentTypeMapping.get(newCase.Document_Type__c)
      );
    }
  }

  @IsTest
  private static void whenDocumentTypeAndLanguageArePresent_setTemplateIdOnUpdate() {
    Id caseId = fflib_IDGenerator.generate(Case.SObjectType);
    Id reccordTypeId = SalesCaseMetadata.FinanceRequestRecordType;

    for (Template_Mapping__mdt templateMapping : [
      SELECT Id, IsActive__c, CongaTemplateId__c, DocumentType__c, DocumentLanguage__c
      FROM Template_Mapping__mdt
      WHERE IsActive__c = true AND DocumentLanguage__c != null
    ]) {
      Case oldCase = new Case(Id = caseId, Subject = 'Test', RecordTypeId = reccordTypeId, Status = 'New');
      Case updatedCase = new Case(
        Id = caseId,
        Subject = 'Test',
        RecordTypeId = reccordTypeId,
        Status = 'New',
        Document_Type__c = templateMapping.DocumentType__c,
        Document_Language__c = templateMapping.DocumentLanguage__c,
        Conga_Template_2__c = ''
      );

      if (updatedCase.Document_Type__c.startsWith('MPA Indirect Resale') || updatedCase.Document_Type__c != 'DPA') {
        continue;
      }

      fflib_SObjectDomain.Test.Database.onUpdate(
        new List<Case>{ updatedCase },
        new Map<Id, SObject>{ oldCase.Id => oldCase }
      );
      fflib_SObjectDomain.triggerHandler(SalesCases.class);
      System.assertEquals(
        updatedCase.Conga_Template_2__c,
        SalesCaseMetadata.DocumentTypeMapping.get(updatedCase.Document_Type__c)
      );
    }
  }
}