uipath-core/main/default/objects/Account/fields/Country__c.field-meta.xml
<CustomField>
        <fullName>Country__c</fullName>
        <description>This required field will be used to capture the country on the creation of a new account. It will populate the country on the new address records for accounts. The standard billing and shipping address fields on account will be made read only.</description>
        <label>Country</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Country_Global_List</valueSetName>
        </valueSet>
    </CustomField>

uipath-sales/main/default/objects/Case/fields/Standard_Template__c.field-meta.xml
<CustomField>
    <fullName>Standard_Template__c</fullName>
    <inlineHelpText>Yes - Non-editable document will be generated (Contractual clauses cannot be amended; Products can be modified)
No - Editable document will be generated (Products and contractual clauses can be modified).</inlineHelpText>
    <label>Agreement Template</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
                <label>UiPath Template Non-Editable (Standard)</label>
            </value>
            <value>
                <fullName>No</fullName>
                <label>UiPath Template Editable</label>
            </value>
            <value>
                <fullName>Customer Template</fullName>
            </value>
            <value>
                <fullName>Partner Template</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

uipath-sales/main/default/objects/Case/fields/Standard_Template_Stamp__c.field-meta.xml
<CustomField>
    <fullName>Standard_Template_Stamp__c</fullName>
    <description>Standard template stamp. Populated by workflow rule, used in validation rule.</description>
    <label>Standard Template Stamp</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

uipath-core/main/default/globalValueSets/Country_Global_List.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Afghanistan</fullName>
    </customValue>
    <customValue>
        <fullName>Aland Islands</fullName>
    </customValue>
    <customValue>
        <fullName>Albania</fullName>
    </customValue>
    <customValue>
        <fullName>Algeria</fullName>
    </customValue>
    <customValue>
        <fullName>Andorra</fullName>
    </customValue>
    <customValue>
        <fullName>Angola</fullName>
    </customValue>
    <customValue>
        <fullName>Anguilla</fullName>
    </customValue>
    <customValue>
        <fullName>Antarctica</fullName>
    </customValue>
    <customValue>
        <fullName>Antigua and Barbuda</fullName>
    </customValue>
    <customValue>
        <fullName>Argentina</fullName>
    </customValue>
    <customValue>
        <fullName>Armenia</fullName>
    </customValue>
    <customValue>
        <fullName>Aruba</fullName>
    </customValue>
    <customValue>
        <fullName>Australia</fullName>
    </customValue>
    <customValue>
        <fullName>Austria</fullName>
    </customValue>
    <customValue>
        <fullName>Azerbaijan</fullName>
    </customValue>
    <customValue>
        <fullName>Bahamas</fullName>
    </customValue>
    <customValue>
        <fullName>Bahrain</fullName>
    </customValue>
    <customValue>
        <fullName>Bangladesh</fullName>
    </customValue>
    <customValue>
        <fullName>Barbados</fullName>
    </customValue>
    <customValue>
        <fullName>Belarus</fullName>
    </customValue>
    <customValue>
        <fullName>Belgium</fullName>
    </customValue>
    <customValue>
        <fullName>Belize</fullName>
    </customValue>
    <customValue>
        <fullName>Benin</fullName>
    </customValue>
    <customValue>
        <fullName>Bermuda</fullName>
    </customValue>
    <customValue>
        <fullName>Bhutan</fullName>
    </customValue>
    <customValue>
        <fullName>Bolivia, Plurinational State of</fullName>
    </customValue>
    <customValue>
        <fullName>Bonaire, Sint Eustatius and Saba</fullName>
    </customValue>
    <customValue>
        <fullName>Bosnia and Herzegovina</fullName>
    </customValue>
    <customValue>
        <fullName>Botswana</fullName>
    </customValue>
    <customValue>
        <fullName>Bouvet Island</fullName>
    </customValue>
    <customValue>
        <fullName>United Kingdom</fullName>
    </customValue>
    <description>Created for the new Address object and will be used for other objects (involved in integration with NetSuite)</description>
    <masterLabel>Country Global List</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet>

uipath-sales/main/default/classes/SalesCaseStandardTemplateStampTest.cls
@IsTest
public class SalesCaseStandardTemplateStampTest {
  @IsTest
  private static void testStandardTemplateStampOnInsert() {
    Id caseId = fflib_IDGenerator.generate(Case.SObjectType);
    Id accountId = fflib_IDGenerator.generate(Account.SObjectType);
    Id legalRequestRecordTypeId = SalesCaseMetadata.LegalRequestRecordType;

    Account acc = new Account(
      Id = accountId,
      Name = 'TestAccountUK',
      Country__c = 'United Kingdom',
      BillingCountry = 'United Kingdom',
      Industry = 'Others'
    );

    Case cs = new Case(
      AccountId = accountId,
      Id = caseId,
      Subject = 'Case1',
      RecordTypeId = legalRequestRecordTypeId,
      Status = 'New',
      Standard_Template__c = 'No'
    );

    fflib_SObjectDomain.Test.Database.onInsert(new List<Case>{ cs });

    fflib_SObjectDomain.triggerHandler(SalesCases.class);
    System.assertEquals('No', cs.Standard_Template_Stamp__c);
  }

  @IsTest
  private static void testStandardTemplateStampOnUpdate() {
    Id caseId = fflib_IDGenerator.generate(Case.SObjectType);
    Id accountId = fflib_IDGenerator.generate(Account.SObjectType);
    Id legalRequestRecordTypeId = SalesCaseMetadata.LegalRequestRecordType;

    Account acc = new Account(
      Id = accountId,
      Name = 'TestAccountUK',
      Country__c = 'United Kingdom',
      BillingCountry = 'United Kingdom',
      Industry = 'Others'
    );

    Case oldCase = new Case(
      AccountId = accountId,
      Id = caseId,
      Subject = 'Case1',
      RecordTypeId = legalRequestRecordTypeId,
      Status = 'New'
    );

    Case updatedCase = new Case(
      AccountId = accountId,
      Id = caseId,
      Subject = 'Case1',
      RecordTypeId = legalRequestRecordTypeId,
      Status = 'New',
      Standard_Template__c = 'No'
    );

    fflib_SObjectDomain.Test.Database.onUpdate(
      new List<Case>{ updatedCase },
      new Map<Id, SObject>{ oldCase.Id => oldCase }
    );

    fflib_SObjectDomain.triggerHandler(SalesCases.class);

    System.assertEquals('No', updatedCase.Standard_Template_Stamp__c);
  }
}