uipath-sales/main/default/objects/Case/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

uipath-sales/main/default/objects/Opportunity/fields/Number_of_Legal_Cases__c.field-meta.xml
<CustomField>
    <fullName>Number_of_Legal_Cases__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Counts number of legal cases associated with the opportunity</description>
    <label>Number of Legal Cases</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

uipath-sales/main/default/classes/SalesCaseLegalOpportunityQueueableTest.cls
@IsTest
public class SalesCaseLegalOpportunityQueueableTest {
  @TestSetup
  static void makeData() {
    Opportunity opp = new Opportunity(Name = 'Deal');
    opp.CurrencyISOCode = 'JPY';
    opp.StageName = 'In Progress';
    opp.CloseDate = System.today() + 10;
    insert opp;
  }

  @IsTest
  private static void whenNewLegalCaseIsCreatedOrDeleted_CountIsUpdated() {
    Opportunity opp = [SELECT Id, Number_of_Legal_Cases__c FROM Opportunity LIMIT 1];
    System.assertEquals(0, opp.Number_of_Legal_Cases__c, 'Legal Case count should be blank');
    Id legalRecordType = SalesCaseMetadata.LegalRequestRecordType;
    Case legalCase = new Case(
      Subject = 'Test',
      RecordTypeId = legalRecordType,
      Opportunity__c = opp.Id,
      Status = 'New'
    );

    insert legalCase;
    new SalesCaseLegalOpportunityQueueable(new List<Case>{ legalCase }).work();
    opp = [SELECT Id, Number_of_Legal_Cases__c FROM Opportunity LIMIT 1];
    System.assertEquals(1, opp.Number_of_Legal_Cases__c, 'Legal Case count is not updated');

    delete legalCase;
    new SalesCaseLegalOpportunityQueueable(new List<Case>{ legalCase }).work();
    opp = [SELECT Id, Number_of_Legal_Cases__c FROM Opportunity LIMIT 1];
    System.assertEquals(0, opp.Number_of_Legal_Cases__c, 'Legal Case count is not updated');
  }
}