uipath-sales/main/default/objects/Case/fields/Standard_Template__c.field-meta.xml
<CustomField>
    <fullName>Standard_Template__c</fullName>
    <inlineHelpText>Yes - Non-editable document will be generated (Contractual clauses cannot be amended; Products can be modified)
No - Editable document will be generated (Products and contractual clauses can be modified).</inlineHelpText>
    <label>Agreement Template</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
                <label>UiPath Template Non-Editable (Standard)</label>
            </value>
            <value>
                <fullName>No</fullName>
                <label>UiPath Template Editable</label>
            </value>
            <value>
                <fullName>Customer Template</fullName>
            </value>
            <value>
                <fullName>Partner Template</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

uipath-sales/main/default/objects/Case/fields/Standard_Template_Stamp__c.field-meta.xml
<CustomField>
    <fullName>Standard_Template_Stamp__c</fullName>
    <description>Standard template stamp. Populated by workflow rule, used in validation rule.</description>
    <label>Standard Template Stamp</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

uipath-sales/main/default/classes/SalesCaseStandardTemplateStampFunction.cls
/**
 * Sets Standard_Template_Stamp__c according to Standard_Template__c.
 */
public class SalesCaseStandardTemplateStampFunction implements SObjectToSObjectFunction {
  public SalesCaseStandardTemplateStampFunction(List<Case> cases) {
  }

  public SObject apply(Case record) {
    record.Standard_Template_Stamp__c = 'No';
    return record;
  }

  public SObject apply(SObject record) {
    return apply((Case) record);
  }

  public static void setStandardTemplateStampOnInsert(List<Case> records) {
    Collection.of(records)
      .filter(Match.field(Case.Standard_Template__c).isIn(new Set<String>{ 'No', 'Customer Template' }))
      .mapAll(new SalesCaseStandardTemplateStampFunction(records));
  }

  public static void setStandardTemplateStampOnUpdate(List<SObject> cases, Map<Id, SObject> existingCases) {
    HasRecordChanged templateChanged = new HasRecordChanged(
      new Set<SObjectField>{ Case.Standard_Template__c },
      cases,
      existingCases
    );

    Collection.of(cases)
      .filter(templateChanged)
      .filter(Match.field(Case.Standard_Template__c).isIn(new Set<String>{ 'No', 'Customer Template' }))
      .mapAll(new SalesCaseStandardTemplateStampFunction(cases));
  }
}